### ISSUE TITLE
Problems in fixed point for CRB

### ISSUE THREAD

**Issue by romainhild** [feelpp/feelpp#1016]
In crbmodel, in the function `solveFemUsingAffineDecompositionFixedPoint` in the non linear case, there is several problem with the loop [here](https://github.com/feelpp/feelpp/blob/develop/feel/feelcrb/crbmodel.hpp#L3631-L3663).
First, we print the residual norm of the previous iteration, so the loop can stop without the user knowing why.
Then the number of iteration is incremented after we check if it is not greater than the maximum. So if the user pass the following option `crb.fixedpoint.maxit=2`, the algorithm will do 3 iterations.

Should we not move the `cout` after the computation of the norm and the incrementation of `iter` before the check ?

**Comment by prudhomm** [comment]
Indeed it looks fishy please submit a PR, so that we can review your proposal
