### ISSUE TITLE
NLopt is not working anymore

### ISSUE THREAD

**Issue by romainhild** [feelpp/feelpp#1018]
The testsuite fails: 
```
Running 2 test cases...
unknown location(0): fatal error: in "nlopt/nlopt_test1": memory access violation at address: 0x7ffcb69b08b0: invalid permissions
/home/u2/hild/Devel/feelpp_hifi/testsuite/feelopt/test_nlopt.cpp(143): last checkpoint: "nlopt_test1" entry.
```
and one of my application (applications/crb/biotsavart/biotsavart_opt.cpp) is not working anymore with the following crash that happens in the `optimize` function.
```
*** Aborted at 1503423348 (unix time) try "date -d @1503423348" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGSEGV (@0x7fff0e0b8df0) received by PID 29477 (TID 0x7fa284ca9980) from PID 235638256; stack trace: ***
    @     0x7fa27c64f330 (unknown)
    @     0x7fff0e0b8df0 (unknown)
[1]    29477 segmentation fault (core dumped)  ./feelpp_crb_biotsavartCRBOpt --config-file bs-crb-torus3d/torus3d.cfg    10
```

**Comment by gdolle** [comment]
Might be linked to https://github.com/feelpp/feelpp/commit/c5b5e21969f3a6d8a5b88c0570dfcbd60d0fa18e#commitcomment-23814647. 
See comments.

**Comment by vincentchabannes** [comment]
@romainhild is it ok with last changes?
maybe you need to re-run ```git submodule update --init --recursive``` in feelpp repo

**Comment by romainhild** [comment]
@vincentchabannes @gdolle indeed it is ok now! Thanks
