### ISSUE TITLE
Toolboxes with Newton solver are broken

### ISSUE THREAD

**Issue by vincentchabannes** [feelpp/feelpp#1019]
There is this kind of error when we run a toolbox application with Newton solver : 
```
F0823 07:14:34.024991    63 functionspace.hpp:5006] Check failed: vecPetsc only petsc vector
*** Check failure stack trace: ***
    @     0x7f77152c9f88  google::LogMessage::Flush()
    @     0x7f77152cd45c  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f771cbf7cfd  _ZN4Feel13FunctionSpaceINS_4MeshINS_7SimplexILt2ELt1ELt2EEEdLi0EEENS_5basesIJNS_8LagrangeILt2ENS_9VectorialENS_10ContinuousENS_14PointSetFeketeELt0EEENS6_ILt1ENS_6ScalarES8_S9_Lt0EEEEEEN5boost9parameter5void_ESG_SG_E7elementERKNS_6VectorIdEEi
    @     0x7f771d4ea8a0  Feel::FeelModels::FluidMechanicsBase<>::updateNewtonInitialGuess()
    @     0x7f76e9b74f1c  Feel::FeelModels::ModelAlgebraicFactory::AlgoNewton2()
    @     0x7f771c83ceb3  Feel::FeelModels::FluidMechanicsBase<>::solve()
    @     0x7f771dda62a5  Feel::FeelModels::FluidMechanics<>::solve()
    @           0x411160  Feel::runApplicationFluid<>()
    @           0x40ba1e  main
    @     0x7f76e8b613f1  __libc_start_main
    @           0x40b5da  _start
    @              (nil)  (unknown)
```
It's due to a bad cast. I can't reproduce this problem in a simple example (it's also tested with ```feelpp_test_vector``` but there is no problem).  It seems appear from the merge with hdg or close to this date. @prudhomm I saw that you change the visibility of VectorPetsc class, it's maybe the reason?

In docker, we can reproduce the probem with this command : 
```
feelpp_toolbox_fluid_2d --config-file Testcases/CFD/TurekHron/cfd2.cfg 
```
or
```
feelpp_toolbox_solid_2d --config-file Testcases/CSM/TurekHron/csm3.cfg
```

**Comment by prudhomm** [comment]
I made some changes in block matrix and block vector for condensed data structure , could it be that?I won't have access to a computer for some time.

**Comment by metivett** [comment]
The problem seems indeed to come from the new ```VectorBlockBase``` management. Actually, the ```dynamic_cast``` at ```functionspace.hpp:5004``` fails because the cast vector (```vec```) has actual type ```VectorBlockBase``` and not ```VectorPetsc```. 
I think this comes from the change introduced in c87476184eee3e2bbfd686076e0ba771475a0d1e in ```backend.hpp: newBlockVectorImpl``` which returns ```boost::make_shared<vector_block_type>( b, *this, copy_values )``` (actual type: ```VectorBlockBase``` instead of ```mb->getVector()``` (type: ```VectorPetsc```) in the new version.
Was this change done on purpose ?

**Comment by vincentchabannes** [comment]
@metivett Yes, it's the reason of the issue. I have done a fix. I will push that soon.

**Comment by prudhomm** [comment]
This was a cleanup. I didn't catch the problem unfortunately in the test suite. We should definitely make sure to test that in the future. Moreover we should run some small applications toolbox like in quickstart that would allow to detect this automatically

**Comment by prudhomm** [comment]
Actually there was also a change of interface to support static condensation data structure based on block matrix and vector

**Comment by metivett** [comment]
Maybe also the ```Vector```-like hierarchy should be refactored somehow to make casts and usage clearer (for example, having the names `BlocksVector`, `VectorBlock` and their bases seems confusing). And having the same base (`Vector`) for `VectorBlock` and `VectorPetsc` makes detecting such problems harder. Maybe we should have different base classes, for e.g. `AlgebraicVector`s (like `VectorBlock`) and `NumericalVector`s (like `VectorPetsc`), what do you think ?

**Comment by prudhomm** [comment]
I agree that the current design needs some refactoring and cleaning. There are already some nice features but we do have a few dark nasty corners
