### ISSUE TITLE
Crash for hdg elasticity test case

### ISSUE THREAD

**Issue by lsala** [feelpp/feelpp#1039]
To reproduce the crash:

`./feelpp_benchmarks_hdg_linear_elasticity_2D_P1 -- --config-file hdg_me/hdg_elasticity.cfg`

**Comment by lsala** [comment]
The terms responsible for the crash are:
`a( 0_c, 0_c ) +=  integrate(_range=elements(mesh),_expr=(c1*inner(idt(sigma),id(v))) );`
`a( 0_c, 0_c ) += integrate(_range=elements(mesh),_expr=(c2*trace(idt(sigma))*trace(id(v))) );`
`a( 0_c, 2_c) += integrate(_range=internalfaces(mesh), _expr=-(trans(idt(uhat))*leftface(id(v)*N())+trans(idt(uhat))*rightface(id(v)*N())) );`
`a( 0_c, 2_c) += integrate(_range=boundaryfaces(mesh), _expr=-trans(idt(uhat))*(id(v)*N()));`
` a( 2_c, 0_c) += integrate(_range=internalfaces(mesh), _expr=( trans(id(m))*(leftfacet(idt(sigma)*N())+rightfacet(idt(sigma)*N())) ) ); `

**Comment by lsala** [comment]
@prudhomm I tried to run the class MixedElasticity in 2D and it also crashes with the same error as in this case. 
After a few tests the first crash happens here:
```
     bbf( 0_c, 2_c) += integrate(_quad=_Q<expr_order>(),_range=internalfaces(M_mesh),
                                 _expr=-( trans(idt(uhat))*leftface(id(v)*N())+
                                         trans(idt(uhat))*rightface(id(v)*N())) );
```

To test it and see the difference you can run:
- `./feelpp_toolbox_mixed-elasticity-model_2DP1_G1 --config-file testHdgElasticity/testElasticity-2D.cfg`
- `./feelpp_toolbox_mixed-elasticity-model_3DP1_G1 --config-file testHdgElasticity/testElasticity.cfg`

The first one in 2D crashes, while the second one in 3D is ok

**Comment by prudhomm** [comment]
is this failing in the develop branch or sc-geomap ? I would guess sc-geomap

**Comment by lsala** [comment]
I recompiled everything with the latest versions both in `develop` and in `sc-geomap` running the two testcases (2d and 3d respectively):
- `./feelpp_toolbox_mixed-elasticity-model_2DP1_G1 --config-file testHdgElasticity/testElasticity-2D.cfg`
- `./feelpp_toolbox_mixed-elasticity-model_3DP1_G1 --config-file testHdgElasticity/testElasticity.cfg`

Both cases in both repositories are working nicely giving the expected results.

In this case I close this issue.
