### ISSUE TITLE
singularity build fails

### ISSUE THREAD

**Issue by prudhomm** [feelpp/feelpp#1044]
https://buildkite.com/feelpp/feelpp-singularity/builds/97#5a749221-7d6a-4d13-89e9-b82f4fb6a908

**Comment by gdolle** [comment]
It's a ssh deploy key write access problem with the lfs server. I'm on it with @boileaum

**Comment by gdolle** [comment]
Will see to deploy a ftp server. Also we can try/test singularity hub following #1080
