### ISSUE TITLE
Add ModelOutputs class to give the outputs of a CRB model in json file

### ISSUE THREAD

**Issue by romainhild** [feelpp/feelpp#1051]
If we want to have CRB models as independant as possible of the geometry, we should give the outputs to compute in a json file, each type of output would have a list of marker on which to compute it.
The syntax would be something like:
```json
"Outputs":
{
  "intensity":
  {
    "marker1":2,
    "marker2":3
  },
  "avg_temp":
  {
    "omega":3
  }
}
```
where the number is the dimension of the marker.

If anyone can think of something else an output can depend on, please tell me.

**Comment by prudhomm** [comment]
`intensity` of what ? you have to pass a field 
I think you should have a subsection on the marker 
```
  "marker1":
   {
      "topodim": 3,
      "field(s)": [""] // field or fields to be used by the output 
      "... // may be more in the future depending on the output
   } 
```

I think that outputs could be defined in a "generic" way for some and "specific" way depending on the toolbox being used. 
For example `mean` is generic. `flux` too. we _just_ need to know the field and the marker. but toolboxes may also have specific output such as `tresca` or `vonmises` for elasticity

@romainhild @vincentchabannes what do you think ?

a remark: Ensight has a CAlculator. It would be interesting to look at their outputs and their configuration. It might give us some ideas

**Comment by prudhomm** [comment]
An Output maps to a mathematical object which is then available through the toolboxes. 
We have generic scalar outputs (eg `min` `max` `mean` `flux` ...) that can be shared between toolboxes and specific outputs to one or several toolboxes

**Comment by prudhomm** [comment]
My comments apply to both fem and crb

**Comment by romainhild** [comment]
A possible interface for the json would be:
```json
Outputs:
{
  "myoutput":
  {
    "type":"min_value",
    "field":"potential",
    "range":"omega",
    "topodim":3
  },
  "output1":
  {
    "expr":"-sigma*grad(potential)*trans(grad(potential))",
    "field":"potential",
    "range":["surface1","surface2"],
    "topodim":2
  }
}
```
And we would have a base class `ModelOutput` which would do the computation in the case where we give it an expression. And several subclasses, for each type of output (average value, min value, max value, flux,...)
```c++
class ModelOutput
{
  std::string M_type, M_expr;
  std::vector<std::string> M_markers, M_fields;
  int M_topodim;

  template<typename T>
  virtual vector_ptrtype apply( T functionSpace)
  {
    auto range = markedfaces(functionSpace->mesh(), M_markers);
    auto f = form1(functionSpace);
    f = integrate(range, expr(M_expr) );
    return f.vectorPtr();
  }
};
```

What do you think ?
