### ISSUE TITLE
Allow to have multiple physics by material

### ISSUE THREAD

**Issue by romainhild** [feelpp/feelpp#1052]
It would be useful to be able to do:
```json
"cond":
{
  "name":"copper",
  "physics": ["thermo","electro","maxwell","elasticity"]
},
"box":
{
  "name":"air",
  "physics":["maxwell"]
}
```

**Comment by prudhomm** [comment]
@romainhild @vincentchabannes is there a test somewhere in the testsuite ? I didn't see any after a quick look. please add it if it is not the case

**Comment by vincentchabannes** [comment]
@romainhild has updated a test in testsuite

**Comment by prudhomm** [comment]
ok would you have a link ? how about the documentation ? I think this kind of stuff should be documented too no ?

**Comment by romainhild** [comment]
https://github.com/feelpp/feelpp/blob/develop/testsuite/feelmodels/test_modelproperties.cpp

**Comment by prudhomm** [comment]
We need to have checks here @vincentchabannes. I forgot that I didn't do it initially. Reading and filling the `property_tree` is one thing, have the proper values in is another. see #1054
