### ISSUE TITLE
ModelCrbBase does not have any output method

### ISSUE THREAD

**Issue by romainhild** [feelpp/feelpp#1062]
In crbmodel, the function output calls the method output of its model, a subclass of ModelCrbBase:
https://github.com/feelpp/feelpp/blob/dda4fe038e06152e32206e742e7a2853956e5942/feel/feelcrb/crbmodel.hpp#L2694-L2697

But ModelCrbBase does not have any output method. It should be virtual, either pure or not.
A default version could be: 
```c++
    double output=0;
    if ( output_index < Nl() )
    {
        for ( int q = 0; q < Ql(output_index); q++ )
        {
            for ( int m = 0; m < mMaxF(output_index, q); ++m )
            {
                element_ptrtype eltF( new element_type( Xh ) );
                *eltF = *M_Fqm[output_index][q][m];
                output += M_betaFqm[output_index][q][m]*dot( *eltF, u );
            }
        }
    }
    else
        throw std::logic_error( "error with output_index" );
    return output;
```
@prudhomm @vincentchabannes @jbwahl what do you think ? Does it make sense to add this default version ?

Edit: In fact, `Nl()`, `Ql(int)` and `mMaxF(int, int)` are functions of `crbmodel` and not `ModelCrbBase`...  It wouldn't work like that, but we could use the sizes of `M_betaFqm` instead.

**Comment by romainhild** [comment]
In the same way, `setupSpecificityModel` is a virtual function which does nothing by default. But it should at least resize the vector for the coefficients, right ?
So in the same way than `initModel`, I think it should be pure virtual. What do you think ?

**Comment by vincentchabannes** [comment]
@romainhild about the output method,  maybe we can add the pure virtual function, I am not sure that a good idea to have a default method. Moreover, your default version doesn't take into account all case, you have also the operators-free strategy (matrix/rhs are not stored) which need to be supported.
For ```setupSpecificityModel```,  it's only a user function, so do nothing by default.  The coefficient resizing should be done in the setup of ModelCrbBase, but doing this require to check all cases. There are some particularities with eim and ser.

**Comment by romainhild** [comment]
ok it was just an idea, but indeed maybe not a good one 😄 
Still I think it should be pure virtual, so that the compilation fails with a clear message if it is not implemented.
For `setupSpecificityModel`, I agree that it is dependent of the model, but the goal of this method is the same one as `initModel` right? So it should have the same behavior, pure virtual and each model should implement it.

It would also be clearer when you develop a model, which methods need to be implemented in order for it to work, including with the plugin. For now, I think it is a mess which methods need to be implemented, between linear/non-linear, steady/non-steady, eim or not...

**Comment by vincentchabannes** [comment]
setupSpecificityModel is not always  necessary. In linear/affine case , generally we need'nt. In the future, I would like also to have eim automatically reloaded. This function has been done  for reload some extra properties of the model.

**Comment by romainhild** [comment]
But even in linear case, we need to allocate the vectors for the beta coefficients no?

**Comment by vincentchabannes** [comment]
I am agree. We can resize these vectors automatically. I will look this.
