### ISSUE TITLE
Merge hifimagnet toolboxes

### ISSUE THREAD

**Issue by romainhild** [feelpp/feelpp#1064]
We need to have all the toolboxes in the same place to be able to:
- merge the non-linear part of the thermoelectric toolbox of hifimagnet into the one of feelpp
- update the magnetostatic toolbox of hifimagnet to match the other toolboxes of feelpp

**Comment by prudhomm** [comment]
Indeed we close the issue.

**Comment by Trophime** [comment]
:+1:
