### ISSUE TITLE
FTBS CRB: biosavart not compiling/linking

### ISSUE THREAD

**Issue by prudhomm** [feelpp/feelpp#1066]
<img width="849" alt="screenshot 2017-10-04 07 45 18" src="https://user-images.githubusercontent.com/151693/31161567-2acc9ea0-a8d8-11e7-944d-30d83b26ea71.png">

**Comment by prudhomm** [comment]
No problem. I would like just a clean build before merging the PR

**Comment by prudhomm** [comment]
Should it still be open?

**Comment by prudhomm** [comment]
@romainhild Should it still be open?

**Comment by romainhild** [comment]
No this is outdated, the application does not exist anymore.
