### ISSUE TITLE
Change existing code to deal with function space on range

### ISSUE THREAD

**Issue by romainhild** [feelpp/feelpp#1074]
Existing code might use
```c++
auto mesh = Xh->mesh();
auto u = Xh->element();
integrate( elements(mesh), inner(id(u),idt(u)) );
```
Notably in the class CRBModel:
https://github.com/feelpp/feelpp/blob/015df1e88289b02dd5a6ba01507c24a90760408d/feel/feelcrb/crbmodel.hpp#L3107-L3110

The problem is that if you define your function space on a range: 
```c++
auto Xh = space_type::New(_mesh=mesh, _range=range);
```
 then the elements of the mesh are not all in the definition domain of your functions.

The fix for CRBModel would be to add the `meshSupport` of the space as a member of the class.
If the space has been created on a range, share the pointer, if not, create the `meshSupport` for all elements of the mesh.

**Comment by prudhomm** [comment]
how about the interface for `CRBModel` ? what do you propose ?

**Comment by romainhild** [comment]
In fact, `Xh` is not a member of `CRBModel`, each time, we retrieve the function space by `M_model->functionSpace()` or by `u.functionSpace()` where `u` is an element given as parameter.
So we'll need to change every function that uses that, either to call `M_model->meshSupport()` or create one with `u.functionSpace()->mesh()`.

Maybe the simpler would be to change the `meshSupport()` function from `doftable.hpp` so that either it returns the one already created, or it builds one on the entire mesh and returns it.

What do you think @prudhomm @vincentchabannes ?

Also, we would need to add `meshSupport` as a member of `modelcrbbase.hpp` and set it in `setFunctionSpace`.
