### ISSUE TITLE
Update container script for singularity version 2.4

### ISSUE THREAD

**Issue by gdolle** [feelpp/feelpp#1080]
- [ ] Update tools script to handle new version. 
- [ ] Update singularity install on CI machine.

See related issues https://github.com/feelpp/docker/issues/6 and #1044

**Comment by gdolle** [comment]
@prudhomm Regarding https://github.com/feelpp/feelpp/commit/790a95a5dfdf33c562a8905ac091fcb2d92e5594
It might be interesting to have a look at buildkite concurrency to avoid blocking queue for some jobs (https://buildkite.com/docs/builds/controlling-concurrency) on a same agent.

For example, a feel++ build is blocking the book pipeline and could be done in asynchronously.

**Comment by prudhomm** [comment]
Should it be still open?

**Comment by gdolle** [comment]
Done!
