### ISSUE TITLE
Question on CRB

### ISSUE THREAD

**Issue by romainhild** [feelpp/feelpp#1101]
In the `lb` function of CRB, there are some issues:
- Here `time_for_output` is redefined in the condition.
https://github.com/feelpp/feelpp/blob/7811d6352e1e1bc7b9319640a7c265fe6c2f7b16/feel/feelcrb/crb.hpp#L5774-L5787
- Here we compute the output using `M_variance_matrix_phi` for the space 0. Could somebody explain me what is in this matrix and why we need to use it ? Shouldn't the output be computed by `l(u_{rb},\mu)- r_{pr}(\phi_{rb},\mu)` where `l` is the linear form of the output, `u_{rb}` the primal solution, `\phi_{rb}` the dual solution, and `r_{pr}` the primal residual.
https://github.com/feelpp/feelpp/blob/7811d6352e1e1bc7b9319640a7c265fe6c2f7b16/feel/feelcrb/crb.hpp#L5789-L5816

**Comment by jbwahl** [comment]
The first one looks a like a mistake.

For the second point : according to the option description : 
```
( "crb.compute-variance" , Feel::po::value<bool>()->default_value( 0 ), " if true the output is the variance and not l(v)" )
```
If this option is set to `true`, you just ignore your output and compute instead the variance of the solution vector. I don't know what is the point of such evaluation but i guess @prudhomm can enlighten us.

**Comment by romainhild** [comment]
ok indeed, it is a bit confusing...
The real computation of the output is done in `fixedPointPrimal` and `correctionTerms`.

Still I wonder if this piece of code works, it seems that it always uses the first space, in case of composite space it could be a problem...
