### ISSUE TITLE
Update log directory

### ISSUE THREAD

**Issue by gdolle** [feelpp/feelpp#1104]
I had a problem with containers and `feelpp_mesh_partionner` regarding logs.
As the partionner has no app names, it saves log in current directory ./logs, but that can be a problem regarding immutable containers (read access).

We should update this directory to be the working directory. Or maybe add a FEELPP_LOGDIR in the case there's no appname.

**Comment by prudhomm** [comment]
I would suggest for now to disable logging `--disable_log=true` or `--log_level=0`

**Comment by vincentchabannes** [comment]
@gdolle the mesh partitioner has a app name, juste I force the directory to be the current directory in the environment constructor. I do this for have a relative path of the outputs with respect to this current dir, which  is convenient.

Why you doesn't move in a dir where your container can write? (and so run the mesh_partitioner here)

**Comment by prudhomm** [comment]
or disable logging ;)

**Comment by vincentchabannes** [comment]
@prudhomm the options that you mention works?  If I remember, it's ```--no_log 2``` but the directory logs/exports/expr are always built

**Comment by prudhomm** [comment]
They should. They aren't?
