### ISSUE TITLE
Feelpp lib install (make install-feelpp-lib) fails

### ISSUE THREAD

**Issue by metivett** [feelpp/feelpp#1117]
Command `make install-feelpp-lib` fails with error 
```
CMake Error at contrib/ginac/ginsh/cmake_install.cmake:39 (file):
  file INSTALL cannot find
  "/Users/tmetivet/Workspace/Feelpp/feelpp.build/contrib/ginac/ginsh/ginsh".
Call Stack (most recent call first):
  contrib/ginac/cmake_install.cmake:34 (include)
```

This error can be manually bypassed by running `make ginsh`, but the subsequent installation of Feel seems to give an incomplete set of modules. 

When using the installed libraries with
```
find_package( Feel++ PATHS [feel_install_dir]/share/feelpp/feel/cmake/modules )
```
one gets `cmake` errors
```
CMake Error at [feel_install_dir]/share/feelpp/feel/cmake/modules/Feel++Config.cmake:157 (include):
  include could not find load file:

    [feel_install_dir]/share/feelpp/feel/cmake/modules/feelpp-contrib-export-targets.cmake
Call Stack (most recent call first):
  CMakeLists.txt:3 (find_package)


CMake Error at [feel_install_dir]/share/feelpp/feel/cmake/modules/Feel++Config.cmake:158 (include):
  include could not find load file:

    [feel_install_dir]/share/feelpp/feel/cmake/modules/feelpp-export-targets.cmake
Call Stack (most recent call first):
  CMakeLists.txt:3 (find_package)


CMake Error at [feel_install_dir]/share/feelpp/feel/cmake/modules/Feel++Config.cmake:161 (get_property):
  get_property could not find TARGET feelpp.  Perhaps it has not yet been
  created.
Call Stack (most recent call first):
  CMakeLists.txt:3 (find_package)
```

This might be related to commit 663abcdf13dd1b334edccbdc50e965602cc69b47 ?

**Comment by prudhomm** [comment]
This is indeed deprecated and should not be used anymore.
We need to check the manual and see if it is still there

Actually I think we should change the directory layout a bit to have it more self contained

**Comment by a-bonnet** [comment]
Hi, what is the recommended way to install the libraries when developing new features in Feel++ since we can't use the install-feelpp-lib target? Should we manually move the new headers/shared objects to the installation folder or is there a more automated way?

**Comment by clemenskuehn** [comment]
`install-feelpp-lib` is mentioned at least in the output of the configure script

**Comment by gdolle** [comment]
@clemenskuehn true, we should check the cmake message if it's still up to date.
@vincentchabannes is working on it.

**Comment by prudhomm** [comment]
`install-feelpp-lib` is deprecated in the forthcoming commit associated to this issue. 
Simple directives are now proposed at the end of `configure` or `cmake` process.
