### ISSUE TITLE
Add test for FMU model

### ISSUE THREAD

**Issue by jbwahl** [feelpp/feelpp#1118]
We need a small application to verify if an FMU model is well compiled and executed in Feel++.

/cc @lsala

**Comment by prudhomm** [comment]
could you elaborate on the test? bouncing ball ?

**Comment by jbwahl** [comment]
@prudhomm we have this test now in the testsuite with the bouncing ball. We can close this issue

**Comment by prudhomm** [comment]
in `testsuite/`

**Comment by prudhomm** [comment]
shouldn't we test also `feelpp_fmi_fmu`  in #1119 ?

**Comment by jbwahl** [comment]
in `testsuite/feelfmi` is a simple test which verifies the cmake detection, compilation of the FMU, loading the FMU and executing it.
This issue was about adding a test to verify that FeelFMI framework is ok. And I think this test does the job. 
In my opinion, we can close this issue and then focus on #1119 which is adding a new tool application. What do you think?
