### ISSUE TITLE
Add feelpp_fmi_runfmu

### ISSUE THREAD

**Issue by prudhomm** [feelpp/feelpp#1119]
I propose the implementation of an application `feelpp_fmi_fmu` (merge `feelpp_fmi_readfmu` and `feelpp_fmi_runfmu`

- [X]  read an fmu and display information 
- [ ] run an fmu  taking a `.csv` file and an FMU model as inputs. The FMU model is loaded and executed in Feel and then the variables values are compared with the values in the .csv file.

**Comment by prudhomm** [comment]
@jbwahl we should merge the two apps and I will discuss with @vincentchabannes  about some changes in the directory hierarchy this week hopefully

**Comment by jbwahl** [comment]
workin on it
