### ISSUE TITLE
CRB load the database in the constructor

### ISSUE THREAD

**Issue by romainhild** [feelpp/feelpp#1120]
It is problematic in the case of derived classes from CRB, such as CRBSaddlePoint.
Indeed, in CRBSaddlePoint, there is additionnal members to save in the database. When loading the database in the constructor of CRB, the CRBSaddlePoint object is not yet initialized and so it calls the `loadDB` method of CRB, not the one of CRBSaddlePoint.
See [here](https://isocpp.org/wiki/faq/strange-inheritance#calling-virtuals-from-ctors) for explanations and some possible alternatives.

One way to do it is to create a factory method:
- create an init method that would call `setupOfflineFromDB()` if needed. 
- this function would be called in a static method such as `New`.
- the constructors visibility would be set to `protected` to prevent creating a CRB object without calling `init`

What do you think @vincentchabannes @jbwahl ?

**Comment by jbwahl** [comment]
There was, at some point, an `init()` function that I added to avoid this issue. But actually, it was removed (placed after a `#if 0`)... and I don't remember why...
@vincentchabannes may have an explication? 
Anyway, I am ok with the solution you proposed
