### ISSUE TITLE
Support input and output data files  via Girder

### ISSUE THREAD

**Issue by prudhomm** [feelpp/feelpp#1121]
With MSO4SC or cloud computing, we will have often the case where the data is not available locally but remotely. In order to facilitate the use of remote data, we should be able to provide ways to 
 - retrieve test cases directories by url
 - retrieve test cases archives by url

Using CKAN and/or Girder we have ways to say where our data is, we should also think about simplifying url thanks to these metadata which will provide the true location.

this is linked to #1116

We should also be able to upload output data to Girder once simulation are done

**Comment by vincentchabannes** [comment]
@prudhommit's not finished. Currently, from girder, we can download several files, but not folder or item. It require to use unzip tool.

**Comment by romainhild** [comment]
Maybe it would be useful to check for errors, for example for Github, if the path is wrong or trying to access to a private repo with the wrong token, the following json is returned:
```json
{
"message": "Not Found",
"documentation_url": "https://developer.github.com/v3/repos/contents/#get-contents"
}
```
Currently, an obscur message about yamllint and jsonlint is displayed.
We could have something like the following at this [point](https://github.com/feelpp/feelpp/blob/a145810d8eb0ef060804c5f4efa34b39e7dbbd5c/feel/feelcore/remotedata.cpp#L386):
```c++
if( auto message = ptree.get_optional<std::string>("message") )
  CHECK( message != "Not Found" ) << "url is not valid or you don't have privileges to access the repo\nplease check this link http://docs.feelpp.org/toolboxes/0.105/what-is-a-toolbox/#_run_an_application";
```

what do you think @prudhomm @vincentchabannes ?

ps: I didn't find the corresponding issue for Github.

**Comment by prudhomm** [comment]
Sure the obscur message  shows issues in json parsing and arrives at the very end if something went wrong, it can definitely be improved. errors can occur in `json` for the toolbox, in `json` for the download. providing in context errors is very good. however no `CHECK`!  I want to have clean exception thrown and handled later in the code so that everything is shut down properly.

**Comment by vincentchabannes** [comment]
@romainhild it's not always possible to do that, only one process have this information. Each process must send to the Environment an exception type and exit properly the program.

**Comment by prudhomm** [comment]
depends on the gravity of the exception. in this case that might do it, however we don't want to do it here but rather at a central place for error handling

**Comment by prudhomm** [comment]
@vincentchabannes should it be closed? upload and download are now available and documented right ?
