### ISSUE TITLE
FMU export and XML file associated the model

### ISSUE THREAD

**Issue by prudhomm** [feelpp/feelpp#1132]
it seems that the FMU uses the XML file associated with the model from OpenModelica.
I had a look at the code here
https://trac.openmodelica.org/OpenModelica/browser/trunk/SimulationRuntime/fmi/export/fmi2/fmu2_model_interface.c#L329

It seems quite clear that the FMUData is set-up with the XML from the model. If I understand correctly the XML file allows configuring the solver used and its configuration. We should check if we could indeed configure the solver from there.

Also, note that the latest changes are from 3-4 years ago in FMI2. 

/cc @lsala @mszopos

**Comment by jbwahl** [comment]
Indeed, the XML file is used to configure the simulation. However, we don't have any XML file before the export from OpenModelica to FMU. 
OpenModelica builds the FMU archive from the `.mo` files (and only these files). In this archive are: binary files, c-sources, and an automatically-generated XML file.

**Comment by lsala** [comment]
@jbwahl haven't we try also to change the value within the automatically-generated XML file with no difference between two different simulations?

**Comment by jbwahl** [comment]
We tried to unzip the archive, edit the XML and then rebuild the archive. It was probably not the good way to do it and it did not work anyway
