### ISSUE TITLE
add support for PETSc 3.9

### ISSUE THREAD

**Issue by prudhomm** [feelpp/feelpp#1139]
PETSc 3.9 is out.

**Comment by Trophime** [comment]
@prudhomm watch out slepc 3.8.3 does not compile with petsc 3.8.4:
```
No rule to make target chk_makej...
````
Issue has also been reported on [slep mailing list](chttps://lists.mcs.anl.gov/pipermail/petsc-users/2018-March/034667.html)

**Comment by vincentchabannes** [comment]
I reopen the issue, see #1166
