### ISSUE TITLE
GCC 6 7 & 8 fail to build Feel++ Toolboxes

### ISSUE THREAD

**Issue by prudhomm** [feelpp/feelpp#1152]
GCC 6&7 compile and run properly the feel++ library and base. However, it fails in the toolboxes. This needs investigations and be corrected for the next release.

see the buildkite logs 
 - https://buildkite.com/feelpp/feelpp-gcc6
 - https://buildkite.com/feelpp/feelpp-gcc7

I already excluded the hdg toolbox from the target `all` but it is not enough, there is breakage in other places

- [ ] GCC6
- [ ] GCC7
- [x] GCC8

**Comment by vincentchabannes** [comment]
@prudhomm I added the cmake option  -DFEELPP_TOOLBOXES_ENABLE_HDG=OFF, and all compile in the toolboxes directory with gcc6.4 on atlas. Without the cmake option, there are compilations errors with hdg applications.

**Comment by prudhomm** [comment]
do you do that for GCC only ?

**Comment by vincentchabannes** [comment]
yes, no problem with clang

**Comment by prudhomm** [comment]
did you commit ?
we should have a 0.104.1 then to add this fix for GCC

**Comment by vincentchabannes** [comment]
why commit? it's a cmake option

**Comment by prudhomm** [comment]
I restarted
 - https://buildkite.com/feelpp/feelpp-gcc6/builds/11
 - https://buildkite.com/feelpp/feelpp-gcc7/builds/7

**Comment by prudhomm** [comment]
@vincentchabannes @Trophime I can report that the toolboxes compile fine with GCC8
We need to check with 6 & 7 now and check the boxes above

**Comment by prudhomm** [comment]
gcc-6 support has been discarded, g++-8 support has been added and the compiler has been added to docker
