### ISSUE TITLE
Support norm computation in toolbox post processing

### ISSUE THREAD

**Issue by vincentchabannes** [feelpp/feelpp#1172]
It could be useful to compute easily the norm (L2/H1/Semi-H1) of a field or an error.
An example of json which define 2 norm computations. The results are stored in csv file in column named `Norm_mynorm_L2` and `Norm_myerror_L2-error`
```
"PostProcess":
{
    "Measures":
    {
        "Norm":
        {
            "mynorm":
            {
                "type":"L2",
                "field":"velocity",
                "markers":"omega"
            },
            "myerror":
            {
                "type":"L2-error",
                "solution":"{2*x,cos(y)}:x:y",
                "field":"velocity",
                "markers":"omega",
                "quad":12
            }
        }
    }
}
```

Several norms can be computed by listing it in the type section : 
```
"type":["L2-error","H1-error","SemiH1-error"],
"solution":"{2*x,cos(y)}:x:y",
"grad_solution":"{2,0,0,-sin(y)}:x:y",
```

An expression (scalar/vector/matrix) can be also passed to evaluate the norm. But in this case, the `field` entry must be removed.
```
"expr":"2*x*y:x:y"
```
In the case of  H1 or SemiH1 norm type, the grad_expr entry must be given.
```
"grad_expr":"{2*y,2*x}:x:y"
```

All solution/expression can be depends of specic symbol of the toolboxes used. For example, in the heat toolboxes : 
```
"expr":"2*heat_T+3*x:heat_T:x"
```
where `heat_T` is the  temperature solution computed at last solve.

The quadrature can be also given if an expression/solution is used. By default, the quadrature order is 5. For example,  use a quadrature order equal to 10 is done by adding :
```
"quad":10
```

**Comment by romainhild** [comment]
maybe it could be useful also to export the size of the mesh in the csv, or the number of dofs.
For convergence tests for example.
Also the ability to not overwrite a previous file.

**Comment by vincentchabannes** [comment]
@romainhild it's already exported in the .info. It's a text format used, but it's not really good, it should be replaced soon by a json file. 
Also, these information are not adapted to the csv file, which exports at each time the measures

**Comment by prudhomm** [comment]
@vincentchabannes and how about outputs from linear forms, our more complex outputs

**Comment by PhilippeRicka** [comment]
@vincentchabannes Is this implemented yet ? I could not manage to make this work.
