### ISSUE TITLE
Add MSO4SC blueprints for Feel++ toolboxes

### ISSUE THREAD

**Issue by prudhomm** [feelpp/feelpp#1176]
We should move the mso4sc blueprints in Feel++ to enable versioning the blueprint with Feel++

**Comment by prudhomm** [comment]
I have mixed feelings now about that. I am not sure anymore that it should go in feelpp.
I would now rather have the mso4sc/cloudify blueprints in their repository with buildkite setup so that automatically :
 - ci can check the yaml systematically
 - ci can rebuild the tarballs
 - ci could reupload the tarballs if deployment is ever going to be supported.

The builds would be triggered by successful builds of feelpp and feelpp-singulariry pipelines and would generate the proper versions based on version information (and whatever other data) passed through the builds from feelp

**Comment by prudhomm** [comment]
Actually we should add an application eg feelpp_version inside docker and hence singularity that gives back the version of feelpp. That way even if the version is not encoded into the image name, we have the proper version.
Of course any feelpp app would give that info but it is cleaner to have a dedicated app.

**Comment by prudhomm** [comment]
This is linked to mso4sc/cloudify-hpc-plugin#68

**Comment by prudhomm** [comment]
This needs now a different strategy.

**Comment by prudhomm** [comment]
@jbwahl @vincentchabannes currently the blueprints are in MSO4SC/resources. But this is not very convenient. As stated above we may have several versions of the blueprint depending on the version of the application and would like to setup CI/CD/CD (Continuous Integration, Continuous Delivery, and Continuous deployment) four our online application. As such we need to extract our blueprint and deal with them in a single feelpp repository where we support versioning as well as CI/CD/CD.

**Comment by jbwahl** [comment]
ok, I wait for you to create the repo and I will move the blueprints

**Comment by prudhomm** [comment]
The toolbox recipes are in a separate repo https://github.com/feelpp/cloudify-toolboxes
