### ISSUE TITLE
CFD and CSM apps broken on MSO4SC

### ISSUE THREAD

**Issue by prudhomm** [feelpp/feelpp#1177]
Currently, CFD and CSM are failing at execution stage on MSO4SC

![Screenshot 2018-06-07 23.03.48.png](https://images.zenhubusercontent.com/5926dc9a51aa2c30577f70e0/91fc883c-9f27-474b-a7e8-efdd96f786ca)

![Screenshot 2018-06-07 22.10.21.png](https://images.zenhubusercontent.com/5926dc9a51aa2c30577f70e0/32665f67-84ad-4ae4-8b5e-51ba3c91a2cf)

**Comment by prudhomm** [comment]
I just have two scripts in these directories, nothing else

**Comment by prudhomm** [comment]
here is a screenshot

<img width="683" alt="screenshot 2018-06-07 23 32 18" src="https://user-images.githubusercontent.com/151693/41127395-143eee6e-6aab-11e8-8ad2-00021e01a36a.png">

**Comment by gdolle** [comment]
Did you do the "Deploy instance" step ? It seems to me your forgot no ?

**Comment by prudhomm** [comment]
nope I haven't forgotten and it was green

**Comment by gdolle** [comment]
In my case CSM works 
![image](https://user-images.githubusercontent.com/2409477/41127648-e494c2a0-6aab-11e8-9e0d-d49e4f257df3.png)
![image](https://user-images.githubusercontent.com/2409477/41127742-3119ec72-6aac-11e8-9910-a4b659432475.png)

**Comment by prudhomm** [comment]
here is the deploy stage
<img width="702" alt="screenshot 2018-06-07 23 41 32" src="https://user-images.githubusercontent.com/151693/41127822-66a1650a-6aac-11e8-8add-52ee361762fb.png">

and the run stage
<img width="656" alt="screenshot 2018-06-07 23 42 29" src="https://user-images.githubusercontent.com/151693/41127844-76f92fd2-6aac-11e8-84ca-d37b80de28dd.png">

**Comment by gdolle** [comment]
Currently I try the CSM and at least the job should at least run the job.... I'll retry with the CFD one

**Comment by prudhomm** [comment]
idem with CSM (deploy is ok)

<img width="680" alt="screenshot 2018-06-07 23 58 01" src="https://user-images.githubusercontent.com/151693/41128486-aa09efae-6aae-11e8-83d6-a391312906b8.png">

**Comment by prudhomm** [comment]
undeploy and destroy instance worked fine

**Comment by gdolle** [comment]
It seems your job run and then failed. You should have the *.out *.err file in lustre aside to the scripts.

**Comment by gdolle** [comment]
But I'm quite sure this error is due to a corrupted download. I'll add a check to the deployment step to verify the singularity image.

**Comment by gdolle** [comment]
I updated the image. Now if the singularity image is not properly downloaded, the deployment step should crash.

**Comment by prudhomm** [comment]
@gdolle when the app is run I get immediately (the very first message) at the top of the log file
```
2018-06-08T04:11:14.181Z State changed to FAILED job_toolboxes_u4cvk9 (job_toolboxes)
```

**Comment by prudhomm** [comment]
@gdolle should I do something about the app ? should I rebuy it?

**Comment by prudhomm** [comment]
@gdolle I recreated an instance but deployment went fine however run fails

**Comment by prudhomm** [comment]
Ok we need to add case.config-file cfd1.cfg

**Comment by prudhomm** [comment]
@gdolle I think we need to change the default `case ` for CFD and use lid-driven-cavity

**Comment by prudhomm** [comment]
The issue is in fact due to https://github.com/MSO4SC/MSOOrchestrator/issues/2 so I close the issue
