### ISSUE TITLE
FTBS Debian/stretch boost version?

### ISSUE THREAD

**Issue by Trophime** [feelpp/feelpp#1182]
with 0.105.0rc1 on debian/stretch:
```
/build/feel++-0.104.0-beta.3+20180613.git0f8fe5496/feel/feelcore/environment.cpp:1279:39: error: no member named 'filename_is_dot' in 'boost::filesystem::path'
            if ( fscaseDir.filename().filename_is_dot() )
                 ~~~~~~~~~~~~~~~~~~~~ ^
```
which version of boost do you use?

**Comment by prudhomm** [comment]
Which boost version in stretch? Up to 1.65 should be fine. After we have issues

**Comment by prudhomm** [comment]
No time to solve them currently

**Comment by vincentchabannes** [comment]
feel++ support boost version from 1.61 up to 1.66

**Comment by vincentchabannes** [comment]
@trophine Je viens de vérifier et en effet, la fonction filename_is_dot() apparait seulement à partir de boost >=1.63.
