### ISSUE TITLE
trailing slashes in remote data path make app crash

### ISSUE THREAD

**Issue by prudhomm** [feelpp/feelpp#1183]
trailing slash in remote data make app crash

eg.
```
./feelpp_qs_laplacian_2d --case "github:{path:quickstart/laplacian/triangle/}"
or
./feelpp_qs_laplacian_2d --case "github:{path:quickstart/laplacian/triangle//}"
```
the solution is to remove the slashes.
I suggest to use `remove_trailing_slash()` from `fs::path` twice to cleanup the path and be fool proof

**Comment by vincentchabannes** [comment]
@prudhomm We can generalized that by using : 
```
if ( fs::path( s ).filename().filename_is_dot() )
    s = fs::path(s).parent_path().string()
```
It works for any number of slash.  I will do this update with my next changes, in the next release
