### ISSUE TITLE
[Fluid Toolbox / Sequential / Singularity on Atlas] Lots of threads created

### ISSUE THREAD

**Issue by francoisdh** [feelpp/feelpp#1190]
A lot of threads are created when using the fluid toolbox in sequential using Singularity (tested on atlas node 3):

Using 

`feelpp_feelpp-toolboxes-master-v0.105.0-ubuntu-16.04.simg`,

testing with 

`feelpp_toolbox_fluid --case "github:{repo:toolbox,path:examples/modules/cfd/examples/spring}"`

and monitoring using `htop` shows 48 threads running at 100% eventually. This matches the number of logical cores of the node.

**Comment by francoisdh** [comment]
This is solved by limiting the number of OpenMP threads:

```
export OMP_NUM_THREADS=1
```

**Comment by prudhomm** [comment]
Have you compared the perfs with the native version using the modules from @vincentchabannes ?

**Comment by prudhomm** [comment]
@francoisdh in docker we have this 
```
export OPENBLAS_NUM_THREADS=1
export OPENBLAS_VERBOSE=0
```
could you check what is set in singularity ? We may have to modify singularity environment to fix this issue

**Comment by prudhomm** [comment]
Issue moved to [feelpp/singularity #5](https://github.com/feelpp/singularity/issues/5) via [**ZenHub**](https://www.zenhub.com/)
