### ISSUE TITLE
Fix support of boost 1.61 and 1.62

### ISSUE THREAD

**Issue by vincentchabannes** [feelpp/feelpp#1191]
Two functions of boost filesystem have been used in the library but there are supported in boost 1.61 and 1.62 : 
```
fs::path p("mypath");
p.filename_is_dot();
p.filename_is_dot_dot();
```

For keep the compatibility with these versions, two functions will be added in feel/feelcore/feel.hpp
```
bool  filename_is_dot( fs::path const& p );
bool  filename_is_dot_dot( fs::path const& p );
```
If the version is >= 1.63, we use the boost implementation, else we add the implementation (but not done for WINDOWS_API).

so we can't  use directly `p.filename_is_dot()` but we must use `filename_is_dot( p )`

**Comment by prudhomm** [comment]
@vincentchabannes I will cherry pick to incorporate that in 105. is that relevant for 104?

could you update the CHANGELOG ?

**Comment by vincentchabannes** [comment]
@prudhomm it appears only from the v0.105.

**Comment by vincentchabannes** [comment]
and yes, I will up the CHANGELOG for v0.105.0
