### ISSUE TITLE
CRB apps broken in develop

### ISSUE THREAD

**Issue by romainhild** [feelpp/feelpp#1195]
In develop, crb apps compile but do not run, it gives the following error:
```
terminate called after throwing an instance of 'Feel::FactoryDefaultError<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, Feel::IMBase<double> >::Exception'
  what():  [Factory] Unknown Type : im(3,1,simplex)
```
for example in thermoelectric at this line:https://github.com/feelpp/feelpp/blob/43ed3ca97d06d0b1a30620ab1ffe763cb8d8f08c/applications/crb/thermoelectric/thermoelectric-nonlinear.cpp#L542-L543

It seems to be coming from here: 
```
#7  0x00007ffff61bc15d in Feel::Factory<Feel::IMBase<double>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::function<std::unique_ptr<Feel::IMBase<double>, std::defa
ult_delete<Feel::IMBase<double> > > ()>, Feel::FactoryDefaultError>::createObject(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (this=0x6ba6f60,
    id="im(3,1,simplex)") at /home/u2/hild/Devel/develop/feel/feelcore/factory.hpp:178
#8  0x00007ffff61bb534 in Feel::PointSetQuadrature<Feel::Simplex<(unsigned short)3, (unsigned short)1, (unsigned short)3>, double>::PointSetQuadrature (this=0x7ffffffed268, order=1)
    at /home/u2/hild/Devel/develop/feel/feelpoly/pointsetquadrature.hpp:94
```

@jbwahl
@prudhomm @vincentchabannes do you have any idea what is going on ?

**Comment by prudhomm** [comment]
yes, the quadrature factory failed to provide `im(3,1,simplex)`. `im` stands for integration method. 
somehow the quadrature is not registered or the factory not setup at all.

**Comment by jbwahl** [comment]
I had the same issue with 'heat1d', 'benchmarkgrepl' or 'stokesdeim'. I finally stopped working in 'develop'...

**Comment by romainhild** [comment]
I think the factory is not set up at all:
```(gdb) p M_associations
$4 = std::map with 0 elements```

**Comment by romainhild** [comment]
yes it is at the very beginning of the execution

**Comment by jbwahl** [comment]
For me it was always at the first call of an 'integrate(...)' function

**Comment by prudhomm** [comment]
Ok I understand what is going on. Thanks for reporting.

**Comment by prudhomm** [comment]
It means that there are no crb test to catch this in the testsuite

**Comment by romainhild** [comment]
but why does it happen only to crb apps ?

**Comment by prudhomm** [comment]
probably due to the plugin framework. We have two sets of factory generated but only the first one is allocated on the heap and the second one is allocated but has no products as it was dynamically on the stack. I am working on a fix

**Comment by romainhild** [comment]
@prudhomm any news on this front ?

**Comment by prudhomm** [comment]
yes. It seems that in the crb code at some point heap allocated data (quadratures) gets somehow invalidated or unavailable. I am currently changing this to stack allocated to avoid this kind of issue. This is however not entirely trivial.

**Comment by prudhomm** [comment]
This is however a top priority along with python(mso4sc) and hdg.

**Comment by vincentchabannes** [comment]
@romainhild @jbwahl can you check if it's ok for you now?

**Comment by vincentchabannes** [comment]
I have tested heat3d example with success, also with using the plugin and crb_onlinerun. But my feeling is that something is very low, it wasn't the case when I work on crb several months ago. Maybe a bad impression of me. I will investigate, tell me if you note something like that.

**Comment by romainhild** [comment]
I don't have the error related to the quadrature points anymore, but I have another error that I didn't have before. I'm not sure what is the new problem but it's not related to the quadrature points.

**Comment by vincentchabannes** [comment]
the quadrature error seems fixed, it due to the fact the crb library hide all symbols by default (-fvisibility=hidden is put in the cmake macro crb_add_library).

The case benchmark-grepl-linear run but the results are not good. eim converge very slowly (if I remember, it's done in about 10 iterations). And after the rb build, the output return always one (also for fem output). There is a problem (or an option has changed?).  I launched in sequential and one 8 proc and the time to compute an eim basis is the same (about 20s).

@romainhild what is your error? how we can reproduce it?

**Comment by vincentchabannes** [comment]
I have solved the performance issue with benchmark-grepl-linear in the commit 96074aed6556b562b628c5ed4bb630f7664dd1d1.
However, now I test the benchmark-grepl-nonlinear and it doesn't work...
