### ISSUE TITLE
Refactor/Reorganize directories and update build process

### ISSUE THREAD

**Issue by prudhomm** [feelpp/feelpp#1208]
We need to componentize Feel++ from the build point of view to help with component wise packaging delivery.

component packaging could be done in stage to have faster delivery.

components would be:

* feelpp-contrib
* feelpp-libfeelpp
* feelpp-pyfeelpp
* feelpp-toolboxes
* feelpp-pyfeelpp-toolboxes
* feelpp-mor
* feelpp-pyfeelpp-mor

libfeelpp would deliver:
* libfeelpp
* quickstart
* tools (mesh partitioner, database reader, remotedata,...)

toolboxes would stay the same

mor stands for model order reduction, it would have a similar structure as toolboxes and would deliver:
* applications/crb (which would be moved to `/mor`)

benchmarks,  applications and doc would be probably gathered under then directory and would be cleaned up over time.

build process:
```
# cmake can select which component to build, by default all are built
# build selected components
make
#  install selected components
make install
```

build process and packaging would then reflect the new organization. 
Actually the current build process is not far away from that,  we need to :
* [x] move applications/crb to /mor and and a structure similar to toolboxes.
* [x] split pyfeelpp into pyfeelpp, pyfeelpp-toolboxes, pyfeelpp-mor
* [ ] make feel/ a component of feel++, call it libfeelpp and move tools,quickstart in libfeelpp
* [ ] move benchmarks,applications and doc
* [ ] update buildkite build in stage to reflect the component system

@vincentchabannes @Trophime  what do you think ?

**Comment by prudhomm** [comment]
The current build process is not far away from that, 
we need to 
* [ ] move applications/crb to /mor and and a structure similar to toolboxes.
* [ ] split pyfeelpp into pyfeelpp, pyfeelpp-toolboxes, pyfeelpp-mor
* [ ] move benchmarks,applications and doc
* [ ] update buildkite build in stage to reflect the component system

**Comment by vincentchabannes** [comment]
@prudhomm Yes, it would be nice to have a standard compile/install process.
I think it would be better to deactivate by default the toolbox and the crb (the compilation is really too long)

**Comment by prudhomm** [comment]
I am thinking for a while now about using the trigger +async process for the entire process to avoid having a monolithic system such as the current one (which has also its advantages).
I am also wondering if we could actually trigger specific pipelines from commit logs with buildkite, eg to compile the toolboxes but not mor and vice et versa

**Comment by prudhomm** [comment]
@vincentchabannes I would like to move the mesh partitionner and database reader to tools with remote data. What do you think?
Tools would be delivered with the component pyfeelpp-libfeelpp

**Comment by vincentchabannes** [comment]
yes, it was the idea

**Comment by prudhomm** [comment]
@vincentchabannes to minimize compilation time we could:

1. split feel++ into feelpp, feelpp-toolboxes and feelpp-mor

**Comment by Trophime** [comment]
From my experience, I would also suggest to split feelpp-toolboxes into each physics.
That is provide a package for each physics.
It actually doesn't change the build process but speed up the install and reduce the requested size to the "bare" minimum.

**Comment by prudhomm** [comment]
that would be too many repositories and would not be able to share code. I don't think we want that

**Comment by prudhomm** [comment]
for packaging ok but not for coding

**Comment by prudhomm** [comment]
I now need to deal with libfeelpp. It is a little bit trickier and involved. 
Here is another possible organization:
 - feelpp-contrib
 - feelpp-libfeelpp
    * feelpp-pyfeelpp
 - feelpp-toolboxes
   * feelpp-pyfeelpp-toolboxes
 - feelpp-mor
   * feelpp-pyfeelpp-mor

if we indeed move mor and toolboxes into their own repo (@vincentchabannes what do you think about that? that would solve the compilation time issue and buildkite can help us automate thing) pyfeelpp*  would be associated to their respective component: libfeelpp, toolboxes and mor.

any thoughts about that ?

**Comment by vincentchabannes** [comment]
ok

**Comment by prudhomm** [comment]
this has been merged into develop
