### ISSUE TITLE
Method to perform basic statistics per physical domains

### ISSUE THREAD

**Issue by Trophime** [feelpp/feelpp#1209]
Hi,
It will be great to have a method to perform some basic stats (mean, standard deviation,...) for some quantities like the unknows (eg. the temperature field) for each physical domains.

From an engineering point of view, this infos may be really valuables if displayed easily after each calculation.

**Comment by vincentchabannes** [comment]
@Trophime see [here](http://docs.feelpp.org/toolboxes/0.106/what-is-a-toolbox/#_measures), you have some basic stats computed automatically, you need more?

**Comment by Trophime** [comment]
Ok I've haven't seen that feature. Seems good. Thanks.

**Comment by Trophime** [comment]
is there some keyword to indicate to display stat for each markers?
Something: "markers":"for_each"

**Comment by vincentchabannes** [comment]
* you can write : 
 "markers":"mark1"
 it computes the statistics on marker mark1
* you can also write : 
 "markers":["mark1","mark2","mark3"]
it computes the statistics on union of the markers mark1,marker2,marker3
