### ISSUE TITLE
NLopt fails to configure with cmake 3.12

### ISSUE THREAD

**Issue by romainhild** [feelpp/feelpp#1220]
With cmake 3.9, when nlopt failed to find matlab, it gave just a warning, but in new versions, it is now a fatal error.
Since we do [nothing](https://github.com/feelpp/nlopt/blob/54cdb326e591dd68e8055ee6f0a9530f76b9ad86/CMakeLists.txt#L302-L304) with octave and matlab:
```
if (OCTAVE_FOUND OR Matlab_FOUND)
#  add_subdirectory (octave)
endif ()
```
we could set the [options](https://github.com/feelpp/nlopt/blob/54cdb326e591dd68e8055ee6f0a9530f76b9ad86/CMakeLists.txt#L28-L29) `BUILD_OCTAVE` and `BUILD_MATLAB` to `OFF` by default:
```
option (BUILD_OCTAVE "build octave bindings" OFF)
option (BUILD_MATLAB "build matlab bindings" OFF)
```

**Comment by vincentchabannes** [comment]
@romainhild in fact, the problem come from the call of find_package of matlab, we need to specify the components. In the nlopt repo, the fix has been applied (see https://github.com/stevengj/nlopt/blob/master/CMakeLists.txt#L322 or https://github.com/stevengj/nlopt/pull/154)  but we don't have merged our fork.

Not need to patch feelpp, just we need to update our fork of nlopt

**Comment by romainhild** [comment]
Indeed! I wasn't sure if we could update our fork since it seems there is a lot of commits, and some other changes in our fork.
but just by curiosity, why the `add_subdirectory(octave)` was commented out ?

**Comment by vincentchabannes** [comment]
there are few changes in fact, we have only patch the name of targets (the changes are only in CMakeLists.txt. Normally, we can also use a version of nlopt install in the system.

In waiting, just run cmake with -DBUILD_MATLAB=OFF

**Comment by romainhild** [comment]
ok! Do I close this issue or wait until it is really fixed ?

**Comment by prudhomm** [comment]
we are now running with cmake 3.12 in docker, I don't have this issue.

**Comment by romainhild** [comment]
indeed, this is weird. I tried with cmake 3.12.2 and I have the same error. So it appears only(?) on atlas.
Here is the error:
```
CMake Error at /ssd/hild/opt/softwares/cmake/3.12.2/share/cmake-3.12/Modules/FindMatlab.cmake:1171 (file):
  file STRINGS file "/usr/VersionInfo.xml" cannot be read.
Call Stack (most recent call first):
  /ssd/hild/opt/softwares/cmake/3.12.2/share/cmake-3.12/Modules/FindMatlab.cmake:1433 (_Matlab_get_version_from_root)
  feelpp/contrib/nlopt/CMakeLists.txt:299 (find_package)


CMake Error at /ssd/hild/opt/softwares/cmake/3.12.2/share/cmake-3.12/Modules/FindMatlab.cmake:1173 (string):
  string sub-command REGEX, mode MATCH needs at least 5 arguments total to
  command.
Call Stack (most recent call first):
  /ssd/hild/opt/softwares/cmake/3.12.2/share/cmake-3.12/Modules/FindMatlab.cmake:1433 (_Matlab_get_version_from_root)
  feelpp/contrib/nlopt/CMakeLists.txt:299 (find_package)


-- Could NOT find Matlab (missing: Matlab_INCLUDE_DIRS Matlab_MEX_LIBRARY Matlab_MEX_EXTENSION) (found version "unknown")
```
The last line is normal and is what happens also in docker. Anyway, the fix has been made in nlopt.

**Comment by prudhomm** [comment]
@vincentchabannes @romainhild how about setting in feelpp
```
option (BUILD_OCTAVE "build octave bindings" OFF)
option (BUILD_MATLAB "build matlab bindings" OFF)
```
right before going into `nlopt`, that should do it.

**Comment by vincentchabannes** [comment]
we should update nlopt fork, a clean solution
