### ISSUE TITLE
Test inner_curl fails to compile in testsuite

### ISSUE THREAD

**Issue by prudhomm** [feelpp/feelpp#1227]
The test inner_curl fails to compile in testsuite. It has been currently commented out as it breaks the testsuite compilation and execution.

**Comment by romainhild** [comment]
I have updated the testsuite to check that `curl` computes indeed the curl, both in 2D and 3D.
But even if it is close enough, in 2D it fails to compile the last line:
```    auto Vh = Pchv<2>(mesh);
    auto Wh = Pch<1>(mesh);
    auto f = expr<2,1>("{2*x^2+3*y^2,3*x^2+2*y^2}:x:y");
    auto g = expr("6*x-6*y:x:y");
    auto u = Vh->element(f);
    auto v = Wh->element(g);
    auto err = normL2(_range=elements(mesh), _expr=curlv(u)-idv(v));
```
The error is a size that don't match:
```
/home/u2/hild/Devel/develop/feelpp/feel/../feel/feelvf/shape.hpp:255:5: error: no matching function for call to 'assertion_failed'
    BOOST_MPL_ASSERT_MSG( mpl::bool_<is_rank_ok>::value,
```

**Comment by vincentchabannes** [comment]
it's probably due to this code (line 105 of feel/feelvf/operators.hpp : 
```
          ( OpCurl , curl , curl , 1, 0, 0, vm::CURL|vm::JACOBIAN|vm::KB|vm::FIRST_DERIVATIVE , RankSame,false,-1,1 ), \
```
The keyword `RankSame` is good in 3d but not in 2d, it should be `RankDown`

**Comment by romainhild** [comment]
indeed, that is the issue. By changing that the 2D case works, but not the 3D anymore.

**Comment by romainhild** [comment]
@prudhomm @vincentchabannes I commited a fix.
The curl operator is no more RankSame but RankCurl, which return RankSame in 3D and RankDown in 2D.

**Comment by romainhild** [comment]
It seems that my fix breaks other tests `feeldiscr/test_hdiv_oneelt` and `feeldirsc/test_hcurl_oneelt`.
It is again a problem of mismatch sizes in projection operator.
What is weird is that it happens in a projection from a Lagrange vectorial space to itself, with no `curl` involved:
```
    auto E = Py()*unitX() + Px()*unitY();
    lagrange_space_v_ptrtype Yh_v = lagrange_space_v_type::New( mesh ); //lagrange vectorial space
    auto l2_lagV = opProjection( _domainSpace=Yh_v, _imageSpace=Yh_v, _type=L2 ); //l2 vectorial proj
    auto E_pL2_lag = l2_lagV->project( _expr= E );
```

**Comment by romainhild** [comment]
I think I've found the problem, it is this line:
https://github.com/feelpp/feelpp/blob/cc03dabcf69ffe25356c39493eea016475f71b57/feelpp/feel/feeldiscr/projector.hpp#L277-L278
The curl expression is not the right size.
Changing it to
```
(curl_expr, *, (vf::zero< mpl::if_<mpl::equal_to<mpl::int_<domain_space_type::nDim>, mpl::int_<3> >,
                                                 mpl::int_<3>, mpl::int_<1> >::type::value, 1>() ) )
```
fix the compilation issues.

What are the cases where `nComponents` is different from `nDim` ?

**Comment by prudhomm** [comment]
Indeed it broke the testsuite. I will have a look over the weekend.

**Comment by romainhild** [comment]
the problem comes from the line I indicated in my previous message, but the fix I proposed, does not work for 3D scalar fields.
We would need something like this:
```
(curl_expr, *, (vf::zero< mpl::if_<mpl::equal_to<mpl::int_<domain_space_type::nComponents>, mpl::int_<1> >, 
                                   mpl::int_<1>,
                                   mpl::if_<mpl::equal_to<mpl::int_<domain_space_type::nDim>, mpl::int_<3> >,
                                            mpl::int_<3>, mpl::int_<1> > >::type::value, 1>() ) )
```
This is if we are scalar, then the curl is scalar (??), else we are vectorial, if we are in 3D then the curl is vectorial else it is scalar.
The curl of a scalar is not defined but it should keep the compilation safe.

**Comment by romainhild** [comment]
The problem comes from the line in my previous message, but the fix I proposed break the compilation for 3D scalar field.
It should be something like:
```
(curl_expr, *, ( vf::zero< mpl::if_<mpl::equal_to<mpl::int_<domain_space_type::nComponents>, mpl::int_<1> >,
                                    mpl::int_<1>,
                                    typename mpl::if_<mpl::equal_to<mpl::int_<domain_space_type::nDim>, mpl::int_<3> >,
                                                      mpl::int_<3>, mpl::int_<1> >::type >::type::value, 1>() ) )
```
That is: if the field is scalar, its curl is scalar (even if it's not really defined), else it is vectorial, if it is 3D, the curl is vectorial, else it is scalar.
