### ISSUE TITLE
Test feelpp_test_eigenmodes FTE

### ISSUE THREAD

**Issue by prudhomm** [feelpp/feelpp#1229]
feelpp_test_eigenmodes currently fails at execution in the check. It should be fairly easy to fix. 

@romainhild could you take care of this. simply use docker feelpp/feelpp:latest and recompile this testsuite exampl

**Comment by prudhomm** [comment]
@romainhild I would like this to be in v106. We support SLEPc and we should have tests properly running.

**Comment by romainhild** [comment]
I have found the error, slepc added some new options for the position of the spectrum that are needed when using a target.
I'm fixing this by adding these options in feelpp.

**Comment by romainhild** [comment]
it should be done @prudhomm
