### ISSUE TITLE
Test eim_grepl times out in sequential

### ISSUE THREAD

**Issue by prudhomm** [feelpp/feelpp#1230]
The test feelpp_test_eim_grepl fails in docker/buildkite due to a timeout. It runs properly though
we should just increase the timeout a bit to ensure it goes through properly

see https://buildkite.com/feelpp/feelpp-testsuite/builds/44#5ad523f3-51cd-4faa-9271-f4a198f07318/1113-1871

/cc @vincentchabannes @jbwahl @romainhild

**Comment by vincentchabannes** [comment]
@prudhomm Indeed we need to run 2/3 times the tests in order to work. Probably we need to reduce the tolerance and the mesh size else the time too long. Or we can also move this one in a testsuite specific to mor, it's a full example.

**Comment by prudhomm** [comment]
the timeout is already 90s and it is going through on atlas with this, how about 120s ?

Also why is it only run in sequential and not in parallel ?

I propose to move the code in v107 is that ok ?

**Comment by vincentchabannes** [comment]
12O s is too long
