### ISSUE TITLE
use a single keyword for model json file

### ISSUE THREAD

**Issue by Trophime** [feelpp/feelpp#1240]
In some toolbox like hdg `model_json` is used for the model json file 
whereas in other part of feelpp this is `filename`.

It will be better and simpler to have only one keyword for that... ?
`model_json` is more explicit for me (could also be `model_file` in case 
the default format change at some point)

**Comment by romainhild** [comment]
in fact the default name is `mod-file`:
https://github.com/feelpp/feelpp/blob/dd5ca2db7a4d9097d76784c5fe714e84677364d6/feelpp/feel/feelmodels/modelproperties.hpp#L46-L49
But the toolboxes add `<prefix.>filename`. Should we change all to `model-file` or `model_file`, what is the convention here ? In options.cpp, both `-` and `_` are used.

We will need to be careful to not add a toolbox with an empty prefix.

**Comment by vincentchabannes** [comment]
For me model_file  is not adapted, the json has informations about model but not only (post-process, solver,...) .

I think filename is well adapted and should be keep, it allows to initialize a toolbox with a file (json or something else).

But we can add several options like --models.filename, --materials.filename, --post-process.filename ...  for load specifics part of the config.

**Comment by romainhild** [comment]
The keyword is filename now in all toolboxes
