### ISSUE TITLE
Add feature to handle multiple markers in boundary condition

### ISSUE THREAD

**Issue by romainhild** [feelpp/feelpp#1243]
For now a boundary condition can only support one marker.
We should add the possibility to add a `markers` keyword to handle multiple keywords.
Of course the current way should still be possible. Both should work:
```json
"temperature": {
  "Dirichlet": {
    "mymarker": {
      "expr":"0"
    }
  }
}
```
or 
```json
"temperature": {
  "Dirichlet": {
    "mybc": {
      "markers":["mymarker1","mymarker2"],
      "expr":"0"
    }
  }
}
```

This demands to change a lot of code, since in the toolboxes currently each boundary condition is handled as a pair of string (the marker) and expression where the string is the marker. It needs to be now a pair of string (the name mybc) and a pair of expression and a list of string (the markers).

**Comment by romainhild** [comment]
We should change from std::list to std::set for the list of markers, and I still need to check the hdg and mor parts.

**Comment by prudhomm** [comment]
and how about having regexp such as `"marker*` it would be nice to support that

**Comment by romainhild** [comment]
you mean that `"marker*"` should apply the boundary condition on every (face) marker of the mesh ?

**Comment by prudhomm** [comment]
I am not sure what you mean, I meant we have  "marker1" "marker2" and so on. Instead  of writing them all if it applies we could write  just "marker*"

**Comment by romainhild** [comment]
Ah ok it makes more sense. 
In fact there is already something like that in the fluid toolbox. But we could indeed move that in boundary conditions

**Comment by romainhild** [comment]
see here: https://github.com/feelpp/feelpp/blob/590416bd7b5ea669fd13f3dfa5df3c0a14113d5f/toolboxes/feel/feelmodels/fluid/fluidmechanicscreate.cpp#L92-L111
you need to put `"markers"="marker"` and `"number"=5` for example. We could put that directly in the boundary conditions instead, and it could work for all boundary conditions.

**Comment by romainhild** [comment]
@prudhomm @vincentchabannes proposed to take advantage of the boost format, and have something like:
```json
"mybc": {
  "markers":["bc%1%", "otherbc"],
  "number": 3,
  "expr": "0"
}
```
and we would have a list of marker `bc0,bc1,bc2,otherbc`.
We could then use something else than `number` for the argument...

**Comment by romainhild** [comment]
So in fact, we can now do something like:
```
"mybc": {
  "markers":["mark%1%","mymarker","toto%2%","feelpp%1%_p%3%"],
  "indice1":"1:3",
  "indice2":"2:8:2",
  "indice3":["A","D"],
  "expr":"0"
}
```
which will give the list of markers: `feelpp1_pA, feelpp1_pD, feelpp2_pA, feelpp2_pD, mark1, mark2, mymarker, toto2, toto4, toto6`

**Comment by vincentchabannes** [comment]
@romainhild @prudhomm I think it should be `markers-index*` not only `index*`.
This json property should be used in many parts, not only for bc and use `index*` can generate conflicts.
Another solution is to create a subtree : 
```
"mybc": {
  "markers":  {
    "name":["mark%1%","mymarker","toto%2%","feelpp%1%_p%3%"],
    "index1":"1:3",
    "index2":"2:8:2",
    "index3":["A","D"]
  },
  "expr":"0"
}
```
I think the second solution is better, and we can update easily the marker property. Allow to support for example :  
* boundaryfaces, internalfaces,   ....
* marker from an expression
* marker defined in only one material
And of course, we need to keep functional the current version of develop

Moreover, we need to create a new class `ModelMarkers` for manage markers.

**Comment by prudhomm** [comment]
but `index` refers to the regexp which has nothing to do with the markers in general no ?

**Comment by romainhild** [comment]
Ok indeed it would be more flexible, and I thought about using this also for the materials and other parts.
The new class would be a subclass of a set of string ? With a constructor that takes a ptree ? What else would it do ?
I also thought about renaming the `ExpressionListAtMarkers` as `ModelBoundaryCondition` and have it store also the different kind of `Expr` of the boundary condition. But I guess it would need a lot more work to change that.

For the markers, for now, we could do: 
```
"markers"="mymarker"
"markers"=["mark1",mark2"]
"markers":{
  "name":"mark%1%", or ["mark%1%", "bc%2%"],
  "index1":"1:3",
  "index2":["A","B"]
}
```
If it is in its own subtree, `index` is ok, no ?

And by the way, I don't use `boost::format` for this, so we could use something else than `%n%`, as long as it could not be found in a regular marker.
