### ISSUE TITLE
Support boost 1.68

### ISSUE THREAD

**Issue by vincentchabannes** [feelpp/feelpp#1247]
I have investigated the use of boost 1.68 and I found (at least) 2 problems : 

1) A compilation error due to a change in boost::hana::tuple, the class is marked final so we can't create a class which inherits of boost::hana::tuple.
2) If we look to changes in boost 1.68, we can find this [fix](https://svn.boost.org/trac10/ticket/4427). The pull request related to this issue is [here](https://github.com/boostorg/fusion/pull/183). It change the type of functor argument  (they remove const& ) . So the functor is copied inside the for_each and we cannot access use the functor for get some modification after the for_each (or need to use pointer or reference). I read the doc from previous versions of boost and indeed the signature of for_each is this one. Thus the fix is more delicate, need to look all fusion::for_each

**Comment by vincentchabannes** [comment]
It's almost fixed, still, one thing to do is to the compilation error with ProductSpaces and ProductSpaces2 which can not inherit of boost::hana::tuple. The hana tuple should be an attribute.

**Comment by vincentchabannes** [comment]
see [here](https://github.com/boostorg/hana/commit/5af6066e616a2069bbf80cf687ccfe2c6e7b2530#diff-e0039d1404b40b136a22bfbacb35be7d) for explanation about hana::tuple is final

**Comment by prudhomm** [comment]
I will look into that. I am focusing on eye2brain and the ParaviewWeb interface at the moment

**Comment by vincentchabannes** [comment]
I am on it. I will put a fix in a branch and you can see later.
