### ISSUE TITLE
Compute elements sets with marked entities

### ISSUE THREAD

**Issue by prudhomm** [feelpp/feelpp#1263]
to compute forces eg for fluids with respect to volume then we need to be able to select all the elements touching the boundary (with a point edge or face) on which we need to compute the force

**Comment by vincentchabannes** [comment]
an example : 
```
auto rangeFaces = boundaryfaces(mesh);
auto range1 = elements(mesh,rangeFaces,ElementsType::MESH_POINTS); // elts connected by a point
auto range2= elements(mesh,rangeFaces,ElementsType::MESH_EDGES ); // elts connected by a edge (in 2d correspont to face case)
auto range3 = elements(mesh,rangeFaces,ElementsType::MESH_FACES ); // elts connected by a face
```

**Comment by prudhomm** [comment]
And how to get all of them? We use | with the different entities?

**Comment by prudhomm** [comment]
Ok we use `concatenate` for this!

see here https://github.com/feelpp/feelpp/blob/develop/feelpp/feel/feelmesh/concatenate.hpp
