### ISSUE TITLE
Add radiation type of boundary condition for heat toolbox

### ISSUE THREAD

**Issue by romainhild** [feelpp/feelpp#1274]
Radiation is the type of heating due to the windows.

Possible benchmarks:
- https://www.comsol.fr/paper/solar-radiation-effects-on-the-epoxy-adhesive-temperature-used-to-bond-cfrp-to-c-64131
- https://www.comsol.fr/paper/design-of-solar-thermal-dryers-for-24-hour-food-drying-processes-29072
- https://www.comsol.fr/paper/heat-transfer-optimization-of-a-solar-radiation-concrete-oven-for-rural-areas-40572

**Comment by prudhomm** [comment]
@romainhild @vincentchabannes could we merge this branch, I may need to have radiation type BC

**Comment by prudhomm** [comment]
@romainhild @vincentchabannes could we merge this branch in develop ?

**Comment by prudhomm** [comment]
After discussing with @vincentchabannes this cannot be merged as-is. it will require picking the development and insertion in v108

**Comment by romainhild** [comment]
We also need to compute the view factor, which is computationally intensive.

**Comment by lberti** [comment]
@vincentchabannes @prudhomm 
I looked into the papers proposed above. 
- Paper 3 does not seem to propose a problem with heat transfer through radiation,
- Paper 2 proposes a case of heat transfer with a simple hexahedral geometry,
- Paper 1 proposes a coupled solid mechanics-heat transfer example.

Should the cases be implemented or the ones of pure radiation are sufficient (square, cylindrical, triangular cavities)?

**Comment by prudhomm** [comment]
this is connected to #1908 and #1809 and #1909
