### ISSUE TITLE
Mesh Adaptation in //

### ISSUE THREAD

**Issue by cdaversin** [feelpp/feelpp#129]
Mesh adaptation in // doesn't work actually.

Indeed, each processors will compute the metric for his own dofs to create the file given to gmsh (.pos) to build the adapted mesh.
The initial idea is to create a pos file per proc, concatenate these file into one and give it to gmsh which make the adapted mesh in a sequential way.

This can't be done due to the dofs on the interface between subdomains (for which a metric will be given by the two concerned processors)

So the implementation of mesh adaptation as to be reconsidered to be used in //

**Comment by prudhomm** [comment]
we could use pampa as discussed in #898

**Comment by prudhomm** [comment]
a new pampa version  is out
```
Release v2.0.0 of the PaMPA software is now available.

PaMPA is a software library for handling unstructured meshes in
parallel, on distributed memory architectures. PaMPA speeds-up and
eases the writing of scientific solvers that implement compact
schemes and models, by providing abstractions of mesh entities
(e.g. elements, faces, edges, nodes, etc.) and their interrelations.

The core library of PaMPA 2.0.0 (PaMPA-Core) is freely downloadable
from https://gitlab.inria.fr/PaMPA/PaMPA-Core, under the GPL licence.

The parallel remeshing extension module of PaMPA 2.0.0
(PaMPA-Remesh) is available at no cost under a proprietary,
evaluation licence valid for 30 days. Please contact us in order to
benefit from this offer.

PaMPA-Remesh runs concurrently multiple sequential remeshing tasks
to perform dynamic parallel remeshing and redistribution of very
large unstructured meshes. E.g., it can remesh a tetrahedral mesh
from 200 million elements to 1 billion elements in 10 minutes on
120 Broadwell procs, using the Mmg sequential tetrahedral remesh.
This final mesh was used for an industrial simulation.
```
mmg: http://www.mmgtools.org/

**Comment by prudhomm** [comment]
@Trophime you might also be interested in this. see previous discussions

**Comment by metivett** [comment]
@prudhomm Do you think we can get the remeshing module with a non-proprietary license ?

**Comment by Trophime** [comment]
I also run into this [meshadapt](https://fastmath-scidac.llnl.gov/software/meshadapt.html)

**Comment by prudhomm** [comment]
This is now provided by mmg and parmmg #1430 in feelpp
