### ISSUE TITLE
Setting the options prefix for the HDG toolbox apps

### ISSUE THREAD

**Issue by prudhomm** [feelpp/feelpp#1292]
currently, the hdg toolbox can configure their prefix eg `mixedpoisson`. This is a bit confusing, misleading and may be an issue as complicated application are built. 
I think we want to retain a base prefix and I propose `hdg.poisson` (mixed is implicit here) and the user can pass an extra prefix if he/she wants to have several poisson toolboxes.

We use `hdg` to indicate that we are in the HDG toolbox and then `poisson`, `elasticity`, `poroelasticity`, `stokes`,...  to indicate the model class 

if the user defines no prefix then the command line prefix is `hdg.poisson`
if the user defines the prefix `app1` then the command line prefix is `hdg.poisson.app1`

that way we are more in line with the options of the other toolboxes.
This change means that we need to update the cfg files to accommodate the change of prefix

**Comment by prudhomm** [comment]
I forget to mention that it would also make it cleaner for the python wrapper

**Comment by prudhomm** [comment]
basically we hardcode `hdg.poisson` which makes sense IMO

**Comment by prudhomm** [comment]
however there is poroelasticity hdg toolbox and we might want `hdg.poroelasticity.poisson`and `hdg.poroelasticity.elasticity` to configure the Poisson and Elasticity part instead of configuring the Poisson part of the poroelasticity model using `hdg.poisson`.

in that case it means two arguments for the options function: 

- the user prefix eg `app1` and 
- the toolbox prefix `hdg.poisson` or `hdg.poroelasticity.poisson`

**Comment by lsala** [comment]
but in this case if we use `hdg.poroelasticity.poisson` instead of `hdg.poisson` aren't we doubling the options? 
I imagine such as in FSI that you specify the fluid part and the solid part as for the fluid toolbox and the solid toolbox, in the same way I see poroelasticity with the hdg poisson part and the hdg elasticity part

**Comment by prudhomm** [comment]
why doubling ?

**Comment by prudhomm** [comment]
this is done
