### ISSUE TITLE
Support C++17 with libc++

### ISSUE THREAD

**Issue by vincentchabannes** [feelpp/feelpp#1299]
Some std functions (as std::random_shuffle or std::auto_ptr) have been removed in c++17.
And it seems the case with libc++ but not with libstdc++.

In particular, some previous version of boost use these functions with no check if it's compile with c++17 support.

**Comment by prudhomm** [comment]
indeed some functions/classes from the c++ lib have been deprecated in C++14 and removed in C++17 , see here for some details: https://www.mycplus.com/featured-articles/cplusplus-17-features/

**Comment by prudhomm** [comment]
another source is here https://devblogs.microsoft.com/cppblog/c17-feature-removals-and-deprecations/

**Comment by vincentchabannes** [comment]
and probably the libstdc++ doesn't yet remove these deprecated features.

Now, feel++ compile and run on my macos (macport)
