### ISSUE TITLE
Disabling IO in ModelMeasureStorage

### ISSUE THREAD

**Issue by prudhomm** [feelpp/feelpp#1301]
`ModelMeasureStorage` gathers measures for a toolbox from JSON specifications and then provides `exportMeasures()` to save to a file. Most toolboxes support the measure system however we should be able to 

 * access the output measure from the interface 
 * decide whether we really want to save to a file or not.

Regarding the latter, we don't necessarily want to save the measure to a disk. For example, using OpenTURNS we may have to do hundreds or thousands of evaluations for different parametrization of the toolbox, access them but discard them afterward ( or possibly save them into one big file.)
So the usage at play here is a input - output use case, we set a parametrization and get the response of the system through the measures (we may want to disable any IO, field export...)

**Comment by prudhomm** [comment]
@vincentchabannes I propose to add three functions to `ModelMeasureIO`

 * `disableExport()`  / `enableExport()` to disable / enable exporting measures
 * `exportEnabled()` returns a `bool` about the state of exporting measures

now in toolbox, `::exportMeasures` a small change, the following kind of code
```c++
if ( hasMeasure )                                                                                                                      
    {                                                                                                                                                                                               
        this->postProcessMeasuresIO().exportMeasures();                                                                                    
        this->upload( this->postProcessMeasuresIO().pathFile() );                                                                          
    }  
```
becomes
```c++
if ( hasMeasure && this->postProcessMeasuresIO().exportEnabled() )                                                                                                                      
    {                                                                                                                                                                                               
        this->postProcessMeasuresIO().exportMeasures();                                                                                    
        this->upload( this->postProcessMeasuresIO().pathFile() );                                                                          
    }  
```

what do you think ? other propositions ?

**Comment by vincentchabannes** [comment]
no problem with this proposition

**Comment by prudhomm** [comment]
I will work on this very soon. This is mandatory for several projects

**Comment by prudhomm** [comment]
@vincentchabannes I updated the issue. instead of `save(time)`. how about using `commit(time)`  to commit the data to a time index ? then we could call save if required or just retrieve the data committed

**Comment by vincentchabannes** [comment]
agree!
