### ISSUE TITLE
Support sensor framework for data assimilation

### ISSUE THREAD

**Issue by prudhomm** [feelpp/feelpp#1324]
We need to have a framework to model and work with sensors for data assimilation and their mathematical representation

**Comment by romainhild** [comment]
we should be able to store informations (position, type, radius, field) about sensors in the json file describing the model.
@prudhomm @vincentchabannes do you agree ?

Maybe create a new section in the json for this ? or use the output section already in place. What do you think ?

**Comment by romainhild** [comment]
We also need to implement the pointwise sensor type. The class is here but I don't know how to create the liner form associated with it so it's empty for now.

**Comment by prudhomm** [comment]
The information regarding the sensor is in the class sensor description if i remember correctly. The info wzs taken from the csv file. It should be trivial to use json

**Comment by prudhomm** [comment]
Pointwise functional requires interpolation for one point and encode it in the vector representing the functional. So that the scalar product with a function gives the evaluation at the point.
It would be nice to have also the derivatives and the normal flux

**Comment by romainhild** [comment]
ok I'm not sure I see how to do it, can you give me some hints ?

For the sensors description, I don't really see the point of having an entire class for this, I would rather have a constructor for the sensor or even for pbdw taking a json and constructing the senor(s) from that.

**Comment by prudhomm** [comment]
it is a small class, it  takes of the sensors network configuration. I think it makes sense in the long run. the information may be passed around. I don't think that pbdw should know the details of the sensors, it should only know the set of functionals

**Comment by romainhild** [comment]
We now have Sensor and SensorsMap [classes](https://github.com/feelpp/feelpp/blob/develop/feelpp/feel/feeldiscr/sensors.hpp) as well as [PBDW](https://github.com/feelpp/feelpp/blob/develop/feelpp/feel/feelcrb/pbdw.hpp) and [GEIM](https://github.com/feelpp/feelpp/blob/develop/feelpp/feel/feelcrb/geim.hpp).
Should we close this issue @prudhomm ?
