### ISSUE TITLE
Support framework for data assimilation

### ISSUE THREAD

**Issue by prudhomm** [feelpp/feelpp#1325]
Support features like

 - [x] geim
 - [x] pbdw #1364 
 - [x] sensor #1324

The developments are in ~~`feature/da`~~ `feature/geim-2`

**Comment by romainhild** [comment]
@prudhomm I have created a [branch](https://github.com/feelpp/feelpp/tree/feature/geim-2) to implement from scratch geim and pbdw.
GEIM seems to work fine, there is a test with it.
But PBDW has some problem, I don't have correct results...

I looked at what you did on the previous branch but I wanted to have something with the least dependance possible. So no ModelCrbBase for now.

Could you take a look if you see where the error could come from for PBDW ?

I saw also the classes for the sensors, I should update the code to use that, but I think we should keep the possibility to be more general.

What do you think ?

**Comment by prudhomm** [comment]
the sensor framework is to be quite general and provide a way to retrieve real sensor data as well as virtual ones (measurements from a numerical simulation)

**Comment by romainhild** [comment]
Ok I looked a little bit more and I think I'll take pointer to FsFunctionalLinear for GEIM and Sensors for PBDW. In GEIM we want to be able to take any linear form, whereas in PBDW it should only be sensors.

But I wonder what is the purpose of the P0 space and the marker in the Sensors class ?

**Comment by prudhomm** [comment]
If I remember correctly it is used to localize the support the domain for the sensor model

**Comment by romainhild** [comment]
@prudhomm PBDW works now, I just have to add the database system to it.

**Comment by prudhomm** [comment]
what was the problem ?

**Comment by romainhild** [comment]
An error when constructing the matrix with the Riesz representation of the sensors.
It should be ok now, I'll open the pull request.

**Comment by romainhild** [comment]
@prudhomm should we close this issue ?
