### ISSUE TITLE
HDG toolbox : Robin BC yielding high error

### ISSUE THREAD

**Issue by PhilippeRicka** [feelpp/feelpp#1333]
In branch `hdg-robin`, directory `feelpp/toolboxes/hdg/poisson/test-hdgRobin`, just run:
```
feelpp_toolbox_hdg_poisson --config-file dirichlet.cfg --gmsh.hsize=0.05
```
or:
```
feelpp_toolbox_hdg_poisson --config-file robin.cfg --gmsh.hsize=0.05
```
In the unit square ; exact solution is `p=x*(1-x)*(y-1)+y*y*y/3-y*y+y+2*x`, yielding with all-Dirichlet BC:
```
||p-p_ex||_L2=  7.25312e-05
||u-u_ex||_L2=  0.000191508
```
and with Dirichlet + Robin BC:
```
||p-p_ex||_L2=  0.101566
||u-u_ex||_L2=  0.299701
```
Maybe Robin BC are not properly implemented ?

**Comment by romainhild** [comment]
can you commit your test ?

**Comment by PhilippeRicka** [comment]
Seems I am not authorized to push into `develop`. I commited into the new branch `hdg-robin`.

**Comment by romainhild** [comment]
@PhilippeRicka the right hand side was set during the assembly of the const part of the matrix, and then was set to zero before assembling the rest of the right hand side.
For your example, I'm not sure the conditions are set to the right value. I tried with `grad(P).n + p` for the `expr2` and it is working. Can you check and if it's ok, open a pull request ?
