### ISSUE TITLE
Balancing load for IBC 

### ISSUE THREAD

**Issue by prudhomm** [feelpp/feelpp#1340]
We have imbalance when having ibc.  the results are normal and expected with the current implementation. The issue is due to the partitioning of the IBC interface in parallel which generates lots of communication. The solution is to tell metis to keep in the same partition the elements touching the IBC interface. 

@lsala test + option to enable/disable specific partitioning

**Comment by lsala** [comment]
Solved with commit 9da540d468414ead977a6df2bb76b4b5e1701421
