### ISSUE TITLE
Problem with Nedelec in 3D in parallel

### ISSUE THREAD

**Issue by romainhild** [feelpp/feelpp#1384]
In 3D, using Nedelec elements gives wrong results.

see test feeldiscr/test_hcurl for example.

**Comment by prudhomm** [comment]
Could you provide the analysis here?

**Comment by prudhomm** [comment]
Have you checked the H1 approximation?

**Comment by romainhild** [comment]
with the functions provided in the testsuite, in sequential the error converges correctly but not in parallel.
- In sequential:
```
[TestHCurl]
hsize = 0.2
/home/u2/hild/working-tree/hdg/testsuite/feeldiscr/test_hcurl.cpp(260): error: in "space/test_hcurl_example_3d": absolute value of errorU{0.30330981291728132} exceeds 0.25
...
[TestHCurl]
hsize = 0.1
/home/u2/hild/working-tree/hdg/testsuite/feeldiscr/test_hcurl.cpp(260): error: in "space/test_hcurl_example_3d": absolute value of errorU{0.15489240439918406} exceeds 0.10000000000000001
```
- in parallel (np 2):
```
[TestHCurl]
hsize = 0.2
/home/u2/hild/working-tree/hdg/testsuite/feeldiscr/test_hcurl.cpp(260): error: in "space/test_hcurl_example_3d": absolute value of errorU{1.4661884181978198} exceeds 0.10000000000000001
...
[TestHCurl]
hsize = 0.1
/home/u2/hild/working-tree/hdg/testsuite/feeldiscr/test_hcurl.cpp(260): error: in "space/test_hcurl_example_3d": absolute value of errorU{1.8531095993035325} exceeds 0.10000000000000001
```

To reproduce:
`mpirun -np 2 feelpp_test_hcurl -l all -- --config-file test_hcurl.cfg`

**Comment by romainhild** [comment]
This comes from the H5 format for the mesh.
To use Nedelec elements, we need to use meshes generated and partitioned by gmsh2.

**Comment by prudhomm** [comment]
@romainhild would it be possible to put a proper mesh on girder and have the test download it and use it ?
