### ISSUE TITLE
Clean fmu/fmi support and support FMI generated by OpenModelica 1.13/1.14

### ISSUE THREAD

**Issue by prudhomm** [feelpp/feelpp#1399]
since OpenModelica 1.13 generated fmi are not working properly, only the last time step data is retrieved and all time steps are set to the value.
Some cleanup  is needed. 
Also there is the question of linking feelpp to openmodelica. it is probably not needed.

/cc @vincentchabannes @lsala

**Comment by prudhomm** [comment]
@vincentchabannes the OM libs are not needed to run the FMUs at all. I commented out the OpenModelica libs and everything is fine so far. I am checking a few more things and if ok, we should be good to remove the OM libs for now.

**Comment by vincentchabannes** [comment]
great!
