### ISSUE TITLE
CDash

### ISSUE THREAD

**Issue by vhuber** [feelpp/feelpp#141]
With cdash, we test the develop branch. When you follow a link to github to look the code, it redirect you to the branch master.
Could you please fix it (I do not have the root login to cdash)

**Comment by aancel** [comment]
@jjomier Is it possible to correct the link to the correct branch ?

**Comment by prudhomm** [comment]
The bug is still there

**Comment by jjomier** [comment]
Nous sommes en train de travailler pour pouvoir mettre a jour my.cdash.org mais ce n'est pas encore pret.
