### ISSUE TITLE
Assertion triggered in Tensor Assignement 

### ISSUE THREAD

**Issue by prudhomm** [feelpp/feelpp#1425]
when not using `-DNDEBUG` we have systematically an assertion triggered when calculating the gradient of the basis functions. 
the issue is discussed here it seems https://gitlab.com/libeigen/eigen/issues/1274 and I have left aa message.
in the meantime, we should use `-DNDEBUG`.

@vincentchabannes  this breaks in particular all the toolboxes

**Comment by prudhomm** [comment]
Note that the operation is legitimate and in particular, the sizes of the tensors are perfectly fine

**Comment by romainhild** [comment]
@prudhomm what does -DNDEBUG do ? Can we still use gdb with it ?
The changes you made are only for the toolboxes ? What need to be changed to use it for mor for example ?

**Comment by prudhomm** [comment]
The macro disables assertion. I used it for deb packages otherwise all toolboxes app crash (at least the ones i tested). No problem to use gdb of course. Preferably in debug mode

**Comment by vincentchabannes** [comment]
@prudhomm there is a problem in feel++, not eigen. We try to assign a tensor <1,1,nDim> (result of contract) and a tensor <1,nDim,1>. Just apply a reshape fix the issue. I am almost certain that I have already fix that in the past.

**Comment by prudhomm** [comment]
I know, we discussed that in the past and I am pretty sure I fixed the code to avoid the reshape.
I am looking into that :(

**Comment by vincentchabannes** [comment]
An another Eigen assert can be solved by adding ```M_phi_eigen.resize( M_ref_ele->nbDof(), __pts.size2() );``` in PolynomialSet::PreCompute::update(..)

**Comment by prudhomm** [comment]
I found another issue with normal_component

**Comment by romainhild** [comment]
I have another issue at polynomialset_impl.hpp:310
```
feelpp_mor_saddle-thermoelectric-nonlinear-app: /home/u2/hild/working-tree/crb-dev/feelpp/contrib/eigen/unsupported/Eigen/CXX11/src/Tensor/TensorAssign.h:146: bool Eigen::TensorEvaluator<const Eigen::Tens
orAssignOp<Eigen::TensorFixedSize<double, Eigen::Sizes<3, 3, 1>, 0, long>, const Eigen::TensorContractionOp<const std::array<Eigen::IndexPair<int>, 1>, const Eigen::TensorContractionOp<const std::array<Ei
gen::IndexPair<int>, 1>, const Eigen::TensorFixedSize<double, Eigen::Sizes<3, 3, 1>, 0, long>, const Eigen::TensorMap<Eigen::TensorFixedSize<const double, Eigen::Sizes<3, 3>, 0, long>, 0, MakePointer>, co
nst Eigen::NoOpOutputKernel>, const Eigen::TensorMap<Eigen::TensorFixedSize<const double, Eigen::Sizes<3, 3>, 0, long>, 0, MakePointer>, const Eigen::NoOpOutputKernel> >, Eigen::DefaultDevice>::evalSubExp
rsIfNeeded(Eigen::TensorEvaluator<const TensorAssignOp<type-parameter-0-0, type-parameter-0-1>, type-parameter-0-2>::EvaluatorPointerType) [Derived = const Eigen::TensorAssignOp<Eigen::TensorFixedSize<dou
ble, Eigen::Sizes<3, 3, 1>, 0, long>, const Eigen::TensorContractionOp<const std::array<Eigen::IndexPair<int>, 1>, const Eigen::TensorContractionOp<const std::array<Eigen::IndexPair<int>, 1>, const Eigen:
:TensorFixedSize<double, Eigen::Sizes<3, 3, 1>, 0, long>, const Eigen::TensorMap<Eigen::TensorFixedSize<const double, Eigen::Sizes<3, 3>, 0, long>, 0, MakePointer>, const Eigen::NoOpOutputKernel>, const E
igen::TensorMap<Eigen::TensorFixedSize<const double, Eigen::Sizes<3, 3>, 0, long>, 0, MakePointer>, const Eigen::NoOpOutputKernel> >, Device = Eigen::DefaultDevice]: Assertion `dimensions_match(m_leftImpl
.dimensions(), m_rightImpl.dimensions())' failed.
```
