### ISSUE TITLE
Support for rigid/elastic bodies

### ISSUE THREAD

**Issue by prudhomm** [feelpp/feelpp#1429]
add support for rigid and elastic body motion in fluids

- [x] interpolation operator between fluid velocity and rigid motion
- [x] moment of inertia in 3D for any shapes (currently scalar, should be matricial)

**Comment by lberti** [comment]
@prudhomm @vincentchabannes I propose to close this issue. 
At present, it is possible to simulate the motion of rigid bodies in a fluid by inserting the "body" section in the json file (example [here](https://github.com/feelpp/feelpp/blob/464c3065631f3a018e8968651a5089bb2a0f13a0/toolboxes/fluid/cases/moving_body/gravity/shape_under_gravity/3d/shape_under_gravity.json)). 
Deformability can be handled using the "elastic-velocity" keyword in the "body" section of the json (example [here](https://github.com/feelpp/feelpp/blob/464c3065631f3a018e8968651a5089bb2a0f13a0/toolboxes/fluid/cases/moving_body/swimmers/spermatozoon/2d/spermatozoon_2d.json)).
Bodies with parts moving relative to each other (translation only) can also be simulated (example [here](https://github.com/feelpp/feelpp/blob/464c3065631f3a018e8968651a5089bb2a0f13a0/toolboxes/fluid/cases/moving_body/three_sphere_2D/three_sphere_2D.json))

**Comment by lberti** [comment]
Moreover, thanks to the struct `ElasticBehavior`, defined in toolboxes/feel/feelmodels/fluid/fluidmechanics.hpp, one can define, in the JSON, the update of elastic-velocity and elastic-displacement, and possibly decouple them (i.e. in order to impose a tangential fluid velocity on a rigid swimmer).
