### ISSUE TITLE
Problem mesh MPI

### ISSUE THREAD

**Issue by lberti** [feelpp/feelpp#1438]
I have this error when starting a simulation with the fluid toolbox. Sometimes I get it, other times the simulation starts. In this case, I used the mesh file instead of the .geo . I have used the Gmsh partition option=1.

` terminate called after throwing an instance of 'boost::wrapexcept<boost::mpi::exception>'
  what():  MPI_Test: MPI_ERR_TRUNCATE: message truncated
*** Aborted at 1583238183 (unix time) try "date -d @1583238183" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGABRT (@0x87b00020b03) received by PID 133891 (TID 0x7fe6de4e8500) from PID 133891; stack trace: ***
    @     0x7fe67f582390 (unknown)
    @     0x7fe67b53e428 gsignal
    @     0x7fe67b54002a abort
    @     0x7fe67ee32af3 __gnu_cxx::__verbose_terminate_handler()
terminate called after throwing an instance of '    @     0x7fe67ee38a56 __cxxabiv1::__terminate()
boost::wrapexcept<boost::mpi::exception>'
  what():  MPI_Test: MPI_ERR_TRUNCATE: message truncated
    @     0x7fe67ee38a91 std::terminate()
*** Aborted at 1583238183 (unix time) try "date -d @1583238183" if you are using GNU date ***
    @     0x7fe67ee38cc3 __cxa_throw
PC: @                0x0 (unknown)
*** SIGABRT (@0x87b00020b12) received by PID 133906 (TID 0x7f0d6cd03500) from PID 133906; stack trace: ***
    @     0x7f0d0dd9d390 (unknown)
    @     0x7fe6a8166135 boost::throw_exception<>()
    @     0x7f0d09d59428 gsignal
    @     0x7f0d09d5b02a abort
    @     0x7f0d0d64daf3 __gnu_cxx::__verbose_terminate_handler()
    @     0x7f0d0d653a56 __cxxabiv1::__terminate()
    @     0x7fe6a8735d10 boost::mpi::request::handle_dynamic_primitive_array_irecv<>()
    @     0x7f0d0d653a91 std::terminate()
    @     0x7fe6a3d801d2 boost::mpi::request::test()
    @     0x7f0d0d653cc3 __cxa_throw
    @     0x7f0d36981135 boost::throw_exception<>()
    @     0x7f0d36f50d10 boost::mpi::request::handle_dynamic_primitive_array_irecv<>()
    @     0x7fe6cdd5831a boost::mpi::wait_all<>()
    @     0x7f0d3259b1d2 boost::mpi::request::test()
    @     0x7fe6a8d8891f Feel::Mesh<>::updateEntitiesCoDimensionGhostCellByUsingNonBlockingComm()
    @     0x7f0d5c57331a boost::mpi::wait_all<>()
    @     0x7fe6a8d85871 Feel::Mesh<>::updateForUse()
    @     0x7f0d375a391f Feel::Mesh<>::updateEntitiesCoDimensionGhostCellByUsingNonBlockingComm()
    @     0x7fe6a8d7934a Feel::Mesh<>::createP1mesh()
    @     0x7f0d375a0871 Feel::Mesh<>::updateForUse()
    @     0x7f0d3759434a Feel::Mesh<>::createP1mesh()
    @     0x7fe6abbfe188 Feel::FeelModels::MeshALE<>::MeshALE()
    @     0x7fe6c1413940 Feel::FeelModels::boost_param_default_362meshale<>()
    @     0x7f0d3a419188 Feel::FeelModels::MeshALE<>::MeshALE()
    @     0x7f0d4fc2e940 Feel::FeelModels::boost_param_default_362meshale<>()
    @     0x7fe6c141376c Feel::FeelModels::boost_param_default_362meshale<>()
    @     0x7fe6c141351e Feel::FeelModels::boost_param_default_362meshale<>()
    @     0x7f0d4fc2e76c Feel::FeelModels::boost_param_default_362meshale<>()
    @     0x7f0d4fc2e51e Feel::FeelModels::boost_param_default_362meshale<>()
    @     0x7fe6c141344b Feel::FeelModels::boost_param_default_362meshale<>()
    @     0x7f0d4fc2e44b Feel::FeelModels::boost_param_default_362meshale<>()
    @     0x7fe6c101eb32 Feel::FeelModels::FluidMechanics<>::createALE()
    @     0x7f0d4f839b32 Feel::FeelModels::FluidMechanics<>::createALE()
    @     0x7f0d4f857321 Feel::FeelModels::FluidMechanics<>::init()
    @           0x41e141 Feel::runApplicationFluid<>()
    @           0x415fa8 main
    @     0x7fe6c103c321 Feel::FeelModels::FluidMechanics<>::init()
    @     0x7f0d09d44830 __libc_start_main
`

**Comment by romainhild** [comment]
It is linked to #1296 @vincentchabannes is already looking into it I think
