### ISSUE TITLE
quickstart HDG apps broken in develop

### ISSUE THREAD

**Issue by prudhomm** [feelpp/feelpp#1444]
The HDG apps are currently failing to execute in develop
https://buildkite.com/feelpp/feelpp/builds/3380#5b589a55-1761-4f82-bdba-b0c3fb8e112e/11789-12335

**Comment by prudhomm** [comment]
was already the case here
https://buildkite.com/feelpp/feelpp/builds/3375#1eb1d938-3b65-494b-9491-5f1dca462079/11844-12386

**Comment by prudhomm** [comment]
it seems it comes from this one
https://buildkite.com/feelpp/feelpp/builds/3365#ee0c42bd-5e1f-4f6d-9864-e5c47a1e7565/11908-12450
and this commit
https://github.com/feelpp/feelpp/commit/ba5c15975a3e69a79ad66bb96d66bfab650d80c9

**Comment by vincentchabannes** [comment]
@prudhomm I found where the issue come from. It's due to the conversion sympy2ginac. For example, this code :
```
>>> from sympy import *
>>> M= Matrix([[1, -1], [3, 4], [0, 2]])
>>> ','.join(str(ccode(sympify(e),standard='C99')) for e in Array(M.tolist()))
```
give this result in ubuntu 20.04 : 
```
'[1, -1],[3, 4],[0, 2]'
```
But the exepected result (in Feel++) should be : 
```
'1,-1,3,4,0,2'
```
And this is the case on atlas for example.

There is probably a change in the latest Sympy.

**Comment by vincentchabannes** [comment]
the quickstart testsuite is fixed, see [here](https://buildkite.com/feelpp/feelpp/builds/3384).
