### ISSUE TITLE
add option compute-manufactured-pde

### ISSUE THREAD

**Issue by thomas-saigre** [feelpp/feelpp#1453]
Issue à la demande de @prudhomm pour créer une nouvelle option `compute-manufactured-pde=true` or `false`. `Checker.check=true` or `false` vérifiera la solution numérique avec `checker.solution`

**Comment by prudhomm** [comment]
The language is english and you should provide more details so that other people understand what it is about

**Comment by thomas-saigre** [comment]
For example, when we use the command `feelpp_qs_laplacian_2d`, in order to see the norm of the error when `checker.check=false`, the option `compute-manufactured-pde` will allow to see it.

**Comment by prudhomm** [comment]
this has been implemented and fixed for the laplacian
