### ISSUE TITLE
prepare fmu in heat transfer to test fmi

### ISSUE THREAD

**Issue by prudhomm** [feelpp/feelpp#1457]
We have FMI support in feelpp thanks to eye2brain. We need however to test further our tools and have new simple fmu to test .
I suggest that we have fmus in heat transfer in building modeling.

@Zohra-D could you prepare with OM some simple heat transfer application that we could add to feelpp?

We have currently one case in `feelpp/tools/fmi/fmus`. the `.cfg` is stored on github whereas the fmu is stored on girder. 
here is the [cfg](https://github.com/feelpp/feelpp/blob/develop/feelpp/tools/fmi/fmus/bouncingball.cfg) with the reference to the fmu on girder.
the fmu is `feelpp/fmus` on girder [here](https://girder.math.unistra.fr/#collection/5a293e32b0e9571d65b9ec50/folder/5de42dceb0e95704757e1cd0)

/cc @romainhild @vincentchabannes

**Comment by prudhomm** [comment]
@romainhild could you help @Zohra-D integrating the fmu in feelpp ? thanks in advance

**Comment by romainhild** [comment]
sure, but I need to be able to launch `feelpp_fmi_fmu`, right ?

**Comment by prudhomm** [comment]
you will be in docker in a few minutes

**Comment by prudhomm** [comment]
@romainhild the feelpp_fmi_fmu is in docker

<img width="1063" alt="Screenshot 2020-03-26 10 40 30" src="https://user-images.githubusercontent.com/151693/77632473-54db1e80-6f4e-11ea-9510-05f448ffb669.png">
