### ISSUE TITLE
Possible MPI Deadlock with hMeasure

### ISSUE THREAD

**Issue by vincentchabannes** [feelpp/feelpp#1460]
@prudhomm your recent update about use hMeasure function in Feel::Mesh can generated a MPI deadlock, see for example feelpp_test_worldcomm in testsuite.
The issue is that you use the function `nelements( range, Zone::GLOBAL)`  inside and the MPI all_reduce done here uses the Environment worldComm.
Another point, when we called the hMeasure in Mesh::updateForUse(), we don't need to apply a mpi comm,  we know the number of entities in the range. And,  for example with fsi app, we called this function many times.

**Comment by prudhomm** [comment]
ok thanks.
