### ISSUE TITLE
For a minimum/basic built of the library.

### ISSUE THREAD

**Issue by issabass** [feelpp/feelpp#1469]
Hello TeamFEEL++,
Can one learn just the basic core of the feelpp library, without external packages or optimized libraries? I mean, is there any way to build the library without PETSc's dependency?
Also, after installing PETSc, SLEPC and the other packages, I've tried to build the library using cmake but there are several empty sub-directories, and i fed them with do-nothing cmake files in order to get rid of the warnings but I failed to build the library.
Any hint to build just the core of the library, I am not looking for performance nor optimized version, just to learn the design and implementation of the basic tools.
Thank you much,
zaq

**Comment by prudhomm** [comment]
@issabass how about download the debian/ubuntu package or Docker to investigate what you can do with Feel++ ? the library is available on debian/buster and ubuntu/focal(20.04 lts) and also in docker containers. As to a minimal build it is possible but we are under heavy load these days and this is not our priority currently
