### ISSUE TITLE
SER fails in parallel

### ISSUE THREAD

**Issue by romainhild** [feelpp/feelpp#1476]
In parallel, SER stops after one iteration, resulting in reduced basis with only one element.
This does not happen in sequential.

**Comment by prudhomm** [comment]
does it crash ? what is the error message if any ? what is the testcase ? how to reproduce this ?

**Comment by romainhild** [comment]
No it does not crash, it simply ends the algorithm as if the tolerance is reached, as soon as the EIM is initialized with one base in the initModel method, and one reduced basis is added.

To reproduce, in the branch crb-thermoelectric:
```
mpirun -np 2 feelpp_mor_thermoelectric-nonlinear-app --config-file crb-thermoelectric-nonlinear/quarterturn.cfg --ser.rb-frequency 1 --ser.eim-frequency 1
```
It will run the thermoelectric reduced model with SER.

**Comment by romainhild** [comment]
Ok it was indeed a problem in my config file. It works fine now.
