### ISSUE TITLE
Crash field split rigid solid 

### ISSUE THREAD

**Issue by lberti** [feelpp/feelpp#1484]
Using the field split preconditioning strategy produces a crash in the code. I will attach the two cfg files to reproduce the results. 
The _LU.cfg file should be the working one (sequential and parallel), the _FS1.cfg is not working for me, nor in sequential nor parallel. 

[fluid.ModelAlgebraicFactory(0)] : [linearSolver] : finish assembling in 12.6026 s
*** Aborted at 1592923982 (unix time) try "date -d @1592923982" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGSEGV (@0x8) received by PID 23122 (TID 0x7f10d5bdd500) from PID 8; stack trace: ***
    @     0x7f1072f77390 (unknown)
    @     0x7f109c44f483 Feel::IndexSplit::applyFieldsDef()
    @     0x7f109c642df6 Feel::PreconditionerPetsc<>::init()
    @     0x7f109c5f34b3 __feel_petsc_preconditioner_setup
    @     0x7f107676602d PCSetUp_Shell
    @     0x7f107681d2d1 PCSetUp
    @     0x7f10768c9e75 KSPSetUp
    @     0x7f10768cab1e KSPSolve
    @     0x7f109c5f6993 Feel::SolverLinearPetsc<>::solve()
    @     0x7f109c66595b Feel::BackendPetsc<>::solve()
    @     0x7f109ea16944 Feel::Backend<>::boost_param_default_1070solve<>()
    @     0x7f109ea15657 Feel::Backend<>::boost_param_default_1070solve<>()
    @     0x7f109ea15455 Feel::Backend<>::boost_param_default_1070solve<>()
    @     0x7f109ea15228 Feel::Backend<>::boost_param_default_1070solve<>()
    @     0x7f109ea14ff7 Feel::Backend<>::boost_param_default_1070solve<>()
    @     0x7f109ea14da3 Feel::Backend<>::boost_param_default_1070solve<>()
    @     0x7f109ea14bc8 Feel::Backend<>::boost_param_default_1070solve<>()
    @     0x7f109ea1467f Feel::Backend<>::boost_param_default_1070solve<>()
    @     0x7f109ea14124 Feel::Backend<>::boost_param_default_1070solve<>()
    @     0x7f109ea13fad Feel::Backend<>::boost_param_default_1070solve<>()
    @     0x7f109ea13d71 Feel::Backend<>::boost_param_implsolve<>()
    @     0x7f109e9e8f32 Feel::FeelModels::ModelAlgebraicFactory::solveLinear()
    @     0x7f10b78df4e1 Feel::FeelModels::FluidMechanics<>::solve()
    @           0x41e35a Feel::runApplicationFluid<>()
    @           0x416008 main
    @     0x7f106f126830 __libc_start_main
    @           0x415989 _start
    @                0x0 (unknown)
Erreur de segmentation (core dumped)

**Comment by prudhomm** [comment]
it is from the branch`toolbox_refactoring` of course
