### ISSUE TITLE
Bug(deadlock) in Mesh construction in parallel when working on sub communicator

### ISSUE THREAD

**Issue by prudhomm** [feelpp/feelpp#1505]
there is a deadlock in communications when working in // on a sub communicators.

To reproduce:
- create a split of n-p processors and get the corresponding communicator
- create a Mesh and pass this communicator
- when the number of processors in the sub communicator is > 1 then  `Mesh::updateForUse()` is stuck

/cc @vincentchabannes

**Comment by prudhomm** [comment]
I found the issue thanks to gdb and debugging in //:  two collectives operations (all_gather and all_reduce) were done on the wrong communicator (the global one with all processes instead of the local one with the subset of processes) 
/cc @vincentchabannes

**Comment by vincentchabannes** [comment]
strange, it will the case in `testsuite/feeldiscr/test_twolaplaciansdistributed.cpp`. Maybe look here, if I remember, you need to pass the worldcomm  in the mesh constructor (and also on the backend)

**Comment by prudhomm** [comment]
Actually I think I understand what is going on. I will check the example but I suspect that the example does the same thing on each communicator, no? whereas in this case it is not. For example if I have 2 processes, I split and get one process to do some work, the resulting function space build 0 dof. Looking at the code, it seems quite normal it doesn't work properly sometimes comms or logic are done at global sometimes at local communicator level whereas they should be done only at the local communicator level(at least in the context of the asdymetric test above ) . The mesh seems ok.
I will add these tests to the testsuite
