### ISSUE TITLE
Add range-v3 to feelpp contrib

### ISSUE THREAD

**Issue by prudhomm** [feelpp/feelpp#1507]
range-v3 is the basis for std::range in c++20.
in the last release 0.11 range-v3 (which is C++11/14 and 17 compliant) got closer to the C++20 standard.

see https://github.com/feelpp/range-v3 for more details

see https://en.cppreference.com/w/cpp/header/ranges for more details about std::ranges in the c++20 standard

range-v3 will be available as a submodule

**Comment by romainhild** [comment]
is it used somewhere ? Should I use that or deal with `iota` now ?

**Comment by prudhomm** [comment]
It is used yes

**Comment by prudhomm** [comment]
You can use it of course

**Comment by romainhild** [comment]
Ok I'll take a look to see if I can replace some code
