### ISSUE TITLE
Compilation time evaluation

### ISSUE THREAD

**Issue by prudhomm** [feelpp/feelpp#1529]
We have a severe issue with compilation time, we need to understand the various factors that are associated with the build times.
First we need to benchmark some code and typical behavior
- [ ] check header inclusion cost

- [ ] check template instantiation

**Comment by prudhomm** [comment]
here are some data about header inclusion cost

test | Preprocessing (s) | Compilation & Linking (s)
----|-------------------|--------------------------
feel1         | 115 | 140
feelcore   | 9 | 18
feelpoly   | 8 | 21
feeldiscr  | 75 | 90 
feelvf       | 52 | 78

@vincentchabannes header inclusion has a cost, we should be more careful/mindful about what we include

Note that feel1 is the inclusion of almost all feelpp headers

**Comment by prudhomm** [comment]
header inclusion preprocessing time is given by :
 ```
for i in feel1 feelcore feeldiscr feelpoly feelvf; do make clean; time make $i.cpp.i; done
```

header compilation and linking time is given by :
```
for i in feelpp_bench_compile_feel1      feelpp_bench_compile_feelcore   feelpp_bench_compile_feeldiscr  feelpp_bench_compile_feelpoly   feelpp_bench_compile_feelvf; do time make $i/fast; done
```

**Comment by vincentchabannes** [comment]
yes, I know but the app is small. My troubles come clearly of the compilation (for example with fluid lib : around 45 minutes of compilation, then 5 minutes for the link, and header inclusion less than 1 minutes)

**Comment by prudhomm** [comment]
we should gather here evidence of the various costs at compile time and see where we should put our efforts

**Comment by prudhomm** [comment]
here is a nice blog on the subject: https://interrupt.memfault.com/blog/improving-compilation-times-c-cpp-projects#optimizing-header-includes-and-dependencies

**Comment by vincentchabannes** [comment]
the problem for me comes from the tensor class of Expr. The compilation time increases tremendously when the expression increase in complexity. I noticed that there more instances than necessary when used in bilinearform (but I don't understand why).

**Comment by prudhomm** [comment]
we will have look definitely at all this.

**Comment by prudhomm** [comment]
@vincentchabannes in the previouscommit. I added metabench which allows to test the scalability of template instantiation. it works quite nicely
