### ISSUE TITLE
FsFunctionalLinear gives different results in sequential and in parallel

### ISSUE THREAD

**Issue by romainhild** [feelpp/feelpp#1555]
Applying a FsFunctionalLinear with the operator() gives different results in sequential and in parallel.
For example, the code
```
        auto vv = ex.evaluate({{"x", n(0)}, {"y", n(1)}})(0,0);
        auto v = (*f)(u);
        BOOST_CHECK_CLOSE(v, vv, 1 );
```
pass in sequential but not in parallel because `v` is not the same.

**Comment by romainhild** [comment]
This is needed for the sensors and PBDW.

**Comment by prudhomm** [comment]
@romainhild could you make it a template testcase with respect to the dimension to check also dim=3 ?

**Comment by prudhomm** [comment]
Actually boost test has a nice feature to deal with templates. It would be a tad less verbose

**Comment by prudhomm** [comment]
@romainhild what are the results in sequential and in parallel ?

**Comment by romainhild** [comment]
I understood the problem, I need to enforce the mesh used for the tests.

**Comment by romainhild** [comment]
In fact the issue comes from the `dot` function of the functional, https://github.com/feelpp/feelpp/blob/44cb184985b278e4e025189b4be3928726a38c51/feelpp/feel/feeldiscr/fsfunctionallinear.hpp#L91

Replacing it by `inner_product` solves the issue.
