### ISSUE TITLE
Compilation can fail due to conflicts between the embedded `Eigen` library and the system one (needed by eg VTK)

### ISSUE THREAD

**Issue by metivett** [feelpp/feelpp#1593]
When compiling with a system-wide install of `eigen3`, the version of `eigen` embedded in `feel++` can conflict with the system one, in particular at include resolution. This situation appears in particular when compiling with VTK support, which has usually been built with the system `eigen`, and brings this include dependency along.
Possible solutions could be to un-embed `eigen` from Feel, or to embed all the libraries which require `eigen` and ensure they are compiled with the same `eigen` version (this latter option being possibly cumbersome in the case of VTK, which is slow to compile).

**Comment by prudhomm** [comment]
I haven't tried with VTK recently, probably a careful set of `#include` should do it to avoid the conflict. I will check on this.
which system are you using ? which version of VTK ?
I assume that you are using the system VTK and eigen, right ?

**Comment by metivett** [comment]
I have tested on MacOs (Catalina), with VTK 8.2.0 and system Eigen3 (3.3.9). The conflict in my case came from VTK bringing its `eigen3/unsupported/Eigen/...` includes, which in the case of the latest release (3.3.9) conflict with the `HEAD` branch from `https://gitlab.com/libeigen/eigen` which is used by embedded `FetchContent` of `eigen` in `Feel`.
The issue came in particular from using `VTK_INCLUDE_DIRS` in all further Feel includes.

**Comment by vincentchabannes** [comment]
@metivett Strange, I have tested that a few ago, I don't have any issue. You can see the portfiles of feel++, I compile paraview (and so vtk) with eigen take from system and then I compile feel++ with eigen contrib.
However, I added (some time ago) the possibility to use eigen from system install (-DFEELPP_ENABLE_SYSTEM_EIGEN3=ON) but I don't know if it's always supported, I hope that the answer is yes because it's very useful to test last eigen version.

**Comment by prudhomm** [comment]
There is a big difference between eigen release 3.39 if i recall and the development version in particular in the tensor class development.

**Comment by metivett** [comment]
Indeed, that's what breaks compilation in this case. But anyhow, even if the API would be the same, it is dangerous to mix includes from different libraries...

**Comment by metivett** [comment]
Just a small "up": `-DFEELPP_ENABLE_SYSTEM_EIGEN3=ON` does not seem to work. For the moment, the only reliable workaround is to disable VTK (`-DFEELPP_ENABLE_VTK=OFF`).
After some attempts at fixing this issue, I think the dependency system should definitely be reworked.
