### ISSUE TITLE
Add keywords for Dirichlet bc on specific component of a vector field

### ISSUE THREAD

**Issue by Trophime** [feelpp/feelpp#1602]
Would it be possible to add keywords to impose Dirichlet Boundary condition
on a given component of a vector field in the toolboxes?

**Comment by prudhomm** [comment]
on general geometries it may be non trivial

what you can do is implement that weakly with nitsche
it would interesting to test if cfpdes can handle Nitsche formulation

**Comment by vincentchabannes** [comment]
cfpdes toolbox implements component Dirichlet thanks to 9658a3cf21b6793cc69691389961b8aa2a6924f0 .
fluid and solid toolbox have already this feature
