### ISSUE TITLE
Compilation lamina-cribrosa-model_3DP1 for case Tissue perfusion not compiling

### ISSUE THREAD

**Issue by thomas-saigre** [feelpp/feelpp#1605]
When I try to build the targets in `doc/manual/hdg` (especially the case `lamina-cribrosa-model_3DP1`), it gives errors :
```c++
In file included from /ssd/saigre/feelpp/doc/manual/hdg/lc_main_model.cpp:25:
In file included from /ssd/saigre/feelpp/doc/manual/hdg/lc_model.hpp:29:
In file included from /ssd/saigre/feelpp/toolboxes/feel/feelmodels/hdg/mixedpoisson.hpp:17:
In file included from /ssd/saigre/feelpp/toolboxes/feel/feelmodels/modelcore/modelnumerical.hpp:36:
In file included from /ssd/saigre/feelpp/toolboxes/feel/feelmodels/modelcore/modelalgebraic.hpp:33:
/ssd/saigre/feelpp/toolboxes/feel/feelmodels/modelcore/modelbase.hpp:39:10: fatal error: 
      'feel/feelmodels/modelcore/feelmodelscoreconstconfig.hpp' file not found
#include <feel/feelmodels/modelcore/feelmodelscoreconstconfig.hpp>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```
The full error message (1930 lignes long !) is accessible here : https://pastebin.com/BdBaS8s6

**Comment by prudhomm** [comment]
it is now forbidden to use `include_directories`, `target_include_directories` should be used instead. 
however this is strange that it happens. Probably a (low-level) header is included in this app and it should not.
Otherwise we would have had a lot of applications failing to compile

**Comment by thomas-saigre** [comment]
it seems that when the application run, the program in the function `export` doesn't go through the [`for` loop ](https://github.com/feelpp/feelpp/blob/thomas-saigre/issue1605/doc/manual/hdg/lc_model.hpp#L580), maybe `this->modelProperties().postProcess().exports().fields()` gives an empty object

**Comment by romainhild** [comment]
Yes certainly that the json is not correct
https://github.com/feelpp/feelpp/blob/c58ffacd470d9c841ab60817c03b64d898ff3867/doc/manual/hdg/lamina-cribrosa/test3d0d.json#L115-L118
It should be something like:
https://github.com/feelpp/feelpp/blob/ac4c8661ecf1a4e545faa7a7ca04c00e9764c3f6/toolboxes/electric/ElectroMagnets/HL-31_H1/HL-31_H1.json#L29-L34
