### ISSUE TITLE
Problem docker image : feelpp/feelpp-toolboxes:stable

### ISSUE THREAD

**Issue by ValletRomain** [feelpp/feelpp#1620]
@prudhomm , @vincentchabannes 
The image `feelpp/feelpp-toolboxes:stable` do reference to `https://dl.bintray.com/feelpp/ubuntu focal stable` (see file `/etc/apt/sources.list` in docker `feelpp/feelpp-toolboxes:stable`) but must do reference to `deb https://feelpp.jfrog.io/artifactory/ubuntu focal latest`.

**Comment by prudhomm** [comment]
Are you using stable?

**Comment by ValletRomain** [comment]
Yes, for my repo 2020-m2-lncmi

**Comment by prudhomm** [comment]
stable won't be available for some time. I have to update the scripts for 108(current stable) and rebuild the packages

/Cc @Trophime
