### ISSUE TITLE
linear test case for coupled poisson is not working

### ISSUE THREAD

**Issue by thomas-saigre** [feelpp/feelpp#1621]
I implemented a linear test case to test the application `feelpp_toolbox_hdg_coupled_poisson`, with the exact solution `p(t,x,y,z)=a+b*x*t` where the error should be 0.
![image](https://user-images.githubusercontent.com/60920471/119981360-d482d400-bfbd-11eb-929c-5a119454fdea.png)
As we can see in this screen shot, this is not the case, and the error stay the same with smaller time-step or hsize.

**Comment by prudhomm** [comment]
@thomas-saigre @romainhild it should be closed no ?
