### ISSUE TITLE
Add a keyword for getting curl of a field in cfpdes

### ISSUE THREAD

**Issue by Trophime** [feelpp/feelpp#1643]
It will be great to have access to a keyword for accessing the curl of a field in cfpdes
especially for Maxwell equations.

**Comment by vincentchabannes** [comment]
@Trophime It's already implemented : 
*  <eqname>_curl_<u>  in 2d 
* <eqname>_curl_<u>_0, <eqname>_curl_<u>_1, <eqname>_curl_<u>_2  in 3d 

This information should be available in the .adoc output

**Comment by romainhild** [comment]
there is no `curl` in 3D ? which is also a vector

**Comment by vincentchabannes** [comment]
yes, it's what I wrote.

**Comment by romainhild** [comment]
you wrote `curl` only in 2D.

**Comment by vincentchabannes** [comment]
where?

**Comment by romainhild** [comment]
> @Trophime It's already implemented :
> 
> * `<eqname>_curl_<u>`  in 2d.   <------ HERE
> * `<eqname>_curl_<u>_0`, `<eqname>_curl_<u>_1`, `<eqname>_curl_<u>_2`  in 3d
> 
> The div is also implemented since yesterday.
> 
> This information should be available in the .adoc output

**Comment by vincentchabannes** [comment]
and the second item is the 3d vector (don't forget that a symbol can be only scalar)

**Comment by romainhild** [comment]
ahh ok so indeed there is no `curl` in 3D, only access to each component. I didn't know that it could only be scalar. My bad
