### ISSUE TITLE
Add support for Hcurl in cfpdes

### ISSUE THREAD

**Issue by Trophime** [feelpp/feelpp#1644]
Would it be possible to use cfpdes with a field in Hcurl?

**Comment by vincentchabannes** [comment]
There is a basic example somewhere? it should be possible but I am not an expert of Hcurl

**Comment by Trophime** [comment]
The basic example is the magnetostatic equation (see in Hifimagnet): 
rot(1/mu rot a) = j in R^3 with support(j)=\Omega

But to start with, I just need to solve the same kind of pde that the one in cfpdes but with a field that is in Hcurl.

**Comment by prudhomm** [comment]
should it be closed ? @vincentchabannes @Trophime
