### ISSUE TITLE
Dirichlet_X doesn't work

### ISSUE THREAD

**Issue by ValletRomain** [feelpp/feelpp#1645]
Hello @prudhomm @vincentchabannes ,
I test the command `Dirichlet_X` on feelpp version `0.109.0-rc.10` but it doesn't works.

I solve the laplacian problem :
    Delta u = {0,0}, u={ux,uy} in Omega with Omega a Square
    u={0,1} on Bound
i obtain u={0,0} on `Omega` but I must obtain u={0,1}.

The file are here https://github.com/master-csmi/2020-m2-lncmi/tree/little_test/Test

**Comment by Trophime** [comment]
For sake of clarity, I've renamed the tests:
* test-dirichlet with Dirichlet BC on the whole boundary for vector field unknown (working)
* test-dirichletX with Dirichlet BC .... for X and Y components (separately)  of the vector field (not working)

and I've added checkers (verifiy solution at a given point)

**Comment by vincentchabannes** [comment]
@ValletRomain @Trophime By bad, it's not Dirichlet_X but Dirichlet_x and idem for other comp  (see 70f6929bfdce6cdc48a8b54b4c077384b31e0c92)
