### ISSUE TITLE
Expressions with math functors have protected default constructor

### ISSUE THREAD

**Issue by romainhild** [feelpp/feelpp#1652]
When using `ExpressionEvaluatorNonLinear` (which are used for the empirical quadrature) with certain type of expressions leads to an error during the compilation.
In particular, using an expression such as `vec(cos(cst(0.)), cos(cst(1.)))` produce the following error:
```
feel/feelvf/expr.hpp:445:9: error: field of type 'Feel::vf::Expr<Feel::vf::__Cos__<Feel::vf::Expr<Feel::vf::Cst<double> > > >::expression_type'
      (aka 'Feel::vf::__Cos__<Feel::vf::Expr<Feel::vf::Cst<double> > >') has protected default constructor
        M_expr()
```
It is worth remarking that the same code with an expression such as `cos(cst(0.))` is not producing the same error, as well as the same code with the vector but with an `ExpressionEvaluatorParam`.
It was compiling fine a while ago, more than a year I think.

I will add a test for this.

**Comment by prudhomm** [comment]
indeed the default constructor for math functions  is protected 
I suggest to move the constructor to the public part

line 362
```c++
  VF_FUNC_NAME(O)() {} 
```
should become
```c++
  VF_FUNC_NAME(O)() =default;
```
and become public

**Comment by romainhild** [comment]
When doing this I have the following error:
```
 error: call to implicitly-deleted default constructor of 'Feel::vf::Expr<Feel::vf::__Cos__<Feel::vf::Expr<Feel::vf::Cst<double> > >
      >::expression_type' (aka 'Feel::vf::__Cos__<Feel::vf::Expr<Feel::vf::Cst<double> > >')
```
