### ISSUE TITLE
Add definitions for _curl_key and Curl spaces on subdomains

### ISSUE THREAD

**Issue by piotaixt** [feelpp/feelpp#1653]
Would it be possible to create a "`_curl_key`" just like _gradient_key in `quickstart laplacian `example? 

Thanks

**Comment by piotaixt** [comment]
Does this kind of line work?
`Vh = Ned1h<Order>( mesh, markedelements(mesh, soption("marker.name") ) );`

**Comment by prudhomm** [comment]
@piotaixt sorry I missed your message and it is too late now

```
Vh = Ned1h<Order>( mesh, markedelements(mesh, soption("marker.name") ) );
```
it won't but it is easy to fix.
