### ISSUE TITLE
Missing libfeelpp_parmmg.so from Ubuntu focal latest package

### ISSUE THREAD

**Issue by Trophime** [feelpp/feelpp#1661]
Trying to use latest debian package in focal:
```
feelpp_mesh_partitioner --version
feelpp_mesh_partitioner: error while loading shared libraries: libfeelpp_parmmg.so: cannot open shared object file: No such file or directory
```
There is no package providing  libfeelpp_parmmg.so :(

**Comment by prudhomm** [comment]
ok will fix that asap
it will come with libfeelpp1

**Comment by prudhomm** [comment]
with this has been fixed with https://github.com/feelpp/ParMmg/commit/6f0a962035574a1f2c14225254672b0a9f93ce94
idem for matplot
