### ISSUE TITLE
Sampling [log-]randomly

### ISSUE THREAD

**Issue by thomas-saigre** [feelpp/feelpp#1675]
To get a sample for a problem, I created a function
```python
def listOfParams(n):
    mus = []
    for _ in range(n):
        mus.append(Dmu.element(True, True))    # the second True stand for 'log-random'
    return mus
```
(maybe there already exists a function generating such a sampling)

For a problem where there is only 1 parameter living in _[0.1, 10]_ I created two samples, one with the _log-random_ option, and another without.

Here is what I get when I try to compare the two samples :
![image](https://user-images.githubusercontent.com/60920471/127656652-ada572de-08dd-4cea-b166-5cd28ae915cc.png)
and in log-scale :
![image](https://user-images.githubusercontent.com/60920471/127656711-fb2dc5e8-b54f-4acc-9465-0a69f98468c1.png)
When I run the greedy algorithm on a more complex case where parameters have a range with many orders of magnitude, there is no significant difference between the results given by the log-random generated sample and the other one.

The discussion is about how samples are generated.

**Comment by prudhomm** [comment]
@thomas-saigre is there still an issue with this?

you tested only on a simple example which does not necessarily show the importance of the sampling

**Comment by thomas-saigre** [comment]
I do not remember why I added this issue, maybe it was after a discussion we had... It seemed that there was no difference between a log-random generated and a no-log-random one. I'll try on a more complex case (eg the eye when it will be working) to see

**Comment by prudhomm** [comment]
@thomas-saigre any news on this ?

**Comment by thomas-saigre** [comment]
I think this issue can be closed : when I used it, I wasn't aware of the `sampling` doing it,  before to generate a list of parameters, I did a for loopp
```python
for _ in range(n):
    mus.append(Dmu.element(True, True))    # the second True stand for 'log-random'
```
while the usage of sampling do it, with a selected repartition :
```python
s = Dmu.sampling()
s.sampling(N, samplingMode)
mus = s.getVector()
```
