### ISSUE TITLE
use pointsetfekete by default in FunctionSpace

### ISSUE THREAD

**Issue by prudhomm** [feelpp/feelpp#1683]
Pointsetequispaced is used currently by default, PointSetFekete is the same as PoinSetEquiSpaced for low order but provides better lebesgue constant for higher order. 

Part of #1494

**Comment by vincentchabannes** [comment]
@prudhomm I think we need to apply another strategy. Because for example, PointSetFekete is only for 2d simplex.
We can define PointSetOptimized and switch between the context. As https://github.com/feelpp/feelpp/blob/develop/feelpp/feel/feelpoly/fekete.hpp#L1248-L1264.

We can also say that Pch<1, PoinSetEquiSpaced> ==   Pch<1, PointSetFekete> == Pch<1,PointSetOptimized>

**Comment by prudhomm** [comment]
This is indeed needs to be checked and refactor a tad. Also on hypercube the equivalent of fekete is gausslobatto 
Anyway I checked that everything compiles properly and it does. I will have the results of the testsuite and toolboxes

**Comment by prudhomm** [comment]
@vincentchabannes for high order (>= 4) we have a problem with FeketePoints `TestSMD` in test_operatorinterpolation fails, it cannot find matching dof

```
double dofPtCompareTol = std::max( 1e-15, imageElt.hMin() * 1e-5 );
auto const& imageGlobDofPt = M_XhImage->dof()->dofPoint( imageGlobDof ).template get<0>();
bool find = false;
size_type thelocDofToFind = invalid_v<size_type>;
 for ( uint16_type jloc = 0; jloc < image_fe_changedim_type::nLocalDof; ++jloc )
{
                auto const& domainGlobDofPt = M_gmc->xReal( jloc );
                bool find2 = true;
                for ( uint16_type d = 0; d < DomainSpaceType::nRealDim; ++d )
                {
                    find2 = find2 && ( std::abs( imageGlobDofPt[d] - domainGlobDofPt[d] ) < dofPtCompareTol );
                }
                if ( find2 )
                {
                    thelocDofToFind = jloc;
                    find = true;
                    break;
                }
}
CHECK( find ) << "[OperatorInterpolation::update] Compatible dof not found";
return image_fe_changedim_type::nLocalDof * comp + thelocDofToFind;
```
it fails on the CHECK

**Comment by prudhomm** [comment]
the code looks like:
```
BOOST_TEST_MESSAGE( "start test SMD " << Dim << "d Geo" << OrderGeo );
    auto mesh = buildMeshSMD<OrderGeo>( mpl::int_<Dim>() );
    BOOST_TEST_MESSAGE( "mesh done" );
    auto submesh = createSubmesh( _mesh=mesh, _range=markedfaces( mesh, "BoundaryInterp" ) );
    BOOST_TEST_MESSAGE( "submesh done" );
    auto Xh1 = Pch<3 /*,PointSetFekete*/>( mesh );
    BOOST_TEST_MESSAGE( "spaces Xh1 done" );
    auto Xh2 = Pch<5 /*,PointSetFekete*/>( submesh );
    BOOST_TEST_MESSAGE( "spaces Xh2 done" );
    auto u1 = Xh1->element();
    auto u2 = Xh2->element();

    auto thedispexpr = Px() * ( 5.0 - Px() ) * 0.1; //*oneY();
    //auto thedispexpr = Px();//*(5.0-Px())*0.1;//*oneY();
    auto u1Base = vf::project( _space = Xh1, _expr = thedispexpr );
    auto u2Base = vf::project( _space = Xh2, _expr = thedispexpr );
#if 1
    //-------------------------------------------------------------------------------------//
    auto opIa = opInterpolation( _domainSpace = Xh2,
                                 _imageSpace = Xh1,
                                 _range = markedfaces( mesh, "BoundaryInterp" ) );
    opIa->apply( u2Base, u1 );
```

**Comment by prudhomm** [comment]
perhaps a problem in the permutation ?

**Comment by vincentchabannes** [comment]
In fact, we didn't not use permutation here (in this case of operatorinterpolation ). We guess that we can find have dof points (defined over a surface (nDim != nRealDim)) with dof points (associated to a face) on the volume.
 `typedef typename image_fe_type::template ChangeDim<fe_type::nDim>::type image_fe_changedim_type;`
I think also Fekete is only implemented in 2d.

**Comment by prudhomm** [comment]
we use warpblend in 3D but it should work as well, I will check in 2D and 3D.

**Comment by vincentchabannes** [comment]
fekete is only implement in 2d, no? see [here](https://github.com/feelpp/feelpp/blob/develop/feelpp/feel/feelpoly/fekete.hpp#L141-L148).

And with this line `typedef typename image_fe_type::template ChangeDim<fe_type::nDim>::type image_fe_changedim_type;` we can use fekete in 1d and 3d also. 

Anyway, this code is not very nice, it needs to be rethought
