### ISSUE TITLE
FTBS of mor and testsuite with boost 1.71

### ISSUE THREAD

**Issue by prudhomm** [feelpp/feelpp#1697]
the components mor and and testsuite are failing to build with boost >= 1.71 and clang.
this may be due to the interaction of boost::bimap with some boost headers.
see #1473  and #1474 as an attempt to fix this.

**Comment by prudhomm** [comment]
@Trophime @vincentchabannes I revert the deb depends on boost back to 1.67 until feelpp builds properly with boost 1.71

**Comment by romainhild** [comment]
Is it fixed now with #1724 ?

**Comment by prudhomm** [comment]
Yes
