### ISSUE TITLE
Initialization before time-initial on CFPDES

### ISSUE THREAD

**Issue by ValletRomain** [feelpp/feelpp#1718]
I want to initialize my unknow before the time-initial on toolboxe CFPDES. I follow the documentation book.feelpp.org on romainhild-patch-1 branch ( https://github.com/feelpp/book.feelpp.org/blob/romainhild-patch-1/docs/toolboxes/modules/ROOT/pages/modeling-analysis-using-json-files.adoc ) @romainhild.

I write : 
```
  "InitialConditions":
  {
      "u":{
          "Expression": {
              "myic1": {
                  "markers": "Omega",
                  "expr":"{exp(t+x+y),exp(t+x+y)}:x:y:t"
              },
              "myic2": {
                  "expr":0,
                  "time":-0.5
              }
          }
      }
}
```

But, I have this error message : 
```
F1102 15:55:04.479907 184440 modelnumerical.hpp:351] Check failed: icts.size() == 1 TODO
```

**Comment by romainhild** [comment]
You have to wait for #1715 to be merged before using this.
