### ISSUE TITLE
nonzero error in P2P1 with 3D Poiseuille flow with fluid toolbox

### ISSUE THREAD

**Issue by PhilippeRicka** [feelpp/feelpp#1727]
3D Poiseuille testcase does not yield zero machine error in P2P1

See case [cfg](https://github.com/feelpp/feelpp/blob/945fb9a7bdc9214e83a98fdf9a6ca4976db427b1/toolboxes/fluid/cases/pressure-driven/pipe/pipe-3d.cfg)

**Comment by romainhild** [comment]
This is due to the curved geometry and high order elements.
The fix is to use the exact expression on the boundary instead of what it should be on the real geometry, or to use higher order geometry.
