### ISSUE TITLE
Gmsh refine by splitting is buggy in 3D

### ISSUE THREAD

**Issue by prudhomm** [feelpp/feelpp#175]
@feelpp/feelpp It seems that Gmsh refine by splitting procedure  is buggy in 3D (in 2D all is fine). When conducting convergence analysis in 3D, optimal convergence is not reached using element splitting. Everything is fine by just re-generating a mesh with a halved mesh characteristic size.

**Comment by prj-** [comment]
Do you know if this bug is fixed in Gmsh 2.9.x ?

**Comment by prudhomm** [comment]
will check the new release
