### ISSUE TITLE
time setters have no effect in cfpdes

### ISSUE THREAD

**Issue by prudhomm** [feelpp/feelpp#1763]
cfpde uses ModelNumerical as a base class which deal with time discretisation and allow to set/get time related parameters eg `setTimeFinal(double)`
However the latter has no effect on the BDF stepper if that's the one used.
it seems that the ModelNumerical class is created in the init() call and hence take the default command line option rather than the cfpdes configuration 
it is then not possible to control time stepping for the python testsuite

Note that the other toolbox are fine and setting the final time automatically to eg 10 time steps works fine

**Comment by prudhomm** [comment]
here is the code
```python
@pytest.mark.parametrize("prefix,case,casefile,dim", cfpde_cases)
def test_cfpdes(prefix,case,casefile,dim):
    feelpp.Environment.setConfigFile('cfpdes/{}/{}/{}'.format(prefix,case,casefile))
    f = cfpdes(dim=dim)
    if not f.isStationary():
        f.setTimeFinal( f.timeStep()*10) # <-- no effect at all
        
    simulate(f)
    return not f.checkResults()
```

for heat
```python
@pytest.mark.parametrize("casefile,dim,order", heat_cases)
def test_heat(casefile,dim,order):
    feelpp.Environment.setConfigFile(casefile)
    f = heat(dim=dim, order=order)
    if not f.isStationary():
        f.setTimeFinal(10*f.timeStep()) # works great
    simulate(f)
```

**Comment by vincentchabannes** [comment]
yes, I know. It is probably also the case with multiphysics toolboxes. I have planned to implement a brick to manage Transient model in order to share time step information over toolboxes (this is in roadmap).
