### ISSUE TITLE
Implementation collision forces for moving rigid bodies in fluids

### ISSUE THREAD

**Issue by prudhomm** [feelpp/feelpp#1836]
Collision forces are necessary to avoid contact between moving objects in fluids
they can be implemented as a plugin for the fluid toolbox

**Comment by prudhomm** [comment]
@VLCeline is the code up to date ?

**Comment by prudhomm** [comment]
In other words could we review the PR,?

**Comment by VLCeline** [comment]
@prudhomm No, the code is not up to date. I will review the new version of the code on Monday and push it then.
