### ISSUE TITLE
Cleanup and organize testcases on  bodies moving in fluids

### ISSUE THREAD

**Issue by prudhomm** [feelpp/feelpp#1839]
There are too many testcases on moving body motion. We should keep the ones that allow to check properly (norms measures ...)  the toolbox features

**Comment by prudhomm** [comment]
other testcases should go in feelpp/toolboxes or feelpp/swimmer. Probably the later.

**Comment by lberti** [comment]
The testcases that are being merged from the `rb_testcase` branch to develop are already in `feelpp/swimmer`. Do I have to attach the csv of the two cases that we verified to the pull request? Do I have to copy all the cases to feelpp/swimmer?

**Comment by prudhomm** [comment]
fixes #1839
