### ISSUE TITLE
Test case for distanceToRange function

### ISSUE THREAD

**Issue by VLCeline** [feelpp/feelpp#1847]
After noticing some issues with the `distanceToRange` function, I made a test case to check if it was working right. 
I consider as geometry three circles with the same center and different radii. I use the function `distanceToRange` to compute the distance to the boundary of the small circle and then I use the narrow-band option whose default value should be used starting from the boundary of the second circle. 

When I run this script sequentially, with the command line `./feelpp_qs_distanceCeline`, I get the right results : 

<img width="1360" alt="Sequential_distToCircle1" src="https://user-images.githubusercontent.com/77676706/166235463-f575564f-8b71-4084-9454-b16e6b4c9897.png">

And with narrow-band : 

<img width="1360" alt="Sequential_distToCircle1_NarrowBand" src="https://user-images.githubusercontent.com/77676706/166235547-b8311c26-ac35-46ac-9889-5389fb0d4c10.png">

However, when I run it in parallel, with 4 or more processors : `mpirun -np 4 feelpp_qs_distanceCeline`,
one can observe a problem in the visualization of the function :

<img width="1360" alt="Parallel_distToCircle1" src="https://user-images.githubusercontent.com/77676706/166235614-13735152-99f7-4256-86bb-34eedc559376.png">

With narrow-band:

<img width="1360" alt="Parallel_distToCircle1_NarrowBand" src="https://user-images.githubusercontent.com/77676706/166235655-a02b1d59-f426-4484-b791-933747a3aa5e.png">

I added the geo file, `2D.geo` , and the cpp file, `test.cpp` , used for this test case:

[Test case.zip](https://github.com/feelpp/feelpp/files/8602920/Test.case.zip)

**Comment by vincentchabannes** [comment]
@metivett I have the same issue. it's localized at interprocess element. I didn't see that before, maybe the bug appears with last changes with narrow distance feature

**Comment by prudhomm** [comment]
@VLCeline it would be nice to 

1. add the test to `testsuite/feells`
2. use boost test
3. add checks (using boost.test) to verify that expected quantities (eg errors) are computed properly

**Comment by vincentchabannes** [comment]
Indeed, by default, the doftable is not defined for the ghost dof. And we can probably add these informations (dof on ghosts elt which touch the interprocess zone by a point/edge/faces). You can fill an issue if you want.

An option allows building an extended dof table that includes all ghost cells touching the interprocess zone by a face (only face, not only point or edge). The drawback here is that includes more degree of freedom locally i.e. nLocalDofWithGhost ( and requires more mpi comm when we synchronize parallel vectors for example).

The question : should be use by default (or even always) the dof table extended?  I've been thinking about it for a while but I don't know yet. This could simplify things and maybe the extra cost is perhaps negligible.

**Comment by metivett** [comment]
Ok, that's still weird this issue has never been encountered before, but...
Anyway, I fixed the `distancetorange` initialization in [9df7f0a](https://github.com/feelpp/feelpp/commit/9df7f0a17dd6f00537fee6172f296bf2b632e4bf); @VLCeline have you tested yet ?

**Comment by VLCeline** [comment]
Hello @metivett, I just tested it. It works well now in parallel. When using four or eight processors I get the same results as in sequential: 

<img width="1360" alt="DistanceToRange_parallel" src="https://user-images.githubusercontent.com/77676706/166907447-9b006128-cc4a-4734-9d8e-f7925bf6997d.png">

And with narrow-band:  
<img width="1360" alt="DistanceToRange_narrowBand_parallel" src="https://user-images.githubusercontent.com/77676706/166907496-d3535219-664d-486e-b03c-1051bc47692a.png">
