### ISSUE TITLE
Improve remesh control over boundary representation

### ISSUE THREAD

**Issue by vincentchabannes** [feelpp/feelpp#1871]
I don't know if it's a bug or bad use of the remesher. My issue is based on a mesh that contains a surface not straight (for example a domain perforated by a disk. When I apply remeshing, the initial disk discretization is lost and so the interpolation operator failed. The only solution that I found is to use required marker, but this surface is not remeshed. Any hints? @prudhomm

**Comment by prudhomm** [comment]
you want to unrefine or refine ?

**Comment by vincentchabannes** [comment]
both (and particularly refine ) but maybe this is not possible (split the edges on the boundary).

**Comment by prudhomm** [comment]
I  am writing an example with options to deal with this. To get refinement or unrefinement, we need to tune a parameter to control the boundary approximation

**Comment by prudhomm** [comment]
Here are the two testcases I am using 

### 3D case
<img width="789" alt="Screenshot 2022-05-25 at 08 18 47" src="https://user-images.githubusercontent.com/151693/170193402-ef9bbf92-01a2-4dc7-8f04-8a758b367aa9.png">

### 2D case
<img width="762" alt="Screenshot 2022-05-25 at 08 19 34" src="https://user-images.githubusercontent.com/151693/170193530-fbf1a8dd-cac0-4b89-9683-32e853912f2d.png">
