### ISSUE TITLE
upMasterRank() should be deprecated

### ISSUE THREAD

**Issue by prudhomm** [feelpp/feelpp#1874]
WorldComm::upMasterRank() marked deprecated in WorldComm but used nevertheless in WorldComm.
@vincentchabannes shouldn't we unmark or remove the use of this member function ?
it generates a bit of deprecation messages

**Comment by prudhomm** [comment]
@vincentchabannes any idea ?

**Comment by vincentchabannes** [comment]
you can unmark the deprecated flag until this class is reviewed.

**Comment by prudhomm** [comment]
ok I will do that and keep this issue open
