### ISSUE TITLE
Reduced Basis: Wrong output computation in online step

### ISSUE THREAD

**Issue by alixkien** [feelpp/feelpp#1888]
I work in the `feature/pyrb` branch.
I try to use the Python script to generate reduced basis with the Toolbox Mor (in `feelpp / python / pyfeelpp-mor` folder), with the Greedy algorithm ( class `reducedbasisOffline` in `reducedbasisOffline.py` ).
I have the following warning:
```
[reducedBasis] Greedy, step 1:[0%                                                                        ]
reducedbasis.py:351: RuntimeWarning: invalid value encountered in sqrt
return normHatE / np.sqrt(alp) 
```
The function mentioned is:
https://github.com/feelpp/feelpp/blob/db39f6ef1c7182f6ed6c3ec043265c39e7473abb/python/pyfeelpp-mor/feelpp/mor/reducedbasis/reducedbasis.py#L334-L351
However the algorithm does not stop and so when an output is computed in the online step, the result is totally wrong.
I pushed my testcases (2d and 3d) with the commit 3ae667be63ddd7a109692d7048b5c7d34401867f.

**Comment by prudhomm** [comment]
> The reason of that is becaude eim computes the values if beta for the affine decomposition, it returns negative values, so the energy bound xomputed the min-theta method could not be computed... /cc @prudhomm

@thomas-saigre in that case just compute the dual norm of the residual
Also it may be that there is a bug in the usage of the crb outputs, in c++ it seems to work properly

**Comment by thomas-saigre** [comment]
This has been introduced in 4abfcb132431a5e8eb2b57faf4d98b5ad47e3258 : if we give the argument `compute_lower_bound=True` to the class, the value to be divided by will be one : so the dual norm of the residual is computed.

@alixkien which commands / files did you use to get the error ?

**Comment by prudhomm** [comment]
@alixkien @thomas-saigre does it work now properly ?
