### ISSUE TITLE
Compute ray tracing view factor for RHT

### ISSUE THREAD

**Issue by prudhomm** [feelpp/feelpp#1892]
add view factor computation 

it uses nanoflann #1893 
see also #1806 

/cc @alixkien

**Comment by prudhomm** [comment]
@lberti what is the current status ?

**Comment by lberti** [comment]
@prudhomm I have pushed three tests (run in sequential) where I verify that 

- for a cube, the view factors between parallel faces and perpendicular faces are within 5% of the exact value, in relative error; all rays intersect the cube walls in this test
- for rays launched from the origin towards a circle, the view factor is within 5% of the exact value, in relative error
- for rays launched from parts of a cylindrical mesh, the view factors are within 5% of the exact value, in relative error

**Comment by prudhomm** [comment]
Ok i started a set of classes for ray tracing and unobstructed planar view factor computation. I will propose a first Interface that you can adapt. Then I will add the handling of the rht bc to the app feelpp_doc_rht

/cc @feelpp/rht

**Comment by prudhomm** [comment]
I have renamed the issue to ray tracing view factor as opposed to #1910

**Comment by lberti** [comment]
The development has been merged into develop via the PR #2047
