### ISSUE TITLE
add nanoflann to feelpp

### ISSUE THREAD

**Issue by prudhomm** [feelpp/feelpp#1893]
nanoflann is an efficient modern c++ implementation of kdtree data structure

it should go in `feelpp/feel/feelcore`

**Comment by prudhomm** [comment]
@vincentchabannes this is one header file
how about using it like we do for nl::json?

**Comment by prudhomm** [comment]
also in code we do `<feel/feelcore/nanoflann.hpp>` this should avoid picking the wrong header

**Comment by vincentchabannes** [comment]
This is header only but If another depencies use another version of nanoflann, it can be crash the code. (as Eigen with Gmsh) . For me it's bad idea to put  this feelcore  (idem for nl:json). This is an external lib and we can manage which version is used

**Comment by lberti** [comment]
@prudhomm nanoflann has been added to feelpp. Can we close this issue or it needs further work?

**Comment by lberti** [comment]
Nanoflann has been added to develop via the PR #2047
