### ISSUE TITLE
Add code to solve heat equation as a sandbox for radiative heat transfer

### ISSUE THREAD

**Issue by prudhomm** [feelpp/feelpp#1908]
- [x] add c++ code for heat equation
- [x]  add json spec for heat equation

**Comment by prudhomm** [comment]
@MichelFouquembergh @alixkien the 2D/3D code is there. 
There remains to finish implementing the RHT boundary conditions

**Comment by alixkien** [comment]
- [ ] add json spec for rht: 2d case
- [ ] add json spec for rht: 3d case
- [ ] add general json file for rht

**Comment by lberti** [comment]
80126bf3f03150df6c1a447dffe9a11ead358acc


d0a2a935c4a64f388dde048ebd27074fe700f541
