### ISSUE TITLE
add json spec for radiative heat transfer

### ISSUE THREAD

**Issue by prudhomm** [feelpp/feelpp#1909]
add a json specification for RHT that will be implemented in the heat toolbox

**Comment by alixkien** [comment]
- [x] add general json file for rht

**Comment by prudhomm** [comment]
@alixkien why did you copy the cases files in doc/manual/heat? They should be in the directory `cases`

**Comment by alixkien** [comment]
@prudhomm sorry, I made a mistake: I will move the cases files to the correct directory

**Comment by prudhomm** [comment]
The files are already there. Please overwrite them and remove the ill placed ones
