### ISSUE TITLE
implement nirb tools in feel++

### ISSUE THREAD

**Issue by thomas-saigre** [feelpp/feelpp#1912]
Non intrusive reduced basis methods could be useful to enable model order reduction on complex models/numerical methods

- [x] feelpp/feelpp#1949
- [x] feelpp/feelpp#1950
- [x] feelpp/feelpp#1951
- [x] feelpp/feelpp#1952
- [x] feelpp/phd.thomas#14
- [x] feelpp/feelpp#1954
- [x] #1955
- [x] Use RIC for POD basis generation
- [ ] #2038

**Comment by thomas-saigre** [comment]
Make the code usable as a python library

**Comment by thomas-saigre** [comment]
- [ ] Insert a greedy loop to construct the snapshots in the offline stage
- [ ] Compute the multiplication of the interpolation matrix and the basis vector only once to accelerate the online stage :
     $\alpha_i^{N,H} = (u_H^\mathcal{N}, \xi_i^h)_{L^2}=u_H^N\times (M^{Hh}\xi_i^h)$

**Comment by prudhomm** [comment]
@thomas-saigre @alielarif before going further perhaps do a pull request should be done with the current version to check the initial work and add new issues for the two bits above and specific pull requests for them.

**Comment by thomas-saigre** [comment]
- [ ] compute and store matrices instead of computing multiplication multiple times
