### ISSUE TITLE
Add design of view factor classes

### ISSUE THREAD

**Issue by prudhomm** [feelpp/feelpp#1915]
implement a class hierarchy to support view factor computations: #1910 and #1892

**Comment by prudhomm** [comment]
a simple hierarchy has been setup, it will get updated very soon

**Comment by lberti** [comment]
@prudhomm can we close this issue or further work needs to be done to improve the class hierarchy for the computation of view factors?

**Comment by prudhomm** [comment]
we need to check indeed if further work is needed
