### ISSUE TITLE
Joining the Slack channel

### ISSUE THREAD

**Issue by massimiliano-leoni** [feelpp/feelpp#1918]
I would like to join the feelpp Slack channel. As per the documentation, I sent an email to support@feelpp.org but I got a message saying that the address does not exist. What should I do?

**Comment by thomas-saigre** [comment]
> I would like to join the feelpp Slack channel. As per the documentation, I sent an email to [support@feelpp.org](mailto:support@feelpp.org) but I got a message saying that the address does not exist. What should I do?

Hi ! Have you tried this link ? https://feelpp.slack.com/

**Comment by massimiliano-leoni** [comment]
I have, but it looks like I need an invitation to be able to join.

**Comment by thomas-saigre** [comment]
I see I can generate an invitation link from Slack (I don't have administrator rights in the workspace), but I don't know if public issue is the right place to share it, can I sent it somewhere directly to you ?

**Comment by massimiliano-leoni** [comment]
Sure! You can use my email address leoni.massimiliano1<at>gmail.com.

**Comment by thomas-saigre** [comment]
I sent the invitation

**Comment by massimiliano-leoni** [comment]
Got it, thanks!
