### ISSUE TITLE
Bug in mesh generated by operator Lagrange P1 in 3d

### ISSUE THREAD

**Issue by vincentchabannes** [feelpp/feelpp#199]
The mesh build with this tool does not  work in 3d in order to apply a finite element computation. It work only for visualisation! The issue appear in sequential also.
To see that, just use this mesh generated with the quickstart laplacian for example and show the export with Paraview. here is an example
```
auto meshBase = unitCube();
auto VhBase = Pch<2>( meshBase );
auto mesh = lagrangeP1(_space=VhBase)->mesh();
```

**Comment by vincentchabannes** [comment]
Whit last commits, the meshes generated by lagP1 in P2 and 2d/3d are always good (no random generation).
Also the mesh P2 in 3d can be now used also for a finite element computation (not only visu)

**Comment by prudhomm** [comment]
nice !
we can do a lot of things from there :)
like preconditioning for example

**Comment by prudhomm** [comment]
@vincentchabannes should we close this bug ?

**Comment by vincentchabannes** [comment]
it's always the case for order > 2. we need to complete the database.
However the bug is identified, the issue can be closed or only change the status/name.

**Comment by prudhomm** [comment]
see #694
