### ISSUE TITLE
🏭  add multiblock 2D and 3D use case generator

### ISSUE THREAD

**Issue by prudhomm** [feelpp/feelpp#2014]
add the multiblock hypercube use case generator with parametrisation  in $dD$

- generate geo and mesh
- generate cfg and json for heat/cfpdes toolbox

## Geometry

- $d=2$ and $d=3$
- number of blocks $n_{\text{rows}}$ / $n_{\text{cols}}$

## Model
- parametrisation of the properties, eg thermal conductivity, Biot number
- parametrization of the boundary condition

@alielarif @thomas-saigre could you contribute this in a separate branch directly from develop and not the nirb branches

**Comment by alielarif** [comment]
Now I have a case generator in 2D with only 3xN blocs. I will generalize it for $N_{row} \times N_{col}$ blocs.

**Comment by prudhomm** [comment]
@alielarif @thomas-saigre it should go here  https://github.com/feelpp/feelpp/tree/develop/toolboxes/generator/cases next to thermal fin. @thomas-saigre the templating code should be common and not specific

**Comment by prudhomm** [comment]
@alielarif @thomas-saigre I created the branch, simply do the following : 
```
git fetch origin
git checkout 2014-add-multiblock-2d-and-3d-use-case-generator
```

**Comment by prudhomm** [comment]
@thomas-saigre @alielarif is this done?
it should be similar to the thermal fin

**Comment by thomas-saigre** [comment]
It works well for the thermal fin case, but there is still some issues with the cube template

**Comment by alielarif** [comment]
It is done in 2D for a subdivision of a square in N_x \times N_x blocs. We don't have the  case of 3D.

**Comment by thomas-saigre** [comment]
there are issues even in 2d for the cfg and json file, I'm trying to fix it.
on the geometry too if we set another number of blocks

**Comment by thomas-saigre** [comment]
@alielarif @prudhomm I tried to set the number of block in the three dimension but this doesn't work.

**What is done :**

* Generation of the 2D case, with many squares as we want
* Generation of the 3D case, with many squares as we want in the two first dimensions, and only 1 in the third
* The [documentation](https://github.com/feelpp/feelpp/blob/2014-add-multiblock-2d-and-3d-use-case-generator/toolboxes/generator/cases/heat_nirb/case_generator_cube.adoc) of the python script, and of the parameters  involved
