### ISSUE TITLE
Create objects inside a mesh via a level set function

### ISSUE THREAD

**Issue by prudhomm** [feelpp/feelpp#2021]
It can be interesting to create objects inside a meshed geometry whose CAO discretization is not available.
In order to do so, we rely on the MMG functionalities described in http://www.mmgtools.org/mmg-remesher-try-mmg/mmg-remesher-tutorials/mmg-remesher-mmg2d/implicit-domain-meshing, which create an interface from the 0-level set of a function. 
The corresponding example can be found in the MMG repository in `/libexamples/mmg2d/IsosurfDiscretization_lsOnly/main.c`.

It is necessary to:
- provide a .mesh file, containing the mesh where the function is defined
- provide a .sol file, containing the function  defining the interface

The steps are
- [ ] create functions that write the .mesh and .sol files
- [x] create a circle on a square mesh using the function `(x-x0)^2 + (y-y0)^2-R^2`
- [x] create the level set associated to a generic body and place it in the meshed geometry (translation, rotation, scaling of the body coordinates & extension of the level set onto the meshed geometry)
- [ ] add  c++ API 
- [ ] add python API 
- [ ] add mesh generation tool

**Comment by VLCeline** [comment]
@prudhomm 

Insertion of the three-sphere swimmer in a meshed rectangular geometry in 2D: 


![Image](https://user-images.githubusercontent.com/77676706/209168442-b6e5c700-c4aa-4327-97a1-b28783d73a51.png)


With recollection of all volume and boundary markers: 


![Image](https://user-images.githubusercontent.com/77676706/209168463-b1d38b65-59c5-4788-9172-b17b09491e50.png)

**Comment by prudhomm** [comment]
@VLCeline where do we stand on this ?
