### ISSUE TITLE
Cannot properly model slit with zero thickness with Homogeneous BC in cfpdes

### ISSUE THREAD

**Issue by Trophime** [feelpp/feelpp#2022]
Hi,
I'm trying to solve a electro-thermal problem with an interior boundary condition on a slit of zero thickness.
The cal is of Neumann type for the electric problem and robin type for the thermal problem.
The solution is displayed on the right side of the attached image for the thermal (top) and electric (bottom) problem
A reference solution with a slit of finite thickness is given on the left images.

![cmp](https://user-images.githubusercontent.com/1309311/205929224-c522a990-d0cb-4c83-9044-cd1766f6674b.png)

One can see that the robin cal was clearly taken into account, whereas the homogeneous Neumann BC on the electric problem seems to be ignored.

The files to reproduce the issue has been sent to @prudhomm and @vincentchabannes by email.

NB: the mesh is built so that the nodes and edges are duplicated on the slit.

**Comment by Trophime** [comment]
The Robin BC du/dn = a * u + b for the thermal problem are not correct either...
My guess is that du/dn = b  part is not properly treated as in the electric problem where du/dn= 0 is ignored

@prudhomm @vincentchabannes any news on that issue?

This is a blocking issue for the modelling of Bitter magnets which I try to implement to demonstrate feelpp usage (and its advantages when compared to other software) in the frame of a european project with my colleagues of EMFL

**Comment by prudhomm** [comment]
not yet, let's discuss that on monday

**Comment by prudhomm** [comment]
@Trophime what is the exact problem that you solve ? could you provide the equation set ?

**Comment by Trophime** [comment]
thermoelectric in Axi implemented with cfpdes
