### ISSUE TITLE
python script fails to run on 96 cores of gaya

### ISSUE THREAD

**Issue by prudhomm** [feelpp/feelpp#2048]
I have a python script made to run on 96 cores, but when I run it on a single node, it takes too much memory and fails.
I tried the following slurm script to split it on 2 nodes :

```sh
#!/bin/bash
#SBATCH --job-name=get-output
#SBATCH --nodes=2
#SBATCH --ntasks-per-node=48
#SBATCH --time=1:00:00
#SBATCH --output=log-output%j.log
#SBATCH --error=log-error%j.log

mpirun -np 96 python output.py
```

but in the execution, at the step on loading the mesh (already partitioned over 96 cores), it fails :

```python
Traceback (most recent call last):
  File "/data/home/.../output.py", line 127, in <module>
    run("Eye-model/eye.cfg", "outputCOMP.csv")
  File "/data/home/.../output.py", line 38, in run
    mesh = feelpp.load(m, path, 0.1)
RuntimeError: MPI_Test: MPI_ERR_TRUNCATE: message truncated
```

is it an issue of parametrization of slurm ? Or should I also update the python code ?

_Originally posted by @thomas-saigre in https://github.com/feelpp/feelpp/discussions/2045_

**Comment by prudhomm** [comment]
@thomas-saigre could you provide the link to your code so that we can reproduce this ?

**Comment by prudhomm** [comment]
@thomas-saigre here is a testcase that works fine:

```
#!/bin/bash
#SBATCH --job-name=get-output
#SBATCH --nodes=2
#SBATCH --ntasks-per-node=48
#SBATCH --time=1:00:00
#SBATCH --output=log-output%j.log
#SBATCH --error=log-error%j.log

mkdir -p /data/home/prudhomm/toto

 mpirun -np 96 feelpp_qs_laplacian_2d --directory /data/home/prudhomm/toto --config-file  /usr/share/feelpp/data/testcases/quickstart/cases/feelpp2d/feelpp2d.cfg  --f=1 --gmsh.hsize=0.025
```

**Comment by thomas-saigre** [comment]
@prudhomm I successfully ran the example you provided. So the issue must come from my python script.
The script `output.py` is [here](https://github.com/feelpp/phd.thomas/blob/ef2ffcea88de11f6a7ff16c1c084f33d1c4623fb/paper/2022.eye/src/heat/output.py).
If I run on one node, it works fine, but on multiple cores, the execution fails on [line 37](https://github.com/feelpp/phd.thomas/blob/ef2ffcea88de11f6a7ff16c1c084f33d1c4623fb/paper/2022.eye/src/heat/output.py#L37) :
```python
mesh = feelpp.load(m, path, 0.1)
```
with the same error message in the log than above :
```py
Traceback (most recent call last):
  File "/data/home/.../output.py", line 127, in <module>
    run("Eye-model/eye.cfg", "outputCOMP.csv")
  File "/data/home/.../output.py", line 38, in run
    mesh = feelpp.load(m, path, 0.1)
RuntimeError: MPI_Test: MPI_ERR_TRUNCATE: message truncated
```

**Comment by thomas-saigre** [comment]
@prudhomm I successfully ran the example you provided. So the issue must come from my python script.
The script `output.py` is [here](https://github.com/feelpp/phd.thomas/blob/ef2ffcea88de11f6a7ff16c1c084f33d1c4623fb/paper/2022.eye/src/heat/output.py).
If I run on one node, it works fine, but on multiple cores, the execution fails on [line 37](https://github.com/feelpp/phd.thomas/blob/ef2ffcea88de11f6a7ff16c1c084f33d1c4623fb/paper/2022.eye/src/heat/output.py#L37) :
```python
mesh = feelpp.load(m, path, 0.1)
```
with the same error message in the log than above :
```py
Traceback (most recent call last):
  File "/data/home/.../output.py", line 127, in <module>
    run("Eye-model/eye.cfg", "outputCOMP.csv")
  File "/data/home/.../output.py", line 38, in run
    mesh = feelpp.load(m, path, 0.1)
RuntimeError: MPI_Test: MPI_ERR_TRUNCATE: message truncated
```

**Comment by prudhomm** [comment]
@thomas-saigre have you followed these procedures : 

For the inter-node to work (use of network cards in RoCE), you have to go through [HPCX](https://docs.nvidia.com/networking/display/HPCXv29/NVIDIA+HPC-X+Software+Toolkit). 

A module has been setup  env-module which allows to activate hpcx on gaya. 
Be careful, it sets a lot of variables that redefine MPI dependencies. To use it :
```
module load hpcx
```

**Comment by thomas-saigre** [comment]
> have you followed these procedures
@prudhomm 

If I add the line `module load hpcx` in my slurm script, I get the following error message :
```python
--------------------------------------------------------------------------
MPI_INIT has failed because at least one MPI process is unreachable
from another.  This *usually* means that an underlying communication
plugin -- such as a BTL or an MTL -- has either not loaded or not
allowed itself to be used.  Your MPI job will now abort.

You may wish to try to narrow down the problem;

 * Check the output of ompi_info to see which BTL/MTL plugins are
   available.
 * Run your application with MPI_THREAD_SINGLE.
 * Set the MCA parameter btl_base_verbose to 100 (or mtl_base_verbose,
   if using MTL-based communications) to see exactly which
   communication plugins were considered and/or discarded.
--------------------------------------------------------------------------
[gaya4:1773962] *** An error occurred in MPI_Init_thread
[gaya4:1773962] *** reported by process [1562902529,46]
[gaya4:1773962] *** on a NULL communicator
[gaya4:1773962] *** Unknown error
[gaya4:1773962] *** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
[gaya4:1773962] ***    and potentially your MPI job)
[gaya4:1773907] PMIX ERROR: UNREACHABLE in file server/pmix_server.c at line 2198
(this line is repeted 47 times)
[gaya4:1773907] 95 more processes have sent help message help-mpi-runtime.txt / mpi_init:startup:pml-add-procs-fail
[gaya4:1773907] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages
[gaya4:1773907] 51 more processes have sent help message help-mpi-errors.txt / mpi_errors_are_fatal unknown handle
```
