### ISSUE TITLE
Option problem for a custom toolbox in python

### ISSUE THREAD

**Issue by Luplz** [feelpp/feelpp#2065]
An error occurs when trying to use options (in a `.cfg' file) for toolboxes whose `keyword' has been changed. The problem seems to be with the `prefix` variable. 
```
File "/home/u4/csmi/2020/palazzolo/Microswimmers/feelpp/research/stage.lucas/shape_opti.py", line 119, in <module>
    primal_pb, meas_primal = primal_toolbox(json = primal_json, mesh = mesh, dim=dim)
  File "/home/u4/csmi/2020/palazzolo/Microswimmers/feelpp/research/stage.lucas/shape_opti.py", line 28, in primal_toolbox
    primal_pb = cfpdes(dim=dim,keyword=keyword)
  File "/home/u4/csmi/2020/palazzolo/Microswimmers/feelpp/build/python/install/lib/python3/dist-packages/feelpp/toolboxes/cfpdes/__init__.py", line 34, in cfpdes
    pdes = _cfpdes[key](prefix="cfpdes", keyword=keyword, worldComm=worldComm, subprefix="", modelRep=modelRep)
ValueError: /usr/include/feelpp/feel/feelcore/environment.hpp:739 invalid or missing option cfpdes.verbose
```

I present below a piece of my python code to create my environment and a function to create my "expansion" toolbox.
```python
        e = feelpp.Environment(
                sys.argv, opts= feelpp.backend_options("Iv")
                                .add(tb.toolboxes_options("coefficient-form-pdes", "expansion")),
                config=feelpp.localRepository(folder)
                                )

def expansion_toolbox(json, mesh, dim, t, l, keyword="expansion"):

    print("Solving the expansion problem")
    expansion_pb = cfpdes(dim=dim, keyword=keyword)
    expansion_pb.setMesh(mesh)
    expansion_pb.setModelProperties(json)
    expansion_pb.addParameterInModelProperties("t",t)
    expansion_pb.addParameterInModelProperties("l",l)
    expansion_pb.init(buildModelAlgebraicFactory=True)
    expansion_pb.solve()
    expansion_pb.exportResults()
    meas_expansion = expansion_pb.postProcessMeasures().values()

    return expansion_pb, [meas_expansion]
```

I am attaching a `.zip` file containing a `.json` file and the `.cfg` file I use.
[cantilever.zip](https://github.com/feelpp/feelpp/files/11091034/cantilever.zip)

**Comment by prudhomm** [comment]
After reviewing the python layer, the command line options were indeed prefixed by `cfpdes`, i.e
```
[cfpdes]
ksp-monitor=1
```
Unfortunately all cfpdes are currently sharing the same option prefix, so you cannot distinguish between a linear elasticity solve and the harmonic extension solve for example. I updated the constructors so that so that we can now fully configure the command line options (including the `subprefix` that may be useful in some cases) and the `keyword`. All three can now  be changed for all toolboxes and finally I documented these toolbox constructor parameters
