### ISSUE TITLE
new mor application for heat transfert in eye

### ISSUE THREAD

**Issue by prudhomm** [feelpp/feelpp#2068]
add new mor app for eye heat transfert

- [x] #2081
- [x] #2086
- [x] #2098

Need to be done / fixed :

- [x] Use `P2` discretization
- [x] Use isolated output
- [x] Error bound
- [x] Use 2D Mesh
- [x] Sensitivity analysis and uncertainty propagation (with error bounds)

**Comment by thomas-saigre** [comment]
@prudhomm @vincentchabannes 
It seems that by default, the online application looks for the plugin inside the `/usr/lib/x86-64...` directory, while the plugin is not automatically installed here (e.g. in `build/install/lib`).
I find a way to hard pass it, by setting the right directory path at this line https://github.com/feelpp/feelpp/blob/fbec514b33cffcd6987a9e28e0bb2252f70687b6/mor/mor/feel/feelmor/crbmodeldb.cpp#L161, changing `meta.plugin_libdir` by the path to the right directory but this is not a good way to do it...
I created the issue #2086 about it
