### ISSUE TITLE
Package ghcr.io/feelpp/feelpp:v0.111.0-alpha.4-focal

### ISSUE THREAD

**Issue by jermuzet** [feelpp/feelpp#2122]
@prudhomm  Latest docker image for v0.111.0-alpha.4-focal is broken.
Docker image is only 167 MB and contains not feelpp package :((

**Comment by prudhomm** [comment]
@jermuzet are you sure ? I don't see that 
<img width="1045" alt="Screenshot 2023-06-30 at 13 59 46" src="https://github.com/feelpp/feelpp/assets/151693/ee622389-a290-41ac-b420-3e614ee75a70">

**Comment by prudhomm** [comment]
Please let me know what you are doing
