### ISSUE TITLE
Create fpp file for mor thermal building 

### ISSUE THREAD

**Issue by prudhomm** [feelpp/feelpp#2151]
We can now package offline generated db and binaries see #2150 
Generate a fpp file for thermal building and upload it to girder

See the doc part feelpp/book.feelpp.org#256

**Comment by lberti** [comment]
The`thermalbuilding.fpp` archive has been uploaded to Girder in the folder `thermalbuilding` with ID `64d60522b0e9570499e1eaa1`.
