### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by afabri** [feelpp/feelpp#2194]
I get a 404 when clicking here.
![image](https://github.com/feelpp/feelpp/assets/3263539/5fcad886-ad6b-4e17-8ced-7f0aa6723f5b)

**Comment by prudhomm** [comment]
I believe this is fixed

**Comment by prudhomm** [comment]
commits:
- [7c104e16a0bc9b1a460071a9da3ed3b21ae3f90a](https://github.com/feelpp/feelpp/commit/7c104e16a0bc9b1a460071a9da3ed3b21ae3f90a)
- [14c98991c4806bc02950cf83e01d9f50f8393592](https://github.com/feelpp/feelpp/commit/14c98991c4806bc02950cf83e01d9f50f8393592)
- [d8318fb34ea15d02d7284b5dc4b8ba431a882df3](https://github.com/feelpp/feelpp/commit/d8318fb34ea15d02d7284b5dc4b8ba431a882df3)
