### ISSUE TITLE
Python function "readCfg" not working when multiple keys are given

### ISSUE THREAD

**Issue by thomas-saigre** [feelpp/feelpp#2280]
It is now possible to add many JSNO files in the cfg file, but with Python, when we try to read this file, we get the error
```
DuplicateOptionError: While reading from '<???>' [line 12]: option 'json.filename' in section 'heat' already exists
```

Here is an MWE:
```ini
[heat]
json.filename=$cfgdir/file1.json
json.filename=$cfgdir/file2.json
```

```py
import feelpp.core as fppc
fppc.readCfg("file.cfg")
```

**Comment by prudhomm** [comment]
@thomas-saigre it means that the option `json.filename` is not considered a multiple(vector) option (that can be repeated to create a list). Is it possible that the option is defined differently in python ?

**Comment by thomas-saigre** [comment]
I think in Python the cfg file is not treated as a list of option, it is read using an external library (`ConfigParser`):
https://github.com/feelpp/feelpp/blob/6bd7d9f387360ce0039d22ab99ef360f11adc03d/python/pyfeelpp/feelpp/__init__.py.in#L36-L42

**Comment by prudhomm** [comment]
indeed ConfigParser may not support mutiple tokens
let's check the docs

**Comment by prudhomm** [comment]
I found a possible solution on stackoverflow 
https://stackoverflow.com/questions/15848674/how-to-configparse-a-file-keeping-multiple-values-for-identical-keys

shall we try it ?

**Comment by thomas-saigre** [comment]
What is done with the C++ application? I think that when many JSON files are provided, it results in merging all these files, isn't it?

**Comment by prudhomm** [comment]
We get a vector or list of values
