### ISSUE TITLE
FTBS applications/crb/heat1d  with g++ 4.8.2

### ISSUE THREAD

**Issue by Trophime** [feelpp/feelpp#267]
On Debian testing g++ 4.8.2 is now the default compiler.
The default build works fine.
However applications/crb/heat1d FTBS (see also feelpp/hifimagnet#15 in Hifimagnet):

[ 80%] Building CXX object applications/crb/heat1d/CMakeFiles/crb_heat1dapp.dir/heat1dapp.cpp.o
In file included from /usr/include/c++/4.8/backward/strstream:51:0,
                 from /usr/include/vtk-5.8/vtkIOStream.h:112,
                 from /usr/include/vtk-5.8/vtkSystemIncludes.h:40,
                 from /usr/include/vtk-5.8/vtkIndent.h:24,
                 from /usr/include/vtk-5.8/vtkObjectBase.h:43,
                 from /usr/include/vtk-5.8/vtkObject.h:41,
                 from /usr/include/vtk-5.8/vtkVersion.h:29,
                 from /home/LNCMI-G/trophime/feelpp/feel/feelfilters/pointsettomesh.hpp:46,
                 from /home/LNCMI-G/trophime/feelpp/feel/feeldiscr/operatorlagrangep1.hpp:35,
                 from /home/LNCMI-G/trophime/feelpp/feel/feeldiscr/discr.hpp:45,
                 from /home/LNCMI-G/trophime/feelpp/feel/feel.hpp:50,
                 from /home/LNCMI-G/trophime/feelpp/feel/feeldiscr/reducedbasisspace.hpp:36,
                 from /home/LNCMI-G/trophime/feelpp/applications/crb/heat1d/heat1d.hpp:41,
                 from /home/LNCMI-G/trophime/feelpp/applications/crb/heat1d/heat1dapp.cpp:2:
/usr/include/c++/4.8/backward/backward_warning.h:32:2: warning: #warning This file includes at least one deprecated or antiquated header which may be removed without further notice at a future date. Please use a non-deprecated interface with equivalent functionality instead. For a listing of replacement headers and interfaces, consult the file backward_warning.h. To disable this warning use -Wno-deprecated. [-Wcpp]
 #warning \
  ^
In file included from /usr/include/boost/parameter/parameters.hpp:40:0,
                 from /usr/include/boost/parameter.hpp:11,
                 from /usr/include/boost/signals2/signal_type.hpp:32,
                 from /usr/include/boost/signals2.hpp:20,
                 from /home/LNCMI-G/trophime/feelpp/feel/feelcore/environment.hpp:35,
                 from /home/LNCMI-G/trophime/feelpp/feel/feelalg/backend.hpp:39,
                 from /home/LNCMI-G/trophime/feelpp/applications/crb/heat1d/heat1d.hpp:38,
                 from /home/LNCMI-G/trophime/feelpp/applications/crb/heat1d/heat1dapp.cpp:2:
/usr/include/boost/parameter/aux_/arg_list.hpp: In instantiation of âstruct boost::parameter::aux::arg_list<boost::parameter::template_keyword<Feel::tag::model_type, Feel::ModelCrbBase<Feel::ParameterDefinition, Feel::FunctionSpaceDefinition> >, boost::parameter::aux::empty_arg_list>â:
/usr/include/boost/parameter/aux_/arg_list.hpp:171:8:   recursively required from âstruct boost::parameter::aux::arg_list<boost::parameter::template_keyword<Feel::tag::mesh_type, Feel::Mesh<Feel::Simplex<1u, 1u, 1u> > >, boost::parameter::aux::arg_list<boost::parameter::template_keyword<Feel::tag::model_type, Feel::ModelCrbBase<Feel::ParameterDefinition, Feel::FunctionSpaceDefinition> >, boost::parameter::aux::empty_arg_list> >â
/usr/include/boost/parameter/aux_/arg_list.hpp:171:8:   required from âstruct boost::parameter::aux::arg_list<boost::parameter::template_keyword<Feel::tag::value_type, double>, boost::parameter::aux::arg_list<boost::parameter::template_keyword<Feel::tag::mesh_type, Feel::Mesh<Feel::Simplex<1u, 1u, 1u> > >, boost::parameter::aux::arg_list<boost::parameter::template_keyword<Feel::tag::model_type, Feel::ModelCrbBase<Feel::ParameterDefinition, Feel::FunctionSpaceDefinition> >, boost::parameter::aux::empty_arg_list> > >â
/usr/include/boost/parameter/binding.hpp:59:13:   required from âstruct boost::parameter::binding<boost::parameter::aux::arg_list<boost::parameter::template_keyword<Feel::tag::value_type, double>, boost::parameter::aux::arg_list<boost::parameter::template_keyword<Feel::tag::mesh_type, Feel::Mesh<Feel::Simplex<1u, 1u, 1u> > >, boost::parameter::aux::arg_list<boost::parameter::template_keyword<Feel::tag::model_type, Feel::ModelCrbBase<Feel::ParameterDefinition, Feel::FunctionSpaceDefinition> >, boost::parameter::aux::empty_arg_list> > >, Feel::tag::bases_list, Feel::detail::bases<Feel::Lagrange<1u, Feel::Scalar> > >â
/home/LNCMI-G/trophime/feelpp/feel/feeldiscr/reducedbasisspace.hpp:107:113:   required from âclass Feel::ReducedBasisSpace<Feel::ModelCrbBase<Feel::ParameterDefinition, Feel::FunctionSpaceDefinition>, Feel::Mesh<Feel::Simplex<1u, 1u, 1u> >, Feel::Mesh<Feel::Simplex<1u, 1u, 1u> >, double>â
/home/LNCMI-G/trophime/feelpp/applications/crb/heat1d/heat1d.hpp:617:32:   required from here
/usr/include/boost/parameter/aux_/arg_list.hpp:258:15: error: cannot allocate an object of abstract type âFeel::ModelCrbBase<Feel::ParameterDefinition, Feel::FunctionSpaceDefinition>â
     reference get_default(D const&, mpl::false_) const
               ^
In file included from /home/LNCMI-G/trophime/feelpp/feel/feeldiscr/reducedbasisspace.hpp:38:0,
                 from /home/LNCMI-G/trophime/feelpp/applications/crb/heat1d/heat1d.hpp:41,
                 from /home/LNCMI-G/trophime/feelpp/applications/crb/heat1d/heat1dapp.cpp:2:
/home/LNCMI-G/trophime/feelpp/feel/feelcrb/modelcrbbase.hpp:77:7: note:   because the following virtual functions are pure within âFeel::ModelCrbBase<Feel::ParameterDefinition, Feel::FunctionSpaceDefinition>â:
 class ModelCrbBase : public ModelCrbBaseBase
       ^
/home/LNCMI-G/trophime/feelpp/feel/feelcrb/modelcrbbase.hpp:146:18: note:   void Feel::ModelCrbBase<ParameterDefinition, FunctionSpaceDefinition, EimDefinition>::initModel() [with ParameterDefinition = Feel::ParameterDefinition; FunctionSpaceDefinition = Feel::FunctionSpaceDefinition; EimDefinition = Feel::EimDefinitionBase<Feel::ParameterDefinition, Feel::FunctionSpaceDefinition>]
     virtual void initModel() = 0;
                  ^
In file included from /usr/include/boost/parameter/parameters.hpp:40:0,
                 from /usr/include/boost/parameter.hpp:11,
                 from /usr/include/boost/signals2/signal_type.hpp:32,
                 from /usr/include/boost/signals2.hpp:20,
                 from /home/LNCMI-G/trophime/feelpp/feel/feelcore/environment.hpp:35,
                 from /home/LNCMI-G/trophime/feelpp/feel/feelalg/backend.hpp:39,
                 from /home/LNCMI-G/trophime/feelpp/applications/crb/heat1d/heat1d.hpp:38,
                 from /home/LNCMI-G/trophime/feelpp/applications/crb/heat1d/heat1dapp.cpp:2:
/usr/include/boost/parameter/aux_/arg_list.hpp:264:15: error: cannot allocate an object of abstract type âFeel::ModelCrbBase<Feel::ParameterDefinition, Feel::FunctionSpaceDefinition>â
     reference get_default(D const& d, mpl::true_) const
               ^
In file included from /home/LNCMI-G/trophime/feelpp/feel/feeldiscr/reducedbasisspace.hpp:38:0,
                 from /home/LNCMI-G/trophime/feelpp/applications/crb/heat1d/heat1d.hpp:41,
                 from /home/LNCMI-G/trophime/feelpp/applications/crb/heat1d/heat1dapp.cpp:2:
/home/LNCMI-G/trophime/feelpp/feel/feelcrb/modelcrbbase.hpp:77:7: note:   since type âFeel::ModelCrbBase<Feel::ParameterDefinition, Feel::FunctionSpaceDefinition>â has pure virtual functions
 class ModelCrbBase : public ModelCrbBaseBase
       ^
In file included from /usr/include/boost/parameter/parameters.hpp:40:0,
                 from /usr/include/boost/parameter.hpp:11,
                 from /usr/include/boost/signals2/signal_type.hpp:32,
                 from /usr/include/boost/signals2.hpp:20,
                 from /home/LNCMI-G/trophime/feelpp/feel/feelcore/environment.hpp:35,
                 from /home/LNCMI-G/trophime/feelpp/feel/feelalg/backend.hpp:39,
                 from /home/LNCMI-G/trophime/feelpp/applications/crb/heat1d/heat1d.hpp:38,
                 from /home/LNCMI-G/trophime/feelpp/applications/crb/heat1d/heat1dapp.cpp:2:
/usr/include/boost/parameter/aux_/arg_list.hpp:346:15: error: cannot allocate an object of abstract type âFeel::ModelCrbBase<Feel::ParameterDefinition, Feel::FunctionSpaceDefinition>â
     reference operator[](keyword<key_type> const&) const
               ^
In file included from /home/LNCMI-G/trophime/feelpp/feel/feeldiscr/reducedbasisspace.hpp:38:0,
                 from /home/LNCMI-G/trophime/feelpp/applications/crb/heat1d/heat1d.hpp:41,
                 from /home/LNCMI-G/trophime/feelpp/applications/crb/heat1d/heat1dapp.cpp:2:
/home/LNCMI-G/trophime/feelpp/feel/feelcrb/modelcrbbase.hpp:77:7: note:   since type âFeel::ModelCrbBase<Feel::ParameterDefinition, Feel::FunctionSpaceDefinition>â has pure virtual functions
 class ModelCrbBase : public ModelCrbBaseBase
       ^
In file included from /usr/include/boost/parameter/parameters.hpp:40:0,
                 from /usr/include/boost/parameter.hpp:11,
                 from /usr/include/boost/signals2/signal_type.hpp:32,
                 from /usr/include/boost/signals2.hpp:20,
                 from /home/LNCMI-G/trophime/feelpp/feel/feelcore/environment.hpp:35,
                 from /home/LNCMI-G/trophime/feelpp/feel/feelalg/backend.hpp:39,
                 from /home/LNCMI-G/trophime/feelpp/applications/crb/heat1d/heat1d.hpp:38,
                 from /home/LNCMI-G/trophime/feelpp/applications/crb/heat1d/heat1dapp.cpp:2:
/usr/include/boost/parameter/aux_/arg_list.hpp:353:15: error: cannot allocate an object of abstract type âFeel::ModelCrbBase<Feel::ParameterDefinition, Feel::FunctionSpaceDefinition>â
     reference operator[](default_<key_type, Default> const& d) const
               ^
In file included from /home/LNCMI-G/trophime/feelpp/feel/feeldiscr/reducedbasisspace.hpp:38:0,
                 from /home/LNCMI-G/trophime/feelpp/applications/crb/heat1d/heat1d.hpp:41,
                 from /home/LNCMI-G/trophime/feelpp/applications/crb/heat1d/heat1dapp.cpp:2:
/home/LNCMI-G/trophime/feelpp/feel/feelcrb/modelcrbbase.hpp:77:7: note:   since type âFeel::ModelCrbBase<Feel::ParameterDefinition, Feel::FunctionSpaceDefinition>â has pure virtual functions
 class ModelCrbBase : public ModelCrbBaseBase
       ^
In file included from /usr/include/boost/parameter/parameters.hpp:40:0,
                 from /usr/include/boost/parameter.hpp:11,
                 from /usr/include/boost/signals2/signal_type.hpp:32,
                 from /usr/include/boost/signals2.hpp:20,
                 from /home/LNCMI-G/trophime/feelpp/feel/feelcore/environment.hpp:35,
                 from /home/LNCMI-G/trophime/feelpp/feel/feelalg/backend.hpp:39,
                 from /home/LNCMI-G/trophime/feelpp/applications/crb/heat1d/heat1d.hpp:38,
                 from /home/LNCMI-G/trophime/feelpp/applications/crb/heat1d/heat1dapp.cpp:2:
/usr/include/boost/parameter/aux_/arg_list.hpp:359:15: error: cannot allocate an object of abstract type âFeel::ModelCrbBase<Feel::ParameterDefinition, Feel::FunctionSpaceDefinition>â
     reference operator[](lazy_default<key_type, Default) const
               ^
In file included from /home/LNCMI-G/trophime/feelpp/feel/feeldiscr/reducedbasisspace.hpp:38:0,
                 from /home/LNCMI-G/trophime/feelpp/applications/crb/heat1d/heat1d.hpp:41,
                 from /home/LNCMI-G/trophime/feelpp/applications/crb/heat1d/heat1dapp.cpp:2:
/home/LNCMI-G/trophime/feelpp/feel/feelcrb/modelcrbbase.hpp:77:7: note:   since type âFeel::ModelCrbBase<Feel::ParameterDefinition, Feel::FunctionSpaceDefinition>â has pure virtual functions
 class ModelCrbBase : public ModelCrbBaseBase
       ^
make[2]: **\* [applications/crb/heat1d/CMakeFiles/crb_heat1dapp.dir/heat1dapp.cpp.o] Error 1
make[1]: **\* [applications/crb/heat1d/CMakeFiles/crb_heat1dapp.dir/all] Error 2
make: **\* [all] Error 2

**Comment by prudhomm** [comment]
4.8 is not supported ;)
