### ISSUE TITLE
Refactor GeoTool

### ISSUE THREAD

**Issue by vincentchabannes** [feelpp/feelpp#277]

**Comment by prudhomm** [comment]
@vincentchabannes would it be possible to control geometric transformations associated to the objects ?
of course consistency between objects needs to be kept to ensure fusion when a transformation is applied

**Comment by vincentchabannes** [comment]
We can access for each object to the points, lines, surfaces. It's quite easy to define basic geometric transformation like translation, rotation, re-scaling. 
Can you give me more details? I'm not sure to understand what you want.

**Comment by prudhomm** [comment]
I close this issue
