### ISSUE TITLE
Support for boundary condition framework

### ISSUE THREAD

**Issue by prudhomm** [feelpp/feelpp#284]
Add support for a boundary condition framework based on Ginac. 
Boundary conditions would be setup in .cfg files or elsewhere

**Comment by vhuber** [comment]
How can we handle Robin bcs ?

Dirichlet:
u = g
Neumann:
d u / dn = g
Robin:
a u + b du / dn = g

We have to dispose of 3 expressions for each bcs:
```javascript
{
"variable_name":
{
"physical_marker_name":
{
"a":"...",
"b":"...",
"c":"..."
}
}
}
```

**Comment by prudhomm** [comment]
Actually you need only 2

**Comment by vhuber** [comment]
That would force the user to write neumann bc as
u + b/a du / dn = g/a

**Comment by jbwahl** [comment]
a good solution is to use materials marker :
the parameter b can be see as a diffusivity coefficient depending of the
material.

**Comment by prudhomm** [comment]
@vhuber  you have `b du / dn = g - a u`, you need only `g` and `a`, for neumann condition `b du / dn = g` you need only `g`. The normal derivative `b du / dn` comes naturally from the integration by parts of `\int_Omega \nabla \cdot (b \nabla u ) v`

**Comment by prudhomm** [comment]
a solution for Robin (scalar case) should land in feel++ very soon

**Comment by prudhomm** [comment]
it is all in the toolboxes
