### ISSUE TITLE
Allow product of spaces interface from function calls only

### ISSUE THREAD

**Issue by prudhomm** [feelpp/feelpp#301]
We have various function spaces which could be wrapped to add the support of a Lagrange multiplier to set a constraint such as the mean value.

for example

``` c++
auto Xh = product( Pch<2> (mesh), Pch<0>(mesh) );
```

where `Xh`  contains both P2 piecewise functions and the Lagrange multiplier (P0 continuous)

**Comment by vhuber** [comment]
`laplacian_lagrange_multiplier` does not compile at this point (clang, gcc)
