### ISSUE TITLE
CRB construction on a model using EIM in //

### ISSUE THREAD

**Issue by StephaneVeys** [feelpp/feelpp#344]
When we construct a CRB,with a posteriori error estimation, (with or without EIM error estimation) in parallel, on a model using EIM approximation, comes a time where all processors don't go in a function at the same time.
For example, if in the normal way, all procs do
Beta( mu1 )
Beta( mu2 )
Here proc0,1 and 2 do Beta(mu1) and then Beta(mu2), 
but proc3 arrives, or is still in,  Beta( mu1 ) while others are in Beta(mu2)

I don't know yet exactly where but somewhere there is this bug.

Note that without error estimation, there is no problem

**Comment by prudhomm** [comment]
This is very old, we can not reproduce this. it must have been fixed
