### ISSUE TITLE
MUMPS installed with homebrew/osx requires blacs

### ISSUE THREAD

**Issue by jbwahl** [feelpp/feelpp#365]
I have the following error running a 3D program on OSX : 

---

dyld: lazy symbol binding failed: Symbol not found: _blacs_gridinit_
  Referenced from: /usr/local/lib/libdmumps.dylib
  Expected in: flat namespace

dyld: Symbol not found: _blacs_gridinit_
  Referenced from: /usr/local/lib/libdmumps.dylib
  Expected in: flat namespace

dyld: lazy symbol binding failed: Symbol not found: _blacs_gridinit_
  Referenced from: /usr/local/lib/libdmumps.dylib
  Expected in: flat namespace

dyld: Symbol not found: _blacs_gridinit_
  Referenced from: /usr/local/lib/libdmumps.dylib
  Expected in: flat namespace

dyld: lazy symbol binding failed: Symbol not found: _blacs_gridinit_
  Referenced from: /usr/local/lib/libdmumps.dylib
  Expected in: flat namespace

dyld: Symbol not found: _blacs_gridinit_
  Referenced from: /usr/local/lib/libdmumps.dylib
  Expected in: flat namespace

dyld: lazy symbol binding failed: Symbol not found: _blacs_gridinit_
  Referenced from: /usr/local/lib/libdmumps.dylib
  Expected in: flat namespace

dyld: Symbol not found: _blacs_gridinit_
  Referenced from: /usr/local/lib/libdmumps.dylib
  Expected in: flat namespace

---

Note that :
- i don't have this error on another system (atlas, ubuntu vbox, ... )
- same code doesn't crash in 2D

**Comment by vhuber** [comment]
https://github.com/feelpp/homebrew-science/commit/29c42114148a4c12cd0671739c3eb82348b6b486
