### ISSUE TITLE
Mesh export for parallel execution

### ISSUE THREAD

**Issue by VANTHONG** [feelpp/feelpp#367]
Create an application and export a mesh per processor domain for parallel execution.

- Report / Documentation 
 - [ ] Mesh structure: faces/elements
 - [ ] Markers
 - [ ] Mesh types: EXPORTER_GEOMETRY_STATIC, ...
- Mesh Application
 - [x] mesh a given geometry then partition it
 - [x] partition a given mesh
 - [ ] repartition a mesh
 - [x] display basic information about a mesh 
    - [x] number of elements
    - [x] number of nodes
    - [x] number of faces and edges
    - [x] average min and max h values (see #377)

**Comment by prudhomm** [comment]
This is done via the application mesh  in applications/mesh
this is linked to #579 also
