### ISSUE TITLE
Segfault when loading/saving mesh

### ISSUE THREAD

**Issue by aancel** [feelpp/feelpp#371]
This is probably not a standard use of feelpp, but I am having a segfault with exporters (at least gmsh and ensight gold exporters are confirmed). This happens when I load a mesh and use the exporter to save it right after (without adding any other data to the exporter)
I am using feel.geo as input.

Possible use-case of this scenario: checkpoints saving only mesh data

Code to reproduce the bug:
```
#include <feel/feel.hpp>
int main( int argc, char** argv )
{
    using namespace Feel;
    Environment env( _argc=argc, _argv=argv,
                     _about=about(_name="repartition"
                   ));
    auto mesh = loadMesh(_mesh=new Mesh<Simplex<2>>);
    auto e = exporter( _mesh=mesh );
    e->save();
}
```

There seem to be no safeguards when the user does not use the add() function with the exporter.

**Comment by prudhomm** [comment]
@aancel could you fix this ?
