### ISSUE TITLE
Move levelset core to feel++

### ISSUE THREAD

**Issue by prudhomm** [feelpp/feelpp#390]
We move the levelset code from fsi to feel++ in order to bring the various features it enables to a wider range of projects.

/cc @Doyeux

**Comment by Doyeux** [comment]
Ok, the levelset framework is now in fsi/applications/levelset/￼levelset.
Most of the applications in 
fsi/applications/levelset/applications
fsi/applications/levelset/development
fsi/applications/levelset/examples
won't compile without access to fsi fluid mechanic framework. So maybe this should stay in the fsi repo?

There is now a new feature in fsi/applications/levelset/￼levelset/multifluid. A class name MultiFluidBase which handles the coupling between fsi-fluid-mechanics and levelset.
It is much easier to create a new application (like drop) now.
The two applications in levelset/examples are using this class.

**Comment by prudhomm** [comment]
the fsi code from @vincentchabannes has been moved to feel++ and redesigned to use the `Model*` classes and json file to describe a model. it is still in a separate branch but it will probably be merged very soon.
The idea would be to move the levelset library in feel++ not the applications. We can a a few demonstrators but the applications stay in the private repository

**Comment by prudhomm** [comment]
@Doyeux I already moved the fms and levelset related tools to `feells` plus I added `testsuite/feells` to mirror what we have for the other modules and moved the two tests on levelsets and fms.
