### ISSUE TITLE
Support variable expansion in options

### ISSUE THREAD

**Issue by prudhomm** [feelpp/feelpp#391]
In order to simplify cfg files and make them generic with respect to directories we should support some basic variables such as
 - `top_srcdir` 
 - `top_builddir`
 - `builddir` -> current build directory (see boost filesystem + `top_builddir`)
 - `srcdir` -> `current source directory (see boost filesystem + `top_srcdir`)
 - `home`
 - `repository` -> location of the results (`rootRepository()`)
 - `datadir` -> `$top_srcdir/data`

in cfg file it would look like this
```
gmsh.filename=$srcdir/mygeom.geo
```

a member function of  `Environment::expand` should available to make the expansion of the feel++ variables. `expand` takes a string and returns a string

**Comment by vhuber** [comment]
@prudhomm May I had a `$current` variable initialized by :
```
std::string curent = S_paths[0];
```

**Comment by prudhomm** [comment]
i need to check the code
are you sure that it isnthe current path ?
the variable should be pethaps current_path instead ?

**Comment by vhuber** [comment]
That **is** the current path (the one in the app is launched) and as long as - without the nochdir option - we change the current directory, one can not set in his config file something like :
```
bc-file=toto.bc
```
Thus, I would like to have
```
bc-file=$current_path/toto.bc
```

**Comment by prudhomm** [comment]
yes I thought about something along those lines. what should give `$current_path` ? it should return the path you are in currently, I don't think that's what you meant.
the issue here is to have a consistent behavior to find the .bc file associated to the .cfg file and probably the .geo file.
perhaps something like `$cfgpath` which would return the path to the first config-file (master file say) given to the command line or the default one found in the current dir.
and in the .cfg file we would have `bc-file=$cfgpath/toto.bc` and something similar for `gmsh.filename=$cfgpath/toto.geo`

**Comment by vhuber** [comment]
@prudhomm I do not understand why you think so: I want the current path.
When I use `feelpp_add_application`, I copy to the exec directory various files (such as geo, cfg, bc ...)
From the exec directory, the one who use 
```bash
./feelpp_myApp --config-file theBc.bc
```
won't find the file.
I thus would like to use :
```bash
./feelpp_myApp --config-file $pwd/theBc.bc // or $current_path or $current ...
```
The idea with `$cfgpath` is completely ok for me.

**Comment by vhuber** [comment]
`$<project>_builddir` will do the trick :-)
Thank you.
f720ef46ac06d3c6aea4e69a80cf7b2553f1648b

**Comment by vhuber** [comment]
We have a trouble with that feature.
In 5e313ef4 @prudhomm add the `$h` variable.
We have a project name which start with a `h`, thus
`$hproject_name` will be replaced by `gmsh_hsize_valueproject_name`.

I suggest using `${h}` or `${whatever}` instead of `$h`or `${whatever}` to make it run.
I'll add that feature.
