### ISSUE TITLE
Markers on submesh

### ISSUE THREAD

**Issue by cdaversin** [feelpp/feelpp#402]
I'm trying to integrate on edges of a volume. Since this feature is not yet available (#400), I create of 2D submesh for each faces of my volume, and try to integrate on the faces of this submesh (which correspond to edges of the volume).

For each face (marker faces[i]), I write:

```
faceMesh = createSubmesh(oneelement_mesh, markedfaces(oneelement_mesh, faces[i]));
```

This build a 2D submesh, with real dimension 3 (since it comes from 3D mesh)

Each edges of my initial 3D mesh has been marked, and from what I've seen in createsubmesh implementation these markers are passed to my submesh
Indeed, the test (with edges[q] the marker of the edge n° q)

```
CHECK( faceMesh->hasMarkers( {edges[q]} ) );
```

gives no error.
The problem is that

```
integrate( markedfaces( faceMesh, edges[q] ), ... ).evaluate()(0,0)
```

doesn't do anything, as if edges[q] was not a face of my 2D submesh.
However, I've tried to integrate on the edges on a 2D mesh (not submesh) using markedfaces and there is not any problem.

When the markers are passed from my initial mesh to my 2D submesh, the marked elements keep their topological dimension (1 for edges). I then use

```
integrate( markededges( faceMesh, edges[q] ), ... ).evaluate()(0,0)
```

but it return the following compilation error:

```
/home/cdaversin/feelpp_interpolate/feelpp/feel/feelmesh/filters.hpp:527:44: error: no member named 'edgesWithMarker' in
      'Feel::Mesh<Feel::Simplex<2, 1, 3>, double, 0>'
    std::pair<iterator, iterator> p = mesh.edgesWithMarker( __marker, __pid );
```

Regarding feelmesh/mesh2d.hpp and comparing with feelmesh/mesh3d.hpp, I've seen that Mesh3D herits from Edges class (feelmesh/edges.hpp), but it is not the case for Mesh2D. It seems normal since edges have topological dimension (Dim - 2), and it explains the compilation error since my submesh has dimension 2.

So, what should be done in this case ?

**Comment by prudhomm** [comment]
@cdaversin what is the status of this question ?
have you tried `markedfaces()` instead of `markededges()` ? you are working on a 2D mesh after all

**Comment by prudhomm** [comment]
looking at #648 this issue is fixed. @vincentchabannes may be a test should be added (or may it already exists ? )
