### ISSUE TITLE
Ensight exporter: bad output in parallel

### ISSUE THREAD

**Issue by aancel** [feelpp/feelpp#406]
While testing the fix for issue #403, I found a case where the output files for the ensight exporter does not seem to be correct.

If you use the application feelpp_doc_myfunctionspace, and comparing the output of the ensight and ensight gold exporter:
- Up until 8 processors, both outputs seems to be ok
- Starting from 16 processors, the output with the ensight format seems to be badly generated, whereas the files generated with the ensight gold format are still ok (even with the exporter.merge.markers set to 0).

This might affect other apps.

Test commands:
- ensight: mpirun -np 16 ./feelpp_doc_myfunctionspace --config myfunctionspace.cfg --exporter.format ensight
- ensight gold: mpirun -np 16 ./feelpp_doc_myfunctionspace --config myfunctionspace.cfg --exporter.format ensightgold

**Comment by prudhomm** [comment]
should I close this issue ?

**Comment by aancel** [comment]
This problem seems to have been solved with a previous commit. I'll close the issue.
