### ISSUE TITLE
Support MKL (starting from v11)

### ISSUE THREAD

**Issue by prudhomm** [feelpp/feelpp#420]
We should strive to use Intel MKL whenever possible. I propose that we start by supporting the version 11.
Also note that starting from petsc 3.5 (see #415) the `mkl_pardiso` sparse solver is now available. It would be interesting to compare with mumps.

**Comment by prj-** [comment]
It seems that the MKL support of Feel++ is somehow broken when using PETSc and Gmsh compiled with MKL support too. See the huge amount of warnings there: http://pastebin.com/FWZW2Uqx.

**Comment by prudhomm** [comment]
I would say that it is the mkl library order in feel++ which is buggy :( 
I have to find the page that allow to generate the proper order for the mkl libs, would you have it ?

**Comment by prj-** [comment]
This https://software.intel.com/en-us/articles/intel-mkl-link-line-advisor ?

**Comment by prudhomm** [comment]
yes
