### ISSUE TITLE
compilation error with chi expression

### ISSUE THREAD

**Issue by vincentchabannes** [feelpp/feelpp#442]
this code doesn't compile : 

    auto mesh = loadMesh(_mesh=new Mesh<Simplex<2>>);
    auto Vh = Pch<2>( mesh );
    auto u = Vh->element();
    auto myVec = vec( cst(1.),cst(1.) );
    form1(_test=Vh) =
      integrate(_range=elements(mesh),
                      _expr=chi( myVec(0,0) > cst(0.) )*id(u) );

the problem seems due to chi with a vector inside.
It's idem with bilinearform but it works when we evaluate an integrate.

**Comment by prudhomm** [comment]
@vincentchabannes the code does not look good:
 - `u` is a scalar field
 - `>` compares a constant vector and a constant scalar
 - `chi()` returns a vector field

could you try `myVec(0,0) > vec(cst(0.),cst(0.))` ?
eventually add the test case to the testsuite.

**Comment by vincentchabannes** [comment]
myVec(0,0) is not a vector, it's first component of vector myVec. Thus I compare two scalar with >

**Comment by prudhomm** [comment]
Ok right I was not yet fully awake
Could you add the test when you have the time?
