### ISSUE TITLE
Support new interpolation framework in OperatorInterpolation and possibly other classes

### ISSUE THREAD

**Issue by prudhomm** [feelpp/feelpp#448]
We should use the new interpolation framework wherever interpolation is needed. In particular `Operatorinterpolation` does not currently support it.
@vincentchabannes could you take care of this ?

 - [ ] OperatorInterpolation
 - [ ] put here the classes where it is needed

**Comment by prudhomm** [comment]
@vincentchabannes should it be closed now ?

**Comment by vincentchabannes** [comment]
It's only done in case when domain and image mesh are related.
Still to do 2 cases : no relation sequential and no relation parallel.

**Comment by prudhomm** [comment]
ok thanks !
