### ISSUE TITLE
Support concatenation of mesh elements containers

### ISSUE THREAD

**Issue by prudhomm** [feelpp/feelpp#455]
from @cdaversin  feelpp-devel@
```
I'm currently using createSubmesh function with a volume (and it works well !)
I would want to know if it is possible to create a submesh from two volumes (which share an interface) ?
I've to differenciate these two volumes as they have not the same physical properties. 
Can I join two iterators on markedelements and give it to createSubmesh ?
```
the answer is yes

the iterators are of the same type so no problem to join the two set of elements into one container dans give that to createSubmesh

here is what you can do
```
auto e1 =markedelementS(mesh,"1");
auto e2 =markedelementS(mesh,"2");
auto e3 = concatenate( e1, e2 );
auto new_mesh = createSubmesh( e3 );
```
The function concatenate() needs to be done. What it does is to generate a new container with elements from both 1 and 2. e3 is of the same type as e1 and e2.

**Comment by prudhomm** [comment]
what is the status of this issue @cdaversin @vhuber can it be closed ?
I think it can

**Comment by vhuber** [comment]
CDash does not indicate failures. I guess It can be closed.
