### ISSUE TITLE
OpenMP not usable

### ISSUE THREAD

**Issue by prj-** [feelpp/feelpp#464]
Hello,
For at least two reasons, OpenMP is not usable inside a Feel++ application right now.
1) in `feel/feelvf/integrator.hp`, there are some errors at compilation because it is assumed in some places that if `FEELPP_HAS_OPENMP` is true, then so is `FEELPP_HAS_HARTS`, for instance line 5121 or `5234:13: error: 'RunTimeSystem' has not been declared`.
2) MPI is initialized without any level of desired thread support.
I'll work on the second point, @aancel, could you fix the first please (or anyone else involved in HARTS) ?
Thank you.

**Comment by prudhomm** [comment]
@aancel why not but other libs require MPI cmake config such as boost mpi. Could you take care of that asap? I would like this to go in v100

**Comment by aancel** [comment]
@prudhomm I'll work on this asap.
I'll remove the dependency on MPI, and check if it causes any problem.
An other point: do you think it might be a good idea to check the MPI flavour/version with which MPI dependent libraries are compiled ? (boost.mpi, petsc, hdf5 and maybe others)
This would allow to stop the cmake step or at least warn the user that he uses libraries that are not compiled with the same MPI version/flavour.
This could be a bit tricky as the cmake files generally do not provide the flavour/version of MPI used, but it can be obtained through the mpi.h file included I think.

**Comment by prudhomm** [comment]
yes it might help diagnostic possible problems. If it is not too complicated try to do that. 
Otherwise we shall hope that the user/system has put in place a sensible environment.
Could you also see with @prj- the setting of the multi-thread environment (PETSC./MPI) ?
it would be really nice to announce that the environment is ready for hybrid computing (not to say that we are threadsafe ;) )

**Comment by prudhomm** [comment]
perhaps do the check after the v100 and provide a _simple_ solution for now ?

**Comment by aancel** [comment]
@prudhomm @prj- I tried several things regarding to MPI:
- I tried to remove the find_package(MPI) in FindFeel++.cmake and move the tests for MPI IO when we are detecting Boost MPI, but it seems that the mpi header path is not included in boost includes, so the code samples for MPI IO are not compiling and it is deactivated (we thus require a find_package(MPI) for this).
- I could make the tests when we are configuring petsc, but the problem would be that petsc can also be configured to not use mpi (sequential petsc, but the user would still want to use MPI that is required in feel++, which I guess is not a real use case), thus we won’t have access to the mpi includes. To circumvent this, we could add a check in the find_package for petsc by trying to find mpi.h in petsc include dirs and make the cmake step fail in case not.

So the ideas for now:
- either not modify the code and let MPI be found with a find_package => risk of using different version of MPI
- or Check that MPI is in petsc flags (fail if not), and make the check for MPI IO in the find_package for petsc. This would eliminate the problem with a potential different version of MPI found with a find_package of MPI.

Any input on this ?

@prj- What is the problem with the multi-thread environment ?

**Comment by prj-** [comment]
@aancel I want to initialize MPI with an arbitrary thread level support, but there is some magic inside Feel++/Boost.MPI/PETSc that makes it impossible for me to track down where you initialize MPI, cf. https://github.com/feelpp/feelpp/issues/464#issuecomment-59478047.

**Comment by aancel** [comment]
@prj- I had a quick look at your issue (on the qs_laplacian sample) and indeed right before the initialization of the environment `Environment env( ... )`, `mpi::environment::initialized()` returns 0, and as soon as the process enters the contructor with the ArgumentPack parameter, it returns 1.
I'll have a closer look tomorrow, probably linked to some global variable somewhere.

Did you try to initialize the mpi::environment right before the Environment class of feelpp ? 
They perfom a check as to whether it is already intialized in the contructor, so I guess it should be relatively safe (http://www.boost.org/doc/libs/1_57_0/libs/mpi/src/environment.cpp). Furthermore you have a constructor that allows to set the threading level.

**Comment by prj-** [comment]
@aancel Yes of course, I could use the quick and dirty way of initializing MPI right from the start, and then `boost::mpi::environment` and `PetscInitialize` will check that it has already been initialized, but I'd rather understand what is going on inside Feel++.

**Comment by prudhomm** [comment]
I guess there is may be a static variable doing something dirty behind the scene

**Comment by aancel** [comment]
@prj:
With @prudhomm, we have found the solution to your problem. When using the name-enabled Environment constructor (generated by BOOST_PARAMETER_CONSTRUCTOR), the M_env member variable of the Environment class is initialized, thus initiazing MPI and calling MPI_Init.
I will rework the constructors of the Environment class, so the initialization will happen correctly and the threading level will be parametrizable through the use of options.

**Comment by prudhomm** [comment]
it seems that threading level support is available starting from boost 1.55.
It think that the version we have of boost on Curie

**Comment by prj-** [comment]
I'm not sure neither Boost.MPI nor PETSc/SLEPc makes use of MPI calls inside OMP regions. My code does though.

**Comment by prudhomm** [comment]
what do you mean ? you mean that we may not have to configure the threading level ? 

the issue was that the default constructor for mpi::environment was called in the `ArgumentPack` constructor and it initializes mpi. Now the initialization will be done explicitly and could be configured depending on the threading level required by the application.

**Comment by prj-** [comment]
Yes, I clearly understand the issue and modifying the constructor indeed makes everything run smoothly. What I do mean though, is that this adjustement is only needed for applications that use MPI routines insided a threaded region. I don't think neither Boost.MPI nor PETSc/SLEPc uses MPI calls inside pthreads or OMP regions, so, for a standard application, changing the level of desired thread support will have no implication.

**Comment by prudhomm** [comment]
sure that's what I understood too.

**Comment by prudhomm** [comment]
@prj- you should now be able to play with multithreading :)
