### ISSUE TITLE
Problem with projection of a component of a product space element

### ISSUE THREAD

**Issue by cdaversin** [feelpp/feelpp#465]
_Context_ : 
Working with a product space with two components 

```
typedef Lagrange<1, Scalar> basis_type;
typedef FunctionSpace<mesh_type, bases<basis_type, basis_type>, double > prod_space_type;
...
auto pXh = prod_space_type::New( mesh ); // pXh = Xh x Xh
```

one can access to views (U1,U2) of a product space element U

```
auto U = pXh->element(); //product space element
auto U1 = U.template element<0>(); //first component
auto U2 = U.template element<1>(); //second component
```

**Problem** : 
The projection of a component of the product space (on correct space) passing his view directly as project function parameter is ok

```
auto myproj = vf::project(_space=Xh, _expr= idv(U.template element<0>()));
```

but the **projection using a copy of this view** into an intermediate variable

```
myexpr=idv(U.template element<0>());
auto myproj = vf::project(_space=Xh, _expr= myexpr);
```

returns the following **execution error** : 

```
pure virtual method called
terminate called without an active exception
```

and this seems to happen into globalValue() function of vectorublas (vectorublas.hpp, l. 393)
(compilation with clang 3.4)

_Note : This problem is especially encountered with eim use in crb models using product space. Indeed, _expr parameter given to eim function is copied as a member of eim object, and then projected. Moreover, this problem with projection using a copy happens only with components of product space elements_

**Comment by prudhomm** [comment]
@vincentchabannes I think this should have been closed by now. What do you think ?

**Comment by vincentchabannes** [comment]
yes, I think. I close the issue
