### ISSUE TITLE
In-Situ visualization

### ISSUE THREAD

**Issue by aancel** [feelpp/feelpp#475]
Implement In-situ visualization using Paraview/catalyst and the VTK format (see Issue #474)

**Comment by vincentchabannes** [comment]
@aancel Is it possible to use insitu visualisation with multi exporter. In my fsi code, I have two exporter, one for the fluid, another one for structure.  And when I run insitu visu in this case, I have this error : 
```
vtkPVTrivialProducer (0x7fcensions/Core/vtkPVTrivialProducer.cxx, linr.cxx, line 68
vtkPVTrivia39a15a450): New time step isaViewCore/VTKExtensions/Core/vtkPVTrivialProducer.cxx, line 68
vtkPVTrivialProducer (0x7f94b8bdce 68
vtkPVTrivialProducerlProducer (0x7feec87aa97cd0): New time step is not afte0): New time not after last tir last time step.

 (0x7f9d382cabf0): New tim step is not after last time step.
me step.

e step is not after last 
time step.
```

**Comment by aancel** [comment]
Indeed, I haven't tested this configuration yet. 
I think that I have an idea about what is causing you this problem. It tries to use the same proxy object for all the exporter instances, so when you export 2 different datasets for a single time step, it expects a different time step for each, but the same one is used, thus your error. 
I hope my explication is clear, but anyway I'll try to push a fix tomorrow and see if it helps with your case.

**Comment by vincentchabannes** [comment]
Ok, thank's.

**Comment by aancel** [comment]
@vincentchabannes Ok I had a look and what I thought would be the problem is not the problem in fact.
Do you have a sample code that reproduces this error and that I could use to debug ?
Are you instantiating two separate exporters ?

**Comment by vincentchabannes** [comment]
Yes, I have 2 exporters, one 2d and another one 1d (with a RealDim 2d). I am at the airport of Paris and quite tired, thus not operational to give you an example now. We will see that at FUD. Maybe I do a mistake and also I haven't updated your last changes.

**Comment by aancel** [comment]
@vincentchabannes I added the option `--exporter.vtk.insitu.save` to save data to disk when doing in-situ visualization.
