### ISSUE TITLE
Matrix Type

### ISSUE THREAD

**Issue by jbwahl** [feelpp/feelpp#476]
When you create a new backend, whatever is the type of this backend, the type of the pointer returned by the `newMatrix()` method is `boost::shared_ptr<MatrixSparse>`. With this behavior, we potentially lost methods of specific matrix. 

As an example, the following code does not compile because the `mat()` method does not exist in the `MatrixSparse` class but is implemented in the `MatrixEigenDense` class
```
auto mesh = loadMesh(_mesh=new Mesh<Simplex< 2 > > );
auto Xh = Pch<1>( mesh );
auto my_backend = Backend<double>::build( "eigen_dense" );
auto A = my_backend->newMatrix(Xh,Xh);
Eigen::MatrixXd matA = A->mat();
```

A solution is the use of `boost::dynamic_pointer_cast` to create a new pointer on the same matrix but with the appropriate type.
```
boost::shared_ptr<MatrixEigenDense<double> > A2 = boost::dynamic_pointer_cast<MatrixEigenDense<double> >(A);
Eigen::MatrixXd matA = A2->mat();
```

This issue comes because all pointer in the `newMatrix()` methods are always cast in `boost::shared_ptr<MatrixSparse>` (see for example `backendeigen.hpp` l118 ). I guess this cast is necessary somewhere in the code but it is not obvious for the user to reverse it with the dynamic_cast. 

We might be able to find a solution for a more natural behavior ?

**Comment by prudhomm** [comment]
this is the expected behavior. `dynamic_cast<>` is usually sufficient to retrieve the true matrix type.
the idea is to hide the algebra backend behind an interface. The library then takes care of doing the proper cast depending on the backend/matrix/vector.
