### ISSUE TITLE
Problem when mesh generation fails

### ISSUE THREAD

**Issue by prj-** [feelpp/feelpp#486]
If you run `mpirun -np 1 ./feel_assembly --parameters.l=5`, you'll end up with an error when assembling the matrix on the finest level : 
```
[0]PETSC ERROR: Invalid Pointer to Object: Parameter # 1
[0]PETSC ERROR: #2 MatZeroEntries() line 5319 in petsc/src/mat/interface/matrix.c
[0]PETSC ERROR: #3 zero() line 566 in feelpp/feel/feelalg/matrixpetsc.cpp
```
If you try to find the source of the problem, that is because Gmsh fails to mesh the `.geo` created by Feel++ : 
```
$ gmsh hypercube_5.geo -2 -o hypercube_5.msh
Error   : Identical points in triangulation: increase element size or Mesh.RandomFactor
Error   : Unable to recover an edge 0 1 && 0 0.99375 (0/159)
```
Now there are two problems : 
1) it doesn't look like Feel++ can detect that there is a problem with the mesh generation,
2) I don't think it is easy to adjust directly `Mesh.RandomFactor` from within Feel++. I have tried `--gmsh.geo-variables-list="Mesh.RandomFactor=1e-6;"` but it doesn't work.

**Comment by vhuber** [comment]
You may add to to your `~/.gmsh-options` the option `Mesh.RandomFactor=1e-6;` to take it into account when generating the `msh` file from the `gmsh` executable.
Unfortunately, it seems it does not work when `gmsh` is used as a library, thus I have added the option below.

**Comment by prj-** [comment]
That solves point 2) of the issue, yes, thank you.

**Comment by vhuber** [comment]
I guess the point 1) is solved, isn'it ?

**Comment by prj-** [comment]
How ? If you don't know that you have to adjust `gmsh.randFactor` and Gmsh fails, there is no warning from the Feel++ side, so it might be a little bit disturbing for new users (who just know how to play with `gmsh.hsize`) to have Feel++ crash for no apparent reason. It took me a while to figure out that the problem was coming from Gmsh, instead of Feel++, I would have really enjoyed a little warning to track down the problem more easily.

**Comment by vhuber** [comment]
As long as the app name has been changed, could you please reproduce the bug with the new version ?

**Comment by prj-** [comment]
Yep, I just ran `mpirun -np 1 ./feelpp_tut_mylaplacian --gmsh.hsize=0.0001`: exactly the same problem.
Feel++ crashes, and in `~/feel/mylaplacian/np_1`, if I run `gmsh -2 square.geo  -o square.msh`:
```
Error   : ------------------------------
Error   : Mesh generation error summary
Error   :     0 warnings
Error   :     2 errors
Error   : Check the full log for details
Error   : ------------------------------
```
but Feel++ doesn't pick that up.
