### ISSUE TITLE
Support assembly PˆT A P 

### ISSUE THREAD

**Issue by prudhomm** [feelpp/feelpp#492]
@feelpp/po we should support the assembly of `P^T A P` for the curl eigen value problem. This operation is supported at least by PETSc

**Comment by prudhomm** [comment]
@romainhild we should add a test in feel++ for this feature. Could you propose a test for testsuite/feelalg ?

**Comment by prudhomm** [comment]
@romainhild it should be closed no ?

**Comment by prudhomm** [comment]
@romainhild it should be closed no ?

**Comment by romainhild** [comment]
Yes it works.
