### ISSUE TITLE
Lots of FTBS inside benchmarks/perf and doc

### ISSUE THREAD

**Issue by prj-** [feelpp/feelpp#500]
As everything is being set up for the v0.100 release, it might be a good idea to fix (most of) the benchmarks inside the folder `benchmarks/perf`. At least the following files don't compile:
* [ ] bench1_run1d.cpp
* [ ] laplacian/feel_perf_laplacian_Simplex_3D_Lagrange_5.cpp
* [x] stokes/stokes_kovaznay.cpp
* [ ] dar/feel_perf_dar_Simplex_2D_Lagrange_1_Continuous.cpp

**Comment by vhuber** [comment]
List of code that does not compile :

- [ ] benchmarks/curl/curl.hpp (3D only): expressions lines 239 and 246 seems to be misswritten.
- [ ] benchmarks/perf/stokes/stokes_kovaznay.cpp `288:10: error: no matching function for call to 'straightenMesh'`
- [ ] doc/manual/laplacian/laplacian_lagrange_multiplier.cpp: `auto Vh = space_type::NewFromList( X1, X2 );`
- [ ] benchmarks/navierstokes/stokes/sphere.cpp : `95:16: error: no matching function for call to 'straightenMesh' `

**Comment by prudhomm** [comment]
look at the new prototype for `straightenMesh` in eg `createGmshMesh` to fix these issues

**Comment by vhuber** [comment]
Do we have to make `doc/manual/ns/bs.cpp` run ?
