### ISSUE TITLE
printMatlab : The script should not have the same name than the variable

### ISSUE THREAD

**Issue by romainhild** [feelpp/feelpp#501]
Contrary to Octave, in Matlab, trying to execute a script which results from `printMatlab` leads to : 
```
The variable "a" is also the name of this script.
 This is illegal, because it will be the name of a script and a variable
 in any context from which the script is called.
```
It is enough to rename the script so it's not hard to get rid of the error, but it's not the expected behavior.

Could we add a parameter to `printMatlab` to define the name of the variable/script ? Maybe with a default value to keep the consistency with older code.

**Comment by prudhomm** [comment]
please do it for the v100

**Comment by vhuber** [comment]
@romainhild Is that issue solved ?

**Comment by romainhild** [comment]
For me it is ok.
I close the issue.
