### ISSUE TITLE
Turek compile failed, Please help

### ISSUE THREAD

**Issue by grabbitnu** [feelpp/feelpp#504]
Hi. I tried to compile benchmark/bavierstokes/turek with libFeel++0.99-dev (Ubuntu launchpad packaage), it failed with following info.

It looks Data::Inflow:operator()(...) should return a double-type velocity component from the parabolic expression, but the actual returned one is an expression.
Anyone can give me a hint to correct this ? 

Thank you very much!

Zhenyu

BTW, since turek is a very nice demo of navier-stokes solver for beginners like myself, I also tried to compile it with Feel++ 0.98. Failed as well but due to other error such as incompatibility of template member fucntions between different Feel++ versions. Therefore, I copied the source from the .tar.gz of 0.99 and compile it with libfeelpp0.99-dev. Then I got the above questions. 

zhenyu@amax1:~/work/feel_testcodes/turek/build$ make
Scanning dependencies of target feelpp_turek
[ 33%] Building CXX object CMakeFiles/feelpp_turek.dir/turekapp.cpp.o
[ 66%] Building CXX object CMakeFiles/feelpp_turek.dir/data.cpp.o
In file included from /home/zhenyu/work/feel_testcodes/turek/src/data.cpp:37:
In file included from /home/zhenyu/work/feel_testcodes/turek/src/turek.hpp:44:
/usr/include/feel/feeldiscr/bdf2.hpp:32:2: warning: This file includes at least one deprecated or antiquated header Please include <feel/feeldiscr/bdf.hpp> instead. [-W#warnings]
# warning This file includes at least one deprecated or antiquated header \

 ^
In file included from /home/zhenyu/work/feel_testcodes/turek/src/data.cpp:37:
In file included from /home/zhenyu/work/feel_testcodes/turek/src/turek.hpp:44:
In file included from /usr/include/feel/feeldiscr/bdf2.hpp:35:
/usr/include/feel/feeldiscr/bdf.hpp:27:2: warning: This file includes at least one deprecated or antiquated header Please include <feel/feelts/bdf.hpp> instead. [-W#warnings]
# warning This file includes at least one deprecated or antiquated header \

 ^
/home/zhenyu/work/feel_testcodes/turek/src/data.cpp:743:20: error: no viable conversion from 'Expr<vf_div<Cst<double>, ExprFeel::vf::Pow<Feel::vf::Cst<double, Feel::vf::Cst<int> > > > >' to 'double'
            return 4_M_data.Um()_p[1]_( M_data.H()-p[1] )_time_term/pow( M_data.H(),2 );
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/zhenyu/work/feel_testcodes/turek/src/data.cpp:758:20: error: no viable conversion from 'Expr<vf_div<Cst<double>, ExprFeel::vf::Pow<Feel::vf::Cst<double, Feel::vf::Cst<int> > > > >' to 'double'
            return 16_M_data.Um()_p[1]_( M_data.H()-p[1] )_p[2]_( M_data.H()-p[2] )_time_term/pow( M_data.H(),4 );
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
## 2 warnings and 2 errors generated.

**Comment by prudhomm** [comment]
dear @grabbitnu sorry for the late answer. the benchmark is quite old and the code unmaintained.
may I suggest that you use the navier-stokes code in quickstart and adapt it for the turek benchmark.
We could do it too but I do not know when we have the time

**Comment by grabbitnu** [comment]
I am sorry coz I noticed your reply just now. Anyway, many thanks for your hints.

**Comment by vhuber** [comment]
@prudhomm As long as the code is unmaintained, I guess the issue can be closed ?
