### ISSUE TITLE
Problem in macro FEELPP_VERSION_GREATER_THAN

### ISSUE THREAD

**Issue by romainhild** [feelpp/feelpp#514]
There seems to be a problem with that, I added the following lines in my program,
```c++
    std::cout << Info::versionString() << std::endl;
    std::cout << Info::version() << std::endl;
    if ((Info::versionMajor() > 0 ||                                  \
         (Info::versionMajor() == 0 && (Info::versionMinor() > 99 || \
                                              (Info::versionMinor() == 99 && \
                                               Info::versionMicro() > 2)))) ? 1 : 0)
    {
        std:: cout << "version > 0.99.2\n";
    }
#if FEELPP_VERSION_GREATER_THAN(0,99,2)
        std::cout << "VERSION > 0.99.2\n";
#else
        std::cout << "VERSION <= 0.99.2\n";
#endif
```
And the output is : 
```
0.100.0-beta.10
51200
version > 0.99.2
VERSION <= 0.99.2
```

**Comment by prj-** [comment]
I tried to reproduce your result and printed the values of FEELPP_VERSION_MAJOR, FEELPP_VERSION_MINOR, and FEELPP_VERSION_MICRO. They are currently set to FEELPP_VERSION_MAJOR, FEELPP_VERSION_MINOR, and FEELPP_VERSION_MICRO, instead of 0, 100, and 0. Something must be wrong with cmake which is, correct me if I'm wrong, in charge of setting the proper values for these macros. There is nothing wrong with the macro FEELPP_VERSION_GREATER_THAN itself.

**Comment by romainhild** [comment]
This is weird because versionString() seems to work and it uses FEELPP_VERSION_M... : 
```c++
char const*
Info::versionString()
{
    return stringize( FEELPP_VERSION_MAJOR ) "." stringize( FEELPP_VERSION_MINOR ) "." stringize( FEELPP_VERSION_MICRO )  stringize(FEELPP_VERSION_PRERELEASE) stringize(FEELPP_VERSION_METADATA) stringize(FEELPP_BUILDID);
}
```
and output `0.100.0-beta.10`

**Comment by prj-** [comment]
The values of the macros are not evaluated at the same time by the preprocessor.
If you want to fix your problem, at the beginning of your application, just `#include "path_to_your_feelpp_build_directory/feel/feelinfo.h"`. You can see that the macros are defined inside this file: when `versionString` is compiled by the library, this file is included and the value returned is OK, in your application, it is not included (I don't know if this is the wanted behavior), the preprocessor values are unknown at compile-time, and so you don't get the desired value for FEELPP_VERSION_GREATER_THAN.

**Comment by romainhild** [comment]
Ok including `feelinfo.h` works for me. Thanks.
Is this the normal behavior or should I let the issue open ?

**Comment by prj-** [comment]
I don't know, let's leave it open until one of the @feelpp/owners has a look at it.

**Comment by vincentchabannes** [comment]
Probably add #include <feel/feelinfo.h> in a main header of feel (like feel/feelcore/feel.hpp) must fix the issue

**Comment by prj-** [comment]
Sure, but the question really is: do you want to expose `feelinfo.h` to everyone, or do you rather want people to use `Info::version()` and such ?
If you choose the former, it might be a good idea to add an #include guard into `feelinfo.h.in`.
