### ISSUE TITLE
Feel++ for Ubuntu 14.10

### ISSUE THREAD

**Issue by grabbitnu** [feelpp/feelpp#515]
Dear all,

Is it possible to distribute a Feel++ for Ubuntu 14.10? The current Launchpad one only support 14.04.
Under Ubuntu, incompatibility of libboost appeared for libfeel++1 and libfeel++-dev. The first depends on libboost 1.54 and the second on libboost-dev (which is 1.55 by default)

Bye the way when I downloaded the release .tar.gz file and run "cmake ../feel-xxx" to generate the cmake scripts for feel++ <=0.99, the procedure is always  broken due to errors like:
fatal: Not a git repository (or any parent up to mount point /home)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
-- Git submodule contrib/nlopt updated.
touch: cannot touch ‘swig/nlopt.scm.in’: No such file or directory
autoreconf: 'configure.ac' or 'configure.in' is required
autoreconf: 'configure.ac' or 'configure.in' is required
CMake Error at cmake/modules/feelpp.module.nlopt.cmake:66 (message):
  configure not available
Call Stack (most recent call first):
  cmake/modules/FindFeel++.cmake:442 (include)
  CMakeLists.txt:296 (FIND_PACKAGE)
-- Configuring incomplete, errors occurred!
See also "/home/zhenyu/opencode/feelpp/codes/build/CMakeFiles/CMakeOutput.log".
See also "/home/zhenyu/opencode/feelpp/codes/build/CMakeFiles/CMakeError.log".
Please check it if possible

Thanks first

**Comment by prudhomm** [comment]
packages for 14.10 should be available very very soon

**Comment by grabbitnu** [comment]
Very Good News! So thank you very much. We are looking forward to it.

**Comment by vhuber** [comment]
@grabbitnu You should consider building Feel++ without nlopt :
```
cmake ../feelpp-xxx -DFEELPP_ENABLE_NLOPT=FALSE
```
