### ISSUE TITLE
FindPETSc.cmake is broken with PETSc > 3.5.2

### ISSUE THREAD

**Issue by prj-** [feelpp/feelpp#516]
In the upcoming PETSc release (that can be retrieved using the `next` branch of https://bitbucket.org/petsc/petsc), the location of `petscrules` and `petscvariables` has changed. In its current version, `FindPETSc.cmake` does not support the new scheme.

**Comment by prudhomm** [comment]
@prj- could you point out the specific changes ? I couldn't find anything in the commits.

**Comment by prj-** [comment]
I don't know the specifics, but it has been discussed here http://lists.mcs.anl.gov/pipermail/petsc-dev/2015-January/016712.html and here http://lists.mcs.anl.gov/pipermail/petsc-dev/2015-January/016759.html. It looks like those files are now in `$PETSC_DIR/$PETSC_ARCH/lib/petsc-conf/`.

**Comment by milicchio** [comment]
Hello, I am having the same issue in trying to compile feelpp. I can add my [gist log](https://gist.github.com/anonymous/9f46d29c779a230bbc6a), and recommendation from homebrew's petsc info:

```
==> Caveats
    Set PETSC_DIR to /usr/local/Cellar/petsc/3.5.3_2/real or /usr/local/Cellar/petsc/3.5.3_2/complex.
    Fortran module files are in
      /usr/local/Cellar/petsc/3.5.3_2/real/include and /usr/local/Cellar/petsc/3.5.3_2/complex/include
```

I hope it can be resolved soon, I'm really eager to try feelpp!

**Comment by prj-** [comment]
We might want to ping @jedbrown to update his repository https://github.com/jedbrown/cmake-modules. I guess the FindPETSc.cmake of Feel++ comes from there, and it is likely that all other software that rely on PETSc and cmake will eventually face this issue.
