### ISSUE TITLE
Gmsh header lost

### ISSUE THREAD

**Issue by grabbitnu** [feelpp/feelpp#517]
I just installed feel++-dev 0.100.3 on Utopic from Lauchpad PPA
The default version of gmsh is 2.8.3 for Ubuntu 14.10
When making my code with Feel++, errors pop up with information that
BasisFactory.h not found. 

I suppose Feel++-dev 0.100 is built with gmsh > 2.8.4, Yes?

**Comment by vhuber** [comment]
Hello :-)

I've just installed a VM Ubuntu 14.10 and installed :
- feel++-apps 
- libfeel++-dev
- clang-3.5
- cmake

I have done: 
```
git clone https://github.com/feelpp/quickstart
(... few modification to the CMakeListst.txt to make it run ... )
mkdir build; cd build
cmake -DCMAKE_CXX_COMPILER=`which clang++` -DCMAKE_C_COMPILER=`wich clang` 
make feelpp_qs_laplacian
./feelpp_qs_laplacian
```

I do not face your problem.
Actually, I've found on my system:
```
/usr/include/feel/gmsh/BasisFactory.h
```

I suggest you to try this:
```
apt-get update
apt-get upgrade
apt-get install --reinstall libfeel++-dev
```

Let me know if that fix your problem.

**Comment by grabbitnu** [comment]
Well I rebuild gmsh 2.8.5 myself and build feel++ 0.100 from source package. 
Then I installed both in one folder under my own path.
Now it works. So I guess the reason is the default version of gmsh on Ubuntu 14.10 is 2.8.3, which is slightly deffirent from 2.8.5

**Comment by grabbitnu** [comment]
feelpp_qs_laplacian work now. But There is no /usr/include/feel/gmsh/BasisFactory.h for my Ubuntu indeed. Dont know why. The above error rise coz I included <feel/.../loadmesh.h> So finally it requires BasisFactory.h. 
Now I installed my own gmsh 2.8.5, no error

**Comment by vhuber** [comment]
Have you updated/upgraded via apt as I recommended ?

**Comment by grabbitnu** [comment]
I tried and no difference. I think the Ubuntu provided libgmsh-dev 2.8.3 does not have that header.

in include/feel/feelfilters/importergmsh.hpp,
#if defined( FEELPP_HAS_GMSH_H )
#include <GModel.h>
#include <MElement.h>
#include <MVertex.h>
#include <MEdge.h>
#include <MPoint.h>
#include <MLine.h>
#include <MTriangle.h>
#include <MQuadrangle.h>
#include <MTetrahedron.h>
#include <MHexahedron.h>
#endif

Here /usr/include/gmsh/MPoint.h may require BasisFactory.h, depending FEELPP_HAS_GMSH_H
I am not sure if a successful build of feel++ means FEELPP_HAS_GMSH_H=off or not.
Anyway, in my case. at least when I run cmake ../$feel_src_sir, I got first
[feelpp] GMSH NOT FOUND
and then /usr/include/gmsh was found . Quite strange.

**Comment by prj-** [comment]
You are right, cf. http://packages.ubuntu.com/utopic/amd64/libgmsh-dev/filelist, but I think Feel++ installs a different version of libgmsh-dev than the one from the official package, doesn't it @vhuber ?

**Comment by vhuber** [comment]
@prj- Feel++ does not install an other version of `libgmsh-dev`
Actually, I have this:
```
ii  libgmsh-dev                                           2.8.3+dfsg-4ubuntu2                                 amd64        Three-dimensional finite element mesh generator. Development files
ii  libgmsh2:amd64                                        2.8.3+dfsg-4ubuntu2                                 amd64        Three-dimensional finite element mesh generator. Shared library
```
Thus, we have the same `libgmsh-dev` version.

The file you are looking is provided by `libfeel++-dev`:
```
dpkg-query -L libfeel++-dev | grep BasisFactory.h
/usr/include/feel/gmsh/BasisFactory.h
```

As long as `BasisFactory.h` ***is NOT*** provided by `libfeel++-dev 0.98`, see [here](http://packages.ubuntu.com/utopic/amd64/libfeel++-dev/filelist) I recommend you to check :
- The libfeel++-dev package version you have installed `dpkg -l feel++`
- The presence of the file `/usr/include/feel/gmsh/BasisFactory.h`
- The value of the `$FEELPP_DIR`. If that variable is set, then remove it and try a new cmake process.

Please, let me know if that fix your problem.

**Comment by prudhomm** [comment]
`BasisFactory.h` is a required Gmsh header to compile the interface between Feel++ and Gmsh but unfortunately is not installed properly by Gmsh Debian/Ubuntu packages. That's why it was shipped with Feel++

**Comment by vhuber** [comment]
@prudhomm It seems that the one who install Feel++ (make install, apt-get install ...) and define FEELPP_DIR face that problem.
I guess we have to add 
```
/usr/include/feel/gmsh/
/usr/local/include/feel/gmsh/
```
to the FIND_PATH line 35 (or remove the NO_DEFAULT_PATH) but I wonder the reason one use NO_DEFAULT_PATH before changing it.

**Comment by prudhomm** [comment]
It is because we do not want to override the system headers.
from feelpp.module.gmsh.cmake
```
  FIND_PATH(GMSH_CONTRIB_INCLUDE_DIR BasisFactory.h
    $ENV{FEELPP_DIR}/include/feel/gmsh
    NO_DEFAULT_PATH)
  FIND_PATH(GMSH_CONTRIB_INCLUDE_DIR BasisFactory.h
    PATH_SUFFIXES feel/gmsh )
  include_directories(${GMSH_CONTRIB_INCLUDE_DIR})
```
the first `find_path` tries to locate the header if feel++ is installed in a non standard directory then it check in standard directories by adding the  `PATH_SUFFIXES feel/gmsh` 
@grabbitnu what is the value of `GMSH_CONTRIB_INCLUDE_DIR` in the cmake cache ?

**Comment by vhuber** [comment]
@grabbitnu Can we close that issue ?

**Comment by vhuber** [comment]
@grabbitnu Without answer from your side, I close this issue.
