### ISSUE TITLE
Hcurl x Pch

### ISSUE THREAD

**Issue by vhuber** [feelpp/feelpp#523]
Creating cross product between HCurl and Pch (or Pchv) does not compile.

```
typedef FunctionSpace<mesh_type, bases< Nedelec<0, NedelecKind::NED1>, Lagrange<1,Scalar> > space_type;
[...]
space_ptrtype Xh = space_type::New(mesh);
auto A1 = Xh -> element();
auto A2 = Xh -> element();
A1 = vf::project(Xh,elements(mesh),idv(A2) );
```

**Comment by romainhild** [comment]
I use the same space without problem : 
```c++
    typedef Nedelec<0, NedelecKind::NED1> basis_edge_type;
    typedef Lagrange<1,Scalar> basis_vertex_type;
    typedef bases<basis_edge_type, basis_vertex_type> basis_type;
    typedef FunctionSpace<mesh_type, basis_type> space_type;
```
But I recall that at a moment, I had a problem and I "solved" it by swapping the order in which I declare the bases, instead of `FunctionSpace<mesh_type, bases< Nedelec<0,NedelcKin::NED1>, Lagrange<1,Scalar> >`, I used `FunctionSpace<mesh_type, bases<  Lagrange<1,Scalar>, Nedelec<0,NedelcKin::NED1> >` and it worked...

**Comment by romainhild** [comment]
In your code there is `NedelcKin::NED1`. Is it just when you copy the code ?

**Comment by vincentchabannes** [comment]
You can't do a projection on a composite space.
The main problem is  idv( compositefield ) which not make sense.
You need to do the projection on each subspace

**Comment by vhuber** [comment]
What do you mean "It does not make sense" ?

**Comment by prudhomm** [comment]
the interpolant for a composite element is not implemented, you have to do it subspace by subspace
it could probably be implemented at some point but it can be quite technical because for each subspace the interpolant may be different (e.g. nedelec vs lagrange)

**Comment by vhuber** [comment]
I guess I have a problem then.
At some point, in the stationary ferromagnetic formulation, I have to add in the bilinear form :
```
// Trial
auto U = Xh->element();
auto u = U.element<0>(); // Nedelec
auto phi = U.element<1>(); // Lagrange - scalar
// Test
auto V = Xh->element();
auto v = V.element<0>(); // Nedelec
auto psi = V.element<1>(); // Lagrange - scalar
// [...] here some code [...]
a += integrate(elements(mesh), inner(idv(v),gradt(phi) ));
// [...] here some code [...]
```

If I do understand, it is not possible to write something like that, isn't it ?
Thus, How can I do it ?

**Comment by vincentchabannes** [comment]
No, here it's good because you have id( ) or grad( ) with non composite field!
I say not sense because if the your compositefield is composed of a tensor2 and a vector fields, what is the dimension of idv( U)? Or gradv(U) with U=velocty/pressure for exemple , what is the dimension of gradv(U).

**Comment by vhuber** [comment]
I do understand the non sens for `gradv(U)` but `idv` make sense to me: you only evaluate for each dof.

**Comment by prudhomm** [comment]
It is not as simple as evaluation of an expression, you have at least the geometric transformation to take into account for Lagrange element. For Nedelec you don't evaluate the expression but rather the integral of the tangential component of the expression over each edge of the mesh (for lowest order and it gets messier for higher orders). The interpolants are  not the same between the finite elements, you have to take into account the definition of each finite element.

**Comment by prudhomm** [comment]
why don't you write `A1=A2`? it is simpler and easier to understand  no ?
as to
```
// Trial
auto U = Xh->element();
auto u = U.element<0>(); // Nedelec
auto phi = U.element<1>(); // Lagrange - scalar
// Test
auto V = Xh->element();
auto v = V.element<0>(); // Nedelec
auto psi = V.element<1>(); // Lagrange - scalar
// [...] here some code [...]
a += integrate(elements(mesh), inner(id(v),gradt(phi) ));
// [...] here some code [...]
```
it depends on the definition of `a`, it has to be a bilinear form from `Xh(test) x Xh(trial)` to `R` or from `Xh<0> (test) x Xh<1>(trial)` otherwise you have a problem

**Comment by vhuber** [comment]
Actually, for the bilinear form a (Xh,Xh), the problem was that Nedelec elements are not vertical but horizontal. thus:
```
a += integrate(elements(mesh), inner(trans(id(v)),gradt(phi) ));
```

**Comment by prudhomm** [comment]
no they are col vectors, grad are by convention row vectors
for inner both left and right objects must have the same shape
either trans on left or right
