### ISSUE TITLE
Get a function from a VectorPetsc

### ISSUE THREAD

**Issue by romainhild** [feelpp/feelpp#524]
What I need to is : 
```c++
auto fNh  = Nh->element();
auto tmpNh = backend()->newVector( Nh );
...[fill tmpNh]...
fNh = *tmpNh;
```
However, while it is working in sequential, in parallel `fNh` stays empty.
Any idea why ? Or any other way to do this ?

**Comment by vincentchabannes** [comment]
For this moments, we need to call tmpNh->close() in our code after the filling of vector.
This call update the values of // vector into a local vector (containing also the values of ghost dof).
And this is the local vector which is used in last operator=.

**Comment by romainhild** [comment]
Indeed it works.
Thanks !
