### ISSUE TITLE
Load several config files

### ISSUE THREAD

**Issue by vincentchabannes** [feelpp/feelpp#525]
add an option  --config-files allowing to load several cfg files
./myexec --config-files toto.cfg toto2.cfg toto3.cfg

in case where some options are duplicated in the files, the priority is given at the end.
toto3.cfg can overwrite toto2.cfg and toto.cfg
toto2.cfg can overwrite toto.cfg

All files in --config-files can overwrite options given by the classic --config-file.
And all options in command line can overwrite all cfg files.

**Comment by vhuber** [comment]
Thank you :-)
May you please comment this for the doc ?
Please find it [here](http://www.feelpp.org/docs/develop/TutorialEnv.html#Config)

**Comment by vincentchabannes** [comment]
Ok, I will try!

**Comment by vhuber** [comment]
Using this option does not generate the correct value for the `$cfgdir` variable set by #391, see [here](https://github.com/feelpp/feelpp/blob/develop/feel/feelcore/environment.cpp#L1219).

There is various methods to fix that, we have to choose one.

**Comment by prudhomm** [comment]
what happens exactly ? could you post an example ?

**Comment by vhuber** [comment]
the `S_cfgdir` is simply not set.
I have in `a.cfg`:
`myModel=$cfgdir/tws.mod`
and I run :
```sh
./feelpp_myApp --config-files a.cfg b.cfg
```
and I got:
```
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::property_tree::json_parser::json_parser_error> >'
  what():  /tws.mod: cannot open file
```
