### ISSUE TITLE
Problem inside createGMSHMesh

### ISSUE THREAD

**Issue by prj-** [feelpp/feelpp#526]
It seems that the behavior of `createGMSHMesh` and `loadMesh` are not the same. `createGMSHMesh` will generate a .geo file where `Mesh.NbPartitions` is always equal to `Environment::globalSize()`, whereas `loadMesh` generates a file with the correct value for `Mesh.NbPartitions` (depending on the communicator used to define the mesh).

Also, why is there a parameter `_worldcomm` inside `createGMSHMesh` and `loadMesh` ? Isn't it possible to retrieve the communicator used to define the parameter `_mesh` ?

**Comment by prudhomm** [comment]
reopen
