### ISSUE TITLE
Improve support for slepc 

### ISSUE THREAD

**Issue by prudhomm** [feelpp/feelpp#527]
@romainhild we are going to improve the support for slepc and its option in feel++ and have something like we have for standard linear algebra problems

**Comment by romainhild** [comment]
The following options should be supported : 
- [eps_mpd](http://slepc.upv.es/documentation/current/docs/manualpages/EPS/EPSSetDimensions.html)
- [eps_interval](http://slepc.upv.es/documentation/current/docs/manualpages/EPS/EPSSetInterval.html)
- [eps_krylovschur_partitions](http://slepc.upv.es/documentation/current/docs/manualpages/EPS/EPSKrylovSchurSetPartitions.html)

To implement `eps_interval`, we need to set the type to GHEP, the spectral transformation to SINVERT, the solver to KRYLOVSCHUR, the spectrum to EPS_ALL, get the [KSP](http://slepc.upv.es/documentation/current/docs/manualpages/ST/STGetKSP.html#STGetKSP) and set the ksp_type to preonly and the pc_type to cholesky.
We also need to add the possibility to use mumps for the preconditioner. 
An example is available [here](http://slepc.upv.es/documentation/current/src/eps/examples/tutorials/ex25.c.html).

**Comment by romainhild** [comment]
we also need to add `-eps_target` which is used for the shift

**Comment by prudhomm** [comment]
@romainhild should be closed no ?

**Comment by romainhild** [comment]
Indeed, the main options are supported.
I guess we could support other types of eigen problems (nonlinear or polynomial are now supported by slepc) but they can have their own issue whenn needed.
