### ISSUE TITLE
Linking fails for high-order geometries with hypercube elements 

### ISSUE THREAD

**Issue by asamake** [feelpp/feelpp#528]

**Comment by prudhomm** [comment]
What is the error message?

**Comment by asamake** [comment]
The error message is:

référence indéfinie vers « boost::shared_ptr<Feel::Mesh<Feel::Hypercube<(unsigned short)2, (unsigned short)2, (unsigned short)2>, double, 0> > Feel::straightenMesh<Feel::Mesh<Feel::Hypercube<(unsigned short)2, (unsigned short)2, (unsigned short)2>, double, 0> >(boost::shared_ptr<Feel::Mesh<Feel::Hypercube<(unsigned short)2, (unsigned short)2, (unsigned short)2>, double, 0> >, Feel::WorldComm const&, bool, bool) »
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [doc/manual/laplacian/feelpp_doc_laplacian_bean] Erreur 1
make[2]: *** [doc/manual/laplacian/CMakeFiles/feelpp_doc_laplacian_bean.dir/all] Erreur 2

**Comment by prudhomm** [comment]
You have to include straightenmesh_impl.hpp

**Comment by asamake** [comment]
Thanks.
