### ISSUE TITLE
eigenPair : each call erase previous eigen functions 

### ISSUE THREAD

**Issue by romainhild** [feelpp/feelpp#533]
It seems that all the functions are set to the last one computed. 
If I compute the error between `A*x-lambda*B*x` with : 
```c++
    auto modes = eigs( _matrixA=aHat,
                       _matrixB=bHat,
                       _solver=(EigenSolverType)EigenMap[soption("solvereigen.solver")],
                       _problem=(EigenProblemType)EigenMap[soption("solvereigen.problem")],
                       _transform=(SpectralTransformType)EigenMap[soption("solvereigen.transform")],
                       _spectrum=(PositionOfSpectrum)EigenMap[soption("solvereigen.spectrum")]
                       );
    for( auto const& mode: modes )
    {
        auto tmp1 = backend()->newVector( aHat->mapRowPtr());
        auto tmp2 = backend()->newVector( aHat->mapRowPtr());
        aHat->multVector(boost::get<2>(mode.second), tmp1);
        bHat->multVector(boost::get<2>(mode.second), tmp2);
        tmp1->add(-boost::get<0>(mode.second), tmp2);
        auto n = tmp1->linftyNorm();
        if(Environment::isMasterRank())
            std::cout << "norm = " << n << std::endl;
```
For the last eigenpair, the error is in the order of 1e-12, whereas for the others, it is between 1e-1 and 1e-4.
Note that the eigen**values** are set correctly, but all the eigenfunctions are identical.

I also use the SLEPc option `st_shift`.

**Comment by romainhild** [comment]
It happens when `matA` is `trans(curlt(u))*curl(v)` or `inner(gradt(u),grad(v))`.
In these cases, the problem has some null eigenvalues, and we need to use the option `st_shift` to shift the eigenvalues found.

**Comment by prudhomm** [comment]
sure  it is normal that they have 0 eigenvalues if you have only neumann boundary conditions
the constants are in the kernel at least for grad.grad and for the curl the kernel contains the grad of scalar field (solution up to the gradient of a scalar field)

**Comment by romainhild** [comment]
Yes I'm ok with that.
But the problem is in the eigen functions returned. If I compare them, they are all equal to the last one : 
>eigenvalue 0 = (3.44968e-12,0)
norm = 0.189993
eigenvalue 1 = (4.55337e-10,0)
norm = 0.189993
eigenvalue 2 = (-7.55076e-10,0)
norm = 0.189993
eigenvalue 3 = (7.6018,0)
norm = 0.0944538
eigenvalue 4 = (7.60235,0)
norm = 0.094447
eigenvalue 5 = (7.6031,0)
norm = 0.0944375
eigenvalue 6 = (15.1051,0)
norm = 0.000153433
eigenvalue 7 = (15.1074,0)
norm = 0.000123489
eigenvalue 8 = (15.1108,0)
norm = 8.10889e-05
eigenvalue 9 = (15.1157,0)
norm = 1.9446e-05
eigenvalue 10 = (15.1173,0)
norm = 4.14565e-12

Where norm is the max of the absolute value of A*x-lambda*B*x.
You can see that the last one is null but not the others

**Comment by prudhomm** [comment]
@romainhild I am working on that now. I will check eigen value problems in doc manual

**Comment by romainhild** [comment]
Thanks.
On my side, I exported the matrices in matlab, resolved the eigen problem in it and import the functions in feelpp. The errors in this case are all in the order 1e-8. 
So it seems that there is indeed a problem with the eigenfunctions. Either in feelpp or in SLEPc.

**Comment by prudhomm** [comment]
@romainhild I cannot reproduce on the examples in `doc/manual/eigen/`
for example `ge_laplacian`generates the proper eigen modes 
could you write a testcase for the testsuite ?

**Comment by romainhild** [comment]
Ok, is there some template I can use to write the test case ?
Also, if I need to use some options that are not implemented in feelpp (`-st_shift` for example) how can I do that ?

**Comment by romainhild** [comment]
If you run the test with `--log_level=all`, you can see that only the last check succeed, and that, regardless of the number of eigenpairs you ask.

Also, I have a segmentation fault at the end, and I don't know where it is coming from. Is there something to do in particular to end properly the test ?

**Comment by prudhomm** [comment]
@romainhild something we have that with petsc and mumps, it is not directly in feel++.

FYI I use now petsc 3.5.3 and slepc 3.5.3 (see /data/software)

**Comment by romainhild** [comment]
In /data/software, I have indeed the 3.5.3 versions, but using `-v 1`, it seems that I use the versions 3.4.2 : 
```
Petsc Release Version 3.4.2, Jul, 02, 2013 
       The PETSc Team
    petsc-maint@mcs.anl.gov
 http://www.mcs.anl.gov/petsc/
See docs/changes/index.html for recent updates.
See docs/faq.html for problems.
See docs/manualpages/index.html for help. 
Libraries linked from /tmp/petsc-3.4.2.dfsg1/linux-gnu-c-opt/lib
```
It is on atlas, where I clone the feelpp repository.
How can I use the version 3.5.3 ?

**Comment by prudhomm** [comment]
you have to set `PETSC_DIR` and `SLEPC_DIR`to `/data/software/petsc-3.5.3` and `/data/software/slepc-3.5.3` respectively before configuring

**Comment by romainhild** [comment]
I now use petsc and slepc 3.5.3 but I still have the errors : 
```
/home/u2/hild/feelpp/testsuite/feelalg/test_eigenmode.cpp(65): error in "test_0": difference{34.8222%} between AvNorm{4.7112774728932552} and BvNorm{3.494438454751875} exceeds 1e-08%
/home/u2/hild/feelpp/testsuite/feelalg/test_eigenmode.cpp(65): error in "test_0": difference{0.142133%} between AvNorm{4.7112774728932552} and BvNorm{4.7045907010545243} exceeds 1e-08%
/home/u2/hild/feelpp/testsuite/feelalg/test_eigenmode.cpp(65): error in "test_0": difference{0.0495343%} between AvNorm{4.7112774728932552} and BvNorm{4.7089449318102936} exceeds 1e-08%
/home/u2/hild/feelpp/testsuite/feelalg/test_eigenmode.cpp(65): info: difference{%} between AvNorm{4.7112774728932552} and BvNorm{4.7112774728834896} doesn't exceed 1e-08%
```

**Comment by romainhild** [comment]
I build feelpp/po@5b852b5, which do essentially the same as the test case, by cloning the feelpp repository and by using the install on atlas.
In the latter, I have 0 eigenpairs, which could explain why there is no problem with the test case.
Whereas with the former, I retrieve the 15 eigenvalues requested.

Can you see how many eigenpairs you have in the test case (with `--log_level=message`) ?

**Comment by romainhild** [comment]
It seems that there is indeed a bug. 
By moving the portion of code that check the error
```c++
    for(int i = 0; i<nconv; i++)
    {
        auto pair = eigen->eigenPair(i);
        auto v = boost::get<2>(pair);
        auto s = v->size();
        auto l = boost::get<0>(pair);
        auto Av = boost::shared_ptr<Vector<double> >(new VectorPetsc<double>(s,s));
        auto Bv = boost::shared_ptr<Vector<double> >(new VectorPetsc<double>(s,s));
        matrixA->multVector(v, Av);
        matrixB->multVector(v, Bv);
        Av->add(-l, Bv);
        auto errr = Av->l2Norm();
        auto errRel = errr / v->l2Norm();
        if( Environment::isMasterRank())
            std::cout << "eigenpair : " << i << "( " << l << " )" << std::endl
                      << "||A x - lambda B x|| = " << errr << std::endl
                      << "||A x - lambda B x|| / ||x|| = " << errRel << std::endl;
    }
```
into the `eigs` function in [solvereigen.cpp](https://github.com/feelpp/feelpp/blob/develop/feel/feelalg/solvereigen.hpp#L495-554) I have now the expected errors : 
>eigenpair : 5( -1.28818e-08 )
||A x - lambda B x|| = 2.44231e-08
||A x - lambda B x|| / ||x|| = 6.87516e-09
eigenpair : 6( 7.67507 )
||A x - lambda B x|| = 3.82072e-10
||A x - lambda B x|| / ||x|| = 8.76605e-11
eigenpair : 7( 7.67926 )
||A x - lambda B x|| = 1.01705e-09
||A x - lambda B x|| / ||x|| = 2.3504e-10
eigenpair : 8( 7.6817 )
||A x - lambda B x|| = 1.80072e-09
||A x - lambda B x|| / ||x|| = 4.1737e-10

So either in `eigenModes()`, or somewhere else, I can't see.

**Comment by romainhild** [comment]
In `eigs` function in [solvereigen.cpp](https://github.com/feelpp/feelpp/blob/develop/feel/feelalg/solvereigen.hpp#L495-554) I did the following : 
```c++
    for(int i = 0; i<nconv; i++)
    {
        auto pair = eigen->eigenPair(i);
        auto v = boost::get<2>(pair);
        auto s = v->size();
        auto l = boost::get<0>(pair);
        auto Av = boost::shared_ptr<Vector<double> >(new VectorPetsc<double>(s,s));
        auto Bv = boost::shared_ptr<Vector<double> >(new VectorPetsc<double>(s,s));
        matrixA->multVector(v, Av);
        matrixB->multVector(v, Bv);
        Av->add(-l, Bv);
        auto errr = Av->l2Norm();
        auto errRel = errr / v->l2Norm();
        if( Environment::isMasterRank())
            std::cout << "eigenpair : " << i << "( " << l << " )" << std::endl
                      << "||A x - lambda B x|| = " << errr << std::endl
                      << "||A x - lambda B x|| / ||x|| = " << errRel << std::endl;
    }

    auto m = std::vector<SolverEigen<double>::eigenpair_type>(nconv);
    for(int i = 0; i<nconv; i++)
        m[i] = eigen->eigenPair(i);
    for(int i = 0; i<nconv; i++)
    {
        auto pair = m[i];
        ...
```
and the first loop computs null errors whereas the last one computs the same errors as before (only the last one is ok).
So it seems that `eigenPair(i)` is erasing at each call the previous eigenfunction.
Can you reproduce this behavior ?

**Comment by vhuber** [comment]
@romainhild test fails.
See [here](http://my.cdash.org/testDetails.php?test=18762601&build=740472)

**Comment by romainhild** [comment]
you have to use `-st_shift 15` or `-eps_target 15` command line options to avoid the zero pivot.

**Comment by vhuber** [comment]
Maybe. Please add theses options to the test to make it run on cdash :-)

**Comment by romainhild** [comment]
How can I do that ? These options are not interfaced into feelpp. I can not add them to config file, or programmatically.

**Comment by romainhild** [comment]
If I replace these [lines](https://github.com/feelpp/feelpp/blob/develop/feel/feelalg/solvereigenslepc.cpp#L734-738) in solvereigenslepc.cpp by 
```c++
    vector_ptrtype solution, tmp;
    if ( this->mapRow().worldComm().globalSize()>1 )
    {
        solution = vector_ptrtype( new VectorPetscMPI<value_type>( this->mapRowPtr() ) );
        tmp = vector_ptrtype( new VectorPetscMPI<value_type>( M_mode,this->mapRowPtr() ) );
    }
    else
    {
        solution = vector_ptrtype( new VectorPetsc<value_type>( M_mode,this->mapRowPtr() ) );
        tmp = vector_ptrtype( new VectorPetsc<value_type>( M_mode,this->mapRowPtr() ) );
    }
    solution->add(1, tmp);
```
it solves the issue.
