### ISSUE TITLE
How to build a pdf for the doc of feelpp?

### ISSUE THREAD

**Issue by grabbitnu** [feelpp/feelpp#540]
I can't find any option in the make file, plz help. Thanks.

**Comment by prudhomm** [comment]
@grabbitnu regarding feelpp/feelpp#540 we provide only an html version of the documentation. I guess we could generate a pdf using doxygen but I am not unsure it will look good.
is there a problem with the html version of the documentation?

**Comment by grabbitnu** [comment]
By default the building of manual is disabled in CMakeLists.txt. The option FEELPP_ENABLE_MANUAL does not work yet, even it is swtiched on. I have to change CMakeLists.txt manually. 
Then the making of html lack imgXX.png and so on. So it cannot be built whether from .tar.gz or from git branch .

**Comment by vhuber** [comment]
@grabbitnu I guess you are aware the documentation is available online ? http://www.feelpp.org/docs/develop/index.html

I'm afraid the variable you highlight is deprectaded. to generate the html doc locally :
```
cmake -DFEELPP_ENABLE_DOXYGEN=ON feelpp
make doxygen
```
You have to open `doc/api/html/index.html` with a browser.

**Comment by vhuber** [comment]
@grabbitnu Can we close that issue ?
