### ISSUE TITLE
Providing options to Petsc.

### ISSUE THREAD

**Issue by vhuber** [feelpp/feelpp#550]
For a test (see #533) we need to pass options directly to Petsc.

- That can be down via the command line but it needs to add a "COMMAND_LINE" variable to the `feelpp_add_test` macro in `cmake/modules/feelpp.macros.cmake`.
- That can also be done at the `PetscInitialize` call (I guess in `feelcore/environment.cpp` line 346) providing the third parameter as a Feel++ option set to an empty config file that the user could fill when needed.
- The user may also define the environmental variable PETSC_OPTIONS

I would prefer the first solution for the #533 issue, but the second one may be more general. The third one is not applicable in the testsuite environment  I guess.

**Comment by vhuber** [comment]
See [here](http://www.mcs.anl.gov/petsc/petsc-current/docs/manual.pdf), page 179 for details.

**Comment by romainhild** [comment]
No it doesn't work

**Comment by vhuber** [comment]
id est ? @romainhild

**Comment by romainhild** [comment]
Ok, in fact it works in the test suite.
Thanks.

**Comment by vhuber** [comment]
@prudhomm I have added the `CLI` entry to the `feelpp_add_test` macro to handle specific variable sent by the command line.
