### ISSUE TITLE
markerToDof using face marker

### ISSUE THREAD

**Issue by gdolle** [feelpp/feelpp#553]
In 3D, markerToDof() doesn't find any Dof when the marker is an internal 2D face.

**Comment by prudhomm** [comment]
could you explain what you want to do exactely ?

**Comment by gdolle** [comment]
I try to set a Dirac on an face that is include in a 3D shape. This face is
geometrically defined  though GMSH then include explicitly in the volume
and marked (dim d-1, and part of the mesh).

When I use markerToDof("2dinternalface") to retrieve DOFs for the surface
nodes, no DOFs are found.

NB: When I mark several GMSH Point rather than one GMSH Surface, it works.

#554 is also related to this test



2015-03-20 16:10 GMT+01:00 prudhomm <notifications@github.com>:

**Comment by romainhild** [comment]
You need to load your mesh like this to use the markers : 
```c++
loadMesh( _mesh=new mesh_type,
          _update=MESH_CHECK|MESH_UPDATE_FACES|MESH_UPDATE_EDGES|MESH_PROPAGATE_MARKERS
```

**Comment by gdolle** [comment]
Thx Romain, it works and close #553 and close #554.

2015-03-20 16:46 GMT+01:00 Romain Hild <notifications@github.com>:
