### ISSUE TITLE
Wrong exact integration value from testsuite

### ISSUE THREAD

**Issue by LANTZT** [feelpp/feelpp#559]
I'm currently trying to write a new quadrature formula for Holo3 project about Image Correlation ( See #545 ). In order to test it, I use test_im.cpp from testsuite/feelpoly as example.
However, it appears some problems occur with tests, where we are in the Hypercube 2D case.

In fact, all "odd" tests ( with N as odd number ) didn't return an acceptable result, like below :
![capture d ecran 2015-04-02 a 15 59 34](https://cloud.githubusercontent.com/assets/7694838/6966382/ee92b01a-d958-11e4-9ff6-a190f6e05e0e.png)

At the contrary, tests with N, an even number, work well 
![capture d ecran 2015-04-02 a 16 56 13](https://cloud.githubusercontent.com/assets/7694838/6966422/33007cfa-d959-11e4-9416-2a14830b8560.png)

After some research and with the help of @vhuber, we finally discover that might not be my quadrature formula that is wrong but the exact solution we have to obtain. It estimates by the method integrate() from the P2N class define in the testsuite file. Furthermore, Gauss quadrature method has the same problem.
![capture d ecran 2015-04-02 a 16 18 36](https://cloud.githubusercontent.com/assets/7694838/6966472/9e06015a-d959-11e4-95f0-1dfe1b0aec77.png)

So I have a few questions : 
Where this formula comes from ? 
Can it be possible there are some mistake in it ?  ( Like not adapt to Hypercube ....) 

Thanks in advance for your help

**Comment by prudhomm** [comment]
could be a mistake, I wrote that a very long time ago and don't remember the details. I will have a look

**Comment by prudhomm** [comment]
I took a look at the code, why do you use `P2N`?  it is for simplices, it provides the interface to test the integral of `x^\alpha y^\beta` on a simplex.
the `integral()` function provides the exact formula.
What I do in `test_im` with P2N is then to loop over `\alpha` and `\beta = N-\alpha` to check polynomials of degree less than N. It is normal that it is not good.
I suggest that you check your formula only against `Qk` checks or write your own check using a known function and associated exact integral on quadrangles
