### ISSUE TITLE
Support HDF5 format 

### ISSUE THREAD

**Issue by prudhomm** [feelpp/feelpp#560]
Currently the restart strategy in timestepping does not scale, we should support HDF5 format and use 
`feel/feelcore/hdf5.hpp`
also we need to support simply hdf5 in order to, for example, use these hdf5 files say in matlab/octave to couple with other models.
the mesh data structure would need to be saved in hdf5 too in ordre to do the coupling.

 - [x] BDF
 - [x] Newmark
 - [x] Mesh

the support for
 -  ReducedBasis database for finite element solutions /cc @cdaversin @jbwahl @aancel 
has been moved to a separate issue

**Comment by prudhomm** [comment]
see @vincentchabannes commits
 - 11da96b56d2308d4290195d025bad3ad7f52e94d
 - cd341d4dea44f419ab90313fc355e62159992335
 - 5320cb3fdd2edf290224fdbe7d3ea3f935a3ef17

**Comment by prudhomm** [comment]
@vincentchabannes  @cdaversin @jbwahl @aancel I have updated the issue description and added mesh + reduced basis database. there are probably other place where the hdf5 format will be useful

**Comment by prudhomm** [comment]
@aancel @vincentchabannes  I am almost done with the read/write in HDF5 format for the mesh. We need that asap.
I have added locally the ghost tables(neighboring partitions of entities and ids in other partitions, @vincentchabannes do we need something else?). I will commit this evening once it is tested.  I am on the road today.
I also realised that a lot of the code can be made generic and we can reduce tremendously the amount of code.

**Comment by vincentchabannes** [comment]
I think that is enough!
Normally, build a parallel mesh require to have all ghosts elements which touch the partition with a point,edge,face and their id in real partition. After updateForUse() must do the work.

**Comment by prudhomm** [comment]
I am on it and almost done with it

**Comment by prudhomm** [comment]
it remains here to add the support to reduced basis.
I move the issue to v101

**Comment by prudhomm** [comment]
move hdf5 support for reduced basis to a separate issue
