### ISSUE TITLE
Support postprocessing in json files

### ISSUE THREAD

**Issue by prudhomm** [feelpp/feelpp#561]
Json files now describe 
- material
- parameter
- boundary conditions

we should start supporting description of post processing such as : 
- fields : which fields to visualize 
- forces: on which boundaries should we compute stresses (eg force)
- points: evaluation of fields at points. List of points can be given either in 
  - json 
  - a filename.  the filename will be useful if there are many points
  - a marked entity in the mesh

``` json
 "Fields":["pressure", "velocity","vorticity"],
 "Forces": ["cylinder"],
 "Points":[ "pressure": [ [0.1,0.2], [0.15,0.2], .. ], }
  // or 
"Points":[ "pressure": { "filename": "pressure_at_points.dat"}
  // or 
"Points":[ "pressure": { "region": "cylinder"}
```

**Comment by vhuber** [comment]
About materials:
- the present framework provides constant parameter, I would really enjoy to pass expression for them: the dynamic viscosity car be a function of a porous density.
- For the magnetostatic problems, we have to implement constitutives laws and tests various ones. It would be fantastic to use ginacExVf to define theses laws.

**Comment by prudhomm** [comment]
I know.

**Comment by vhuber** [comment]
I have added to the modelparameters class the ability to retrieve a node as a string in the tree.
That is a temporary workaround that allow to pass theses laws in the json file.

**Comment by vhuber** [comment]
@vincentchabannes @prudhomm Is there at this point a way to pass a list of points (in a file) to evaluate ?
The current grammar will be a way too expensive when we have more than a very little set of points.

**Comment by prudhomm** [comment]
this can easily be implemented and provided in the example of this issue

**Comment by vhuber** [comment]
Ok, I'm working on it.

**Comment by prudhomm** [comment]
I want a branch and a pull request, no direct commit please

**Comment by vincentchabannes** [comment]
and please, check also that break nothing in feelmodels (see for example feelpp/applications/models/fluid/TurekHron/cfd3.json )

**Comment by vhuber** [comment]
@vincentchabannes I mimic the framework you've implemented, but associating a field to a point sounds strange to me. what do you think of :
```javascript
        "Measures":
        {
            "firstSet":
            {
                "fields":["pressure","velocity"],
                "pointA":
                {
                    "coord":"{0.6,0.2,0}",
                },
                "pointB":
                {
                    "coord":"{0.15,0.2,0}",
                }
            }
            "secondSet":
            {
                "fields":["pressure"],
                "pointA":
                {
                    "coord":"{0.5,0.1,0}",
                },
                "pointB":
                {
                    "coord":"{0.15,0.2,0}",
                }
            }
        }
```
instead of
```javascript
        "Measures":
        {
            "Points":
            {
                "pointA":
                {
                    "coord":"{0.6,0.2,0}",
                    "fields":"pressure"
                },
                "pointB":
                {
                    "coord":"{0.15,0.2,0}",
                    "fields":"pressure"
                }
            }
        }
```
(the two configuration are not equivalent in that example, off course)

**Comment by vincentchabannes** [comment]
not agree.
What means firstSet, secondSet? this tag correspond to the type of measure (it can be Points or Forces or Extremum or. .. ). Also you can write actually : 
 ```
"Measures":
{
     "Points":
     {
           "pointA":
            {
                "coord":"{0.6,0.2,0}",
                "fields":"pressure"
             }
     }
}
 ```
or 
```
"Measures":
{
     "Points":
     {
           "pointA":
            {
                "coord":"{0.6,0.2,0}",
                "fields":["pressure","velocity"]
             }
     }
}
 ```
both are admissibles. and after the model store pointA_pressure and pointA_velocity.
Please try to do changes without break others codes. For example instead of Points tag, use PointSet and do whatever you want.

**Comment by vhuber** [comment]
I'm annoyed with the association "one point <-> many fields".
I would prefer "many fields <-> many points"

I know my proposition will breaks codes, that's why we discuss about it ;)

Would you prefer I implement a new type of measure, say `PointsList` or `PointsSet`, or fit exactly in the one you have developed ? I prefer using what you have written with the possibility to pass a list of coordinates instead just one.

**Comment by prudhomm** [comment]
done
