### ISSUE TITLE
EigenSolver : remove unconverged eigenfunctions

### ISSUE THREAD

**Issue by romainhild** [feelpp/feelpp#562]
Using `solvereigen.verbose` one can see that the relative error for some functions are greater than the tolerance : 
```
0-th mode error ||A x - lambda B x ||/||x|| = 0.00599313
1-th mode error ||A x - lambda B x ||/||x|| = 0.0305545
2-th mode error ||A x - lambda B x ||/||x|| = 6.61354
3-th mode error ||A x - lambda B x ||/||x|| = 39.5555
4-th mode error ||A x - lambda B x ||/||x|| = 0.0945696
5-th mode error ||A x - lambda B x ||/||x|| = 0.0542977
6-th mode error ||A x - lambda B x ||/||x|| = 1.64841e-13
7-th mode error ||A x - lambda B x ||/||x|| = 4.35037e-14
8-th mode error ||A x - lambda B x ||/||x|| = 5.12563e-14
9-th mode error ||A x - lambda B x ||/||x|| = 2.83137e-14
```
could we remove those functions from the returned map or at least add the error with it ?

**Comment by prudhomm** [comment]
normally it should be controlled by the number of converged eigenmodes ncv.
the number of eigenmodes requested is typically smaller than the number of converged eigenmodes.
do you use nev or ncv to print the table above ?

**Comment by romainhild** [comment]
No the table above is what is printed whit the option [solvereigen.verbose](https://github.com/feelpp/feelpp/blob/develop/feel/feelalg/solvereigen.hpp#L541-551).

**Comment by romainhild** [comment]
After a discussion with @prudhomm, I think the best solution is to use the eigenvalue to sort the modes.
I close the issue.
