### ISSUE TITLE
Vim - Modeline

### ISSUE THREAD

**Issue by vhuber** [feelpp/feelpp#565]
@prudhomm In every source file, we have the vim modeline indicating the file is tcl type.
Can I change that in every file ?

**Comment by gdolle** [comment]
I (strongly) agree.
I personnaly use this setting for now
```
vim: set syntax=cpp fenc=utf-8 et sw=4 ts=4 sts=4 :
```
But to respect feel++ coding style, I think we should add explicitly indent options (to discuss), for example
```
cin cino=N-s,c0,(0,W4
```
We should check first it respects all cases listed here
https://github.com/feelpp/feelpp/wiki/FeelppCodingStyles
in particular to avoid the ggvG= problem :).

**Comment by prudhomm** [comment]
Please do not mess with indentation and follow the coding style 
let me know the proper modeling and I will update the files
