### ISSUE TITLE
Support more features in the ginac parser

### ISSUE THREAD

**Issue by prudhomm** [feelpp/feelpp#568]
The Ginac parser support only but a few operations (`+-*/^`) as well as a few mathematical functions (`sin, cos, sqrt...`)and litterals (`Pi, E`). We need for example support for relational operations such as `<,>...`

**Comment by vhuber** [comment]
Is it possible to add `<=` and ` >=` please ?

**Comment by prudhomm** [comment]
with floats you don't really need that 
 `x>=value` -> `x > value-1e-14` 
also this may require more work than expected in ginac parser because the operators are coded as single  character. I suggest you do the above

**Comment by vhuber** [comment]
Yup, you're right.

I do not know how difficult it would be to let the user write directly the code than is written in the Ginac source file: is that possible ?

something like
```c++
auto expr = expr(soption("functions.f"),noparse);
```
that only apply right text substitution to take parameters into account.
