### ISSUE TITLE
interprocessvertices

### ISSUE THREAD

**Issue by prj-** [feelpp/feelpp#574]
It seems that it is possible to build submeshes with `interprocessfaces`, `interprocessedges`, but there is no `interprocessvertices`. How can I build a 0d mesh made of points, for example when two domains are connected only by vertices ?
(@vincentchabannes this might be one of the reason why `feelpp_doc_geneo` is not converging from time to time)

**Comment by prudhomm** [comment]
0d meshes are doable. I need to check if we have a test for that but I remember that 0D should work up to a certain point. I will check that
