### ISSUE TITLE
Ginac expression in myexpression.cpp

### ISSUE THREAD

**Issue by romainhild** [feelpp/feelpp#584]
Here is the output of `feelpp_tut*myexpression` in doc/manul/tutorial/ : 

```
g=x*(a-x)+b^(-1)*a*y^3
f={1,1}
i=-(aVal-x)*y
grad(g)=[[a-2*x,3*b^(-1)*a*y^2,b^(-1)*y^3+x,-b^(-2)*a*y^3]]
grad(f)=[[0,0],[0,0]]
laplacian(g)=[[-2+2*b^(-3)*a*y^3+6*b^(-1)*a*y]]
laplacian(f)=[[0],[0]]
div(f)=[[0]]
curl(f)=[[0]]
Evaluation  at  (0,0):
           g(x,y)=0
           f(x,y)=1
1
           i(x,y)=-0
Gradient:
     grad(g)(x,y)=12 -0
     grad(f)(x,y)=0 0
0 0
Divergence:
      div(f)(x,y)=0
Curl:
     curl(f)(x,y)=0
Laplacian:
laplacian(g)(x,y)=-2
laplacian(f)(x,y)=0
0
```

In `g`, shouldn't a and b be replaced by their value, 12 and -1 ?
Which would give different results for the laplacian for example (-2-72*y).

Also, if I try to replace `f` by `{a,1}:x:y:a` I have a segmentation fault at the line `auto grad_f=grad(f);`

**Comment by prudhomm** [comment]
> In g, shouldn't a and b be replaced by their value, 12 and -1 ?
> Which would give different results for the laplacian for example (-2-72*y).

if that's their values, it should

> Also, if I try to replace f by {a,1}:x:y:a I have a segmentation fault at the line auto grad_f=grad(f);

also a problem indeed

**Comment by prudhomm** [comment]
@romainhild could you provide a test in the testsuite for that please ?
thx in advance

**Comment by prudhomm** [comment]
@romainhild ?

**Comment by romainhild** [comment]
This code does not exist anymore.
