### ISSUE TITLE
Timers table for Feel++

### ISSUE THREAD

**Issue by prudhomm** [feelpp/feelpp#591]
`tic()` and `toc(msg)` provides a simple interface to timing. To follow this idea it would be nice to gather this information in a timer table and be able to dump it in a terminal or in a file to analyse the performances.
Information such as number of calls (to timers), total time, min, max, mean and stddev would be nice.
see also #576

**Comment by romainhild** [comment]
Is it also possible to log the time in LOG(INFO) when `display` is true ?
Also, what does `saveTimers` do when `save` is false ?

**Comment by prudhomm** [comment]
if false then it is not displayed.
I still need to improve this framework to also allow writing to disk the data, currently it is not the case
on your side, just instrument the code with `tic(), toc("msg")`. that part won't change
