### ISSUE TITLE
Extract block diagonal matrix

### ISSUE THREAD

**Issue by prudhomm** [feelpp/feelpp#593]
@vincentchabannes I think we really need to be able to extract the block diagonal part of a matrix in order to precondition say the velocity block of NS. This should reduce tremendously the cost of building the preconditioner (LU or MG type).  For NS, the main features are in the diagonal blocks, the extra diagonal blocks contain only the coupling between the velocity derivatives from the diffusion term.
Currently the preconditioner for velocity block takes the most amount of time and by a large factor.
Note also for @mszopos @ranine @jbwahl.

**Comment by prudhomm** [comment]
@vincentchabannes what do you think about that ?
we discussed that when you were in Strasbourg and you agreed that it was feasible
the idea would be to have something like
```cpp
auto Fu = createBlockDiagonalMatrix( A, Xh_indices, Xh_indices, d  ); 
// d number of components or perhaps some other info ?
```
now the question is : does that help performance-wise to have 2 ou 3 matrices corresponding to the components or have one big blog diagonal matrix. The latter would be better to avoid changing too much the current codes.

**Comment by vincentchabannes** [comment]
It's easier to build each submatrix by component and do the sum after( all can be done by petsc normally I think) .
The second method doesn't allow to use the submatrix method in Petsc and also we need to build the matrix subgraph. Thus more work.
I think, we need to implements both versions for compare performance.

**Comment by prudhomm** [comment]
we could use fieldsplit coupled with jacobi to do that. However we need to be able to tell fieldsplit about the components indices @vincentchabannes

**Comment by prudhomm** [comment]
also see if reuse-prec tells the multigrid solver to reuse the multigrid construction to speed-up the reconstruction of preconditioners

**Comment by vincentchabannes** [comment]
An example for use a preconditioner block jaboci with Fu in PCD : 


    
    [Fu]
    pc-type=fieldsplit
    fieldsplit-use-components=1
    fieldsplit-type=additive
    [Fu.fieldsplit-0]
    pc-type=gamg#lu
    ksp-type=preonly
    [Fu.fieldsplit-1]
    pc-type=gamg#lu
    ksp-type=preonly
    [Fu.fieldsplit-2]
    pc-type=gamg#lu
    ksp-type=preonly

**Comment by prudhomm** [comment]
@vincentchabannes excellent ! have you tried ? anything interesting ?

**Comment by vincentchabannes** [comment]
I don't have look the timers.
I have just checked that we have a correct convergence of PCD in a small 2d case

**Comment by prudhomm** [comment]
cool, lets see how it goes

**Comment by jbwahl** [comment]
very cool, i test this on my simulation asap

**Comment by prudhomm** [comment]
this is done and operational
