### ISSUE TITLE
Method `transpose()` in matrixsparse.hpp

### ISSUE THREAD

**Issue by jbwahl** [feelpp/feelpp#595]
My programme crash when using this function on a shared_ptr on sparse matrix A : 

```
At = A->transpose();
```

when i look the code of this method : 

```
boost::shared_ptr<MatrixSparse<T> > Mt;
transpose( *Mt, options );
```

i guess the crash comes because the shared_ptr Mt is not initialized, right ? 

However this method is often use in Feel (at least in feelcrb) and it seems to work.
Did i miss something ?

**Comment by romainhild** [comment]
I think that in the method, it calls the method `transpose` of the MatrixPetsc class, or another subclass of MatrixSparse.
Maybe it is link to the type of your matrix, or the way you initialized it.

**Comment by vhuber** [comment]
It seems that Mt is uninitialized.

**Comment by jbwahl** [comment]
i call the method `transpose()` which is not virtual in matrixsparse class. 
Then this method call the virtual one. But the program crashes when it call `operator*` on `Mt`
