### ISSUE TITLE
Support higher order meshes for levelset

### ISSUE THREAD

**Issue by prudhomm** [feelpp/feelpp#596]
@Doyeux @gdolle it seems to me that we could support higher order meshes with the levelset function.
As soon as the levelset stays P_1 and we have access to the vertices of the simplices and the hypercubes, I don't see (yet?) why it wouldn't work.

**Comment by Doyeux** [comment]
Yes, it should give a result at least.

In Feel++, only the boundary elements are curved, and the interior elements are P1 right?

We should be careful to initialize correctly the boundary elements. I don't know if h() is still a good approximation of the distance between the closest boundary and the first nodes for highly curved meshes.

**Comment by prudhomm** [comment]
@Doyeux thanks for the comment. We have indeed a procedure to straighten the mesh in the interior however this usually imposes a mesh that is also fine enough on the boundary and `h()` will probably be a good approximation in that case. @gdolle will test that actually rather quickly, let see how it goes.

Please have a look at the code and the nice look `using`  keyword for aliases ;)

**Comment by Doyeux** [comment]
Indeed it's much readable like this!

Yes, if the mesh is not too anisotropic and not thin enough, h() should be an accurate approximation whatever the geo order is.
Looking forward to see if it works on a mesh of geo order 2.

However, if needed, it could be really easy at least in P1 to add the keyword suggested in #468. But this can wait until it becomes really needed I guess...

**Comment by prudhomm** [comment]
a little screenshot @gdolle 😃?

**Comment by gdolle** [comment]
Yes, it seems ok for the 2D case with the two wall2dist methods.
Note that we have to use gmsh for visualizing high order mesh (see #602).

@aancel It seems there's a bug with the gmsh exporter in parallel,
the first test works fine, but the second one gives always 0 despite it
works fine with ensightgold.

3d is coming soon.


2015-06-12 17:57 GMT+02:00 prudhomm <notifications@github.com>:

**Comment by gdolle** [comment]
And here's some tests using again mesh of order 2 but in 3D with the two
methods.


​

2015-06-13 1:25 GMT+02:00 Guillaume DOLLÉ <dolle.guillaume@gmail.com>:

**Comment by prudhomm** [comment]
Can it be closed ?

**Comment by gdolle** [comment]
Yes it seems ok for me.
