### ISSUE TITLE
Exporters: behavior differences between add( ... ) function of exporter and add( ... ) function of a time step

### ISSUE THREAD

**Issue by aancel** [feelpp/feelpp#604]
@gdolle noticed that there were problems with the exporter when using:
```
auto exp = exporter(_mesh=M_mesh, _name="testsuite_levelset_distw1");
exp->step(0)->add("phi1", phi);
...
```
(This is an extract of testsuite/feelpde/test_levelset.cpp)

When adding data with the `add` function of a timestep (like above), the prefix passed to the exporter is not used as the file is written with the EnSight Gold exporter (at least).
Whereas when using the add function of the exporter (`exp->add( ... )`), the prefix is prepended and the file has the correct name.

The current solution works when we have only one exporter. But when we have 2 exporters with different prefixes and that add data directly to a time step like `exp->step(0)->add("phi1", phi);`, the prefix won't be applied and the second exporter will overwrite the data written by the first one.

**Comment by prudhomm** [comment]
@gdolle as a work around to differentiate between exporters use the `_path` option
