### ISSUE TITLE
Reporting framework

### ISSUE THREAD

**Issue by vhuber** [feelpp/feelpp#607]
It would be convenient to generate a logfile that store informations about :
- spaces
- mesh
- solvers
- timers
- bdf
- ...

A `saveMD(std::ostream &os)` should be a good solution.
I have tried it in MarkDown in a personal code (not finished yet), it produce something like that:

![image](https://cloud.githubusercontent.com/assets/2920150/8374015/15a4bb9a-1bf2-11e5-9769-f9a68666f582.png)

**Comment by vhuber** [comment]
What is saved for a model and timers (example)

## Model 
 - Name **precAFP2D**
 - shortName **precAFP2D**
 - description ****
 - model **linear**

### Parameters
|Name|Value|Min|Max|
|---|---|---|---|
|**mu_0**|1|1|1|

### Materials
|Material Physical Region Name|Rho|mu|Cp|Cv|k11|k12|k13|k22|k23|k33|Tref|beta|C|YoungModulus|nu|Sigma|
|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|

### Boundary Conditions
|Name|Type|Expressions|
|---|---|---|
|**phi**|Dirichlet|<ul><li>**Border**</li><li>0</li><li>0</li><li></li></ul>|
|**u**|Dirichlet|<ul><li>**Border**</li><li>{0,0}:x:y</li><li>{0,0}:x:y</li><li></li></ul>|

### PostProcess
|Kind | data |
|---|---|
|Fields|<ul><li>diffused</li><li>k11</li><li>k33</li></ul>|

## Timers

|Timer                                                |Count   |Total(s)     |Max(s)     |Min(s)    |Mean(s) |StdDev(s)|
|---|---|---|---|---|---|---|
|                                                   Backend::newMatrix:: build stencil |       5 |    2.04e-02 |    1.32e-02 |    1.91e-06 |    4.08e-03 |    4.77e-03|
|                                                   Backend::newMatrix:: initialize matrix |       5 |    1.40e-02 |    1.34e-02 |    9.49e-05 |    2.80e-03 |    5.28e-03|
|                                                   Backend::newMatrix:: zero out matrix + set split |       5 |    1.60e-03 |    1.56e-03 |    7.87e-06 |    3.19e-04 |    6.20e-04|
|                                                   Inverse |       1 |    1.38e-01 |    1.38e-01 |    1.38e-01 |    1.38e-01 |    0.00e+00|
|                                                   OperatorMatrix::applyInverse blockms.11 |       7 |    9.39e-02 |    3.92e-02 |    7.95e-03 |    1.34e-02 |    1.06e-02|
|                                                   OperatorMatrix::applyInverse blockms.22 |       7 |    3.30e-02 |    7.17e-03 |    3.75e-03 |    4.71e-03 |    1.13e-03|
|                                                   [PreconditionerAS] setup done  |       1 |    1.38e-05 |    1.38e-05 |    1.38e-05 |    1.38e-05 |    0.00e+00|
|                                                   [PreconditionerBlockMS] applyInverse update solution |       7 |    1.29e-01 |    4.68e-02 |    1.22e-02 |    1.85e-02 |    1.16e-02|
|                                                   [PreconditionerBlockMS] setup done  |       1 |    9.26e-02 |    9.26e-02 |    9.26e-02 |    9.26e-02 |    0.00e+00|
|                                                   [PreconditionerBlockMS] update |       1 |    3.46e-03 |    3.46e-03 |    3.46e-03 |    3.46e-03 |    0.00e+00|
|                                                   read msh from file |       1 |    1.99e-02 |    1.99e-02 |    1.99e-02 |    1.99e-02 |    0.00e+00|
|                                                   register elements associated to marked points |       1 |    3.60e-05 |    3.60e-05 |    3.60e-05 |    3.60e-05 |    0.00e+00|
|                                                   writing elements |       1 |    3.85e-04 |    3.85e-04 |    3.85e-04 |    3.85e-04 |    0.00e+00|
|                                                   writing faces |       1 |    4.21e-04 |    4.21e-04 |    4.21e-04 |    4.21e-04 |    0.00e+00|
|                                                   writing hdf5 file |       1 |    5.82e-02 |    5.82e-02 |    5.82e-02 |    5.82e-02 |    0.00e+00|
|                                                   writing points |       1 |    4.14e-04 |    4.14e-04 |    4.14e-04 |    4.14e-04 |    0.00e+00|

|Timer                                                |Count   |Total(s)     |Max(s)     |Min(s)    |Mean(s) |StdDev(s)|
|---|---|---|---|---|---|---|
|                                                   Inverse |       1 |    1.38e-01 |    1.38e-01 |    1.38e-01 |    1.38e-01 |    0.00e+00|
|                                                   [PreconditionerBlockMS] applyInverse update solution |       7 |    1.29e-01 |    4.68e-02 |    1.22e-02 |    1.85e-02 |    1.16e-02|
|                                                   OperatorMatrix::applyInverse blockms.11 |       7 |    9.39e-02 |    3.92e-02 |    7.95e-03 |    1.34e-02 |    1.06e-02|
|                                                   [PreconditionerBlockMS] setup done  |       1 |    9.26e-02 |    9.26e-02 |    9.26e-02 |    9.26e-02 |    0.00e+00|
|                                                   writing hdf5 file |       1 |    5.82e-02 |    5.82e-02 |    5.82e-02 |    5.82e-02 |    0.00e+00|
|                                                   OperatorMatrix::applyInverse blockms.22 |       7 |    3.30e-02 |    7.17e-03 |    3.75e-03 |    4.71e-03 |    1.13e-03|
|                                                   Backend::newMatrix:: build stencil |       5 |    2.04e-02 |    1.32e-02 |    1.91e-06 |    4.08e-03 |    4.77e-03|
|                                                   read msh from file |       1 |    1.99e-02 |    1.99e-02 |    1.99e-02 |    1.99e-02 |    0.00e+00|
|                                                   Backend::newMatrix:: initialize matrix |       5 |    1.40e-02 |    1.34e-02 |    9.49e-05 |    2.80e-03 |    5.28e-03|
|                                                   [PreconditionerBlockMS] update |       1 |    3.46e-03 |    3.46e-03 |    3.46e-03 |    3.46e-03 |    0.00e+00|
|                                                   Backend::newMatrix:: zero out matrix + set split |       5 |    1.60e-03 |    1.56e-03 |    7.87e-06 |    3.19e-04 |    6.20e-04|
|                                                   writing faces |       1 |    4.21e-04 |    4.21e-04 |    4.21e-04 |    4.21e-04 |    0.00e+00|
|                                                   writing points |       1 |    4.14e-04 |    4.14e-04 |    4.14e-04 |    4.14e-04 |    0.00e+00|
|                                                   writing elements |       1 |    3.85e-04 |    3.85e-04 |    3.85e-04 |    3.85e-04 |    0.00e+00|
|                                                   register elements associated to marked points |       1 |    3.60e-05 |    3.60e-05 |    3.60e-05 |    3.60e-05 |    0.00e+00|
|                                                   [PreconditionerAS] setup done  |       1 |    1.38e-05 |    1.38e-05 |    1.38e-05 |    1.38e-05 |    0.00e+00|

**Comment by prudhomm** [comment]
nice work. However as I said on thursday I would have preferred that we discuss the design before heading straight to implementation.
if we want another format (say asciidoc, latex...) we have to duplicate a lot of code. It does not scale with formats. Only the class that handles saving exporting to a certain format should actually know about the format.

**Comment by vhuber** [comment]
I can cancel theses commits and prepare a new implementation that mimic the exporter implementation. What do you think about it ?

**Comment by prudhomm** [comment]
@vhuber We first need to discuss what would be a good design that can scale with the number of classes and possibly support a few formats. Then we discuss how to implement that. Do not propagate more the changes you made to other classes. We don't have to remove your commits, we will just do a refactoring. thanks in advance

**Comment by vhuber** [comment]
idea: build a jekyll based website to store results of simulations.

**Comment by gdolle** [comment]
To complete the previous comment, 
idea:
- generate a unique id per simulation
- generate an xml/json/... output to add the possibility to collect a posteriori environment information into a database (and use a website similar to cdash to compare every simulations)

**Comment by vincentchabannes** [comment]
add possibility to activate/deactivate the storage of statistic data in Environment.
Can be usefull in the case where we have a lot of mesh,space,solve(),ho gmcinverse,...

Also, I would prefer to have by default 
--prefix.display-stats=0
 when prefix is not empty, what do you think?

**Comment by prudhomm** [comment]
@gdolle the collecting of simulation result will probably be done using mydas by Kitware which we already put in place for vivabrain. 

@vincentchabannes how about a global option `--report.enable=1 | 0` ?
then it means that no report collection will be done at all (not just timers)

**Comment by gdolle** [comment]
@cprudhomme I didn't now Midas, it looks interesting.
I agree with @vincentchabannes to add the possibility to disable some
observers or all observers.

how about a global option --report.enable=1 | 0 ?
>
ok for me.


2015-07-09 17:35 GMT+02:00 prudhomm <notifications@github.com>:

**Comment by vhuber** [comment]
https://github.com/vhuber/present_simu

**Comment by prudhomm** [comment]
we now have the simulation journal

**Comment by prudhomm** [comment]
see #1222
