### ISSUE TITLE
Feel++ Travis Deployment 

### ISSUE THREAD

**Issue by prudhomm** [feelpp/feelpp#624]
- [x] deployment of feel++ tarball after successful builds to **S3**
- [x] encrypt user/password `travis encrpyt PASS=7h3Pa55!` works well
- [ ] webhooks to notify sub-projects to rebuild (parameters: frequency, ...)
- [ ] update some sub-projects (move to container based)

/cc @vhuber  @solael

**Comment by vhuber** [comment]
### Connection
To deploy the generated archive, we need to achieve authentification based on a password as long as key is not possible (or I missed something).

It seems we **need** [`sshpass`](http://stackoverflow.com/a/5386587) as long as [expect](http://stackoverflow.com/questions/5386482/how-to-run-the-sftp-command-with-a-password-from-bash-script/15682600#15682600) print the [password](https://travis-ci.org/feelpp/feelpp/builds/72974554), what is not acceptable.
But Travis does not (yet) allow that package to be installed.
I have asked to add it to the [whitelist](https://github.com/travis-ci/apt-package-whitelist/issues/515).
I'm afraid we are in a dead-end as long as `sshpass` is not available.

### Archive integrity
To improve the archive integrity, we can crypt it using openssl.
```sh
openssl enc -aes-256-cbc -in archive.tar.bz2 -out archive.tar.bz2.ssl -pass pass:$PASS
openssl enc -aes-256-cbc -d -in archive.tar.bz2.ssl -pass pass:$PASS -out archive.tar.bz2
```

### Major concern
We can crypt the pass with
```
travis encrypt SOMEVAR=secretvalue
```
and use `$SOMEVAR` in our `.travis.yml`.

**The one that can modify `.travis.yml` on the repo (but not on a fork) is able to decrypt the password.**

**Comment by prudhomm** [comment]
We have now access to S3. The archive will be stored here
   https://feelpp.s3.eu-central-1.amazonaws.com/travis-builds/

**Comment by prudhomm** [comment]
unfortunately llvm.org is down currently and it breaks the travis build at the very beginning when we add the clang packages.
Once it is back we should have the tarball uploaded

**Comment by vhuber** [comment]
@prudhomm The last archive we have is on atlas, on the /tmp directory.

**Comment by vhuber** [comment]
@prudhomm take care in subprojets to untar the archive in `/home/travis/software/install` as long as `petsc/conf/rules` use absolute path to run scripts. (see line 974 for example).

**Comment by vhuber** [comment]
@prudhomm I guess from now it should be convenient to provide a kind of default `.travis.yml` to add in projects, isn't it ?

**Comment by prudhomm** [comment]
Now we used Buildkite for Feel++ deployement via docker !
