### ISSUE TITLE
Support HDF5 in reduced basis databases

### ISSUE THREAD

**Issue by prudhomm** [feelpp/feelpp#630]
ReducedBasis database for finite element solutions 

/cc @cdaversin @jbwahl @aancel

**Comment by prudhomm** [comment]
link to #560

**Comment by aancel** [comment]
@prudhomm We discussed with @jbwahl this morning. I'll put up a new branch for this feature and use the save/loadHDF5 function from feel/feelalg/vectorublas.cpp. I'll have to rework the code on this side, as there are some issues with const-ness (cc @vincentchabannes). I'll transform the saveHDF5 to const safe, and will let the loadHDF5 as non const.

**Comment by prudhomm** [comment]
@vincentchabannes shouldn't this issue be closed ?
