### ISSUE TITLE
nonlinear pow function works only with integer

### ISSUE THREAD

**Issue by romainhild** [feelpp/feelpp#636]
The function `pow` used for example [here](https://github.com/feelpp/feelpp/blob/develop/doc/manual/nonlinear/nonlinearpow.cpp#L91) has a bug when used with a double.
For example, I have the following results with 3/2 : 
![capture d ecran 2015-08-10 a 15 39 01](https://cloud.githubusercontent.com/assets/5481448/9194548/529e3122-401c-11e5-8ff2-a3ea1c6b34de.png)

**Comment by aancel** [comment]
@romainhild I guess you meant you a non-integer ? (Confusion between title and description)

**Comment by romainhild** [comment]
@aancel I have edited the description. Thanks

**Comment by prudhomm** [comment]
@romainhild could you add a test in `testsuite/feelvf/test_pow.cpp` to reproduce this please ?

**Comment by romainhild** [comment]
I tried to make a test, but computing the L2 norm gives me a NaN. Do I commit as it is ?

**Comment by prudhomm** [comment]
yes

**Comment by vhuber** [comment]
@romainhild Any update ?

**Comment by romainhild** [comment]
in 9a891a9, the test fails because the L2 norm is NaN.

**Comment by vhuber** [comment]
Actually, the problem on 9a891a9 is about the expression definition.
UnitSphere() is between `-1` and `1` and you are asking for `sqrt(x)`, thus the `nan` is on `v` (and after that on the L2 norm).
