### ISSUE TITLE
Support spatial convolution 

### ISSUE THREAD

**Issue by prudhomm** [feelpp/feelpp#643]
We can support convolution using the keyword `convolve` which would support an interface similar to `integrate` and return an element of a nodal function space. This should work in parallel.
The fact that it should work in parallel is problematic since all degrees of freedom coordinates must be known to all processors, this will induce a lot of communication initially. This will be impractical for very large meshes and millions of degrees of freedom.

``` cpp
auto space=Pch<1>(mesh);
auto v = convolve( _space=space, _expr=<convolution integrand expression> );
```

`v` is an element of space.

/cc @feelpp/sivibirpp

**Comment by prudhomm** [comment]
needs now to work in parallel

**Comment by vhuber** [comment]
[CDash](http://my.cdash.org/testDetails.php?test=22531310&build=927826) reports bugs for that test.

**Comment by prudhomm** [comment]
yes that's a known behavior until it is fixed. no problem with that.
