### ISSUE TITLE
Port Feel++ on Windows

### ISSUE THREAD

**Issue by prudhomm** [feelpp/feelpp#65]
Windows 10 has WSL and support ubuntu 18.04. it should  be very easy to port Feel++ on Windows

**Comment by vhuber** [comment]
http://www.clubic.com/linux-os/actualite-801304-bash-windows.html : we should have a look !

**Comment by aancel** [comment]
:+1:
But we will apparently have to wait until summer for the anniversary update:
http://arstechnica.com/information-technology/2016/03/windows-10-270-million-users-binbash-supporting-anniversary-update-coming-summer/

**Comment by prudhomm** [comment]
@Trophime @vincentchabannes here is the result of the laplacian in 3D on 4 cores in windows 10 pro WSL ubuntu 18.04
![Annotation 2019-08-19 150452](https://user-images.githubusercontent.com/151693/63267845-349a0180-c293-11e9-847f-fad30ae619e2.png)

**Comment by prudhomm** [comment]
> as far as what I've understood we have two options:
1) to have feelpp package for ubuntu/debian (to install apt ...)
2) to distribute a ubuntu/debian version with only feelpp and its requirement. Then you have to go throught a kind of review process from MicroSoft to get it on the store

I'll try to send you the few pointer I have on that
<sub>[View in Slack](https://feelpp.slack.com/archives/C6A375EMS/p1566221802002100)</sub>

**Comment by prudhomm** [comment]
> <https://docs.microsoft.com/en-us/windows/wsl/build-custom-distro>
<sub>[View in Slack](https://feelpp.slack.com/archives/C6A375EMS/p1566221842002300)</sub>

**Comment by prudhomm** [comment]
the quickstart testsuite runs 100%

<img width="1066" alt="Screenshot 2019-08-19 21 49 37" src="https://user-images.githubusercontent.com/151693/63294756-675fec00-c2cb-11e9-9ed7-408e5126d45d.png">
