### ISSUE TITLE
Json parser does not support comments in boost 1.59.0

### ISSUE THREAD

**Issue by vincentchabannes** [feelpp/feelpp#659]
this version of boost break all codes which use comments in json file.
all comments must be remove.
see http://www.boost.org/users/history/version_1_59_0.html  or http://lists.boost.org/Archives/boost/2015/09/225238.php

**Comment by vhuber** [comment]
Thank you for noticing it !

**Comment by prudhomm** [comment]
It is not a really big deal. There are a couple of solutions:
 - remove them
 - insert them as data that won't be parsed
```json
  // my bc 
```
becomes
```
"comments":"my bc"
```
perhaps `comments` here is poorly chosen, we can think about this
 - have an extra layer in feel++ that parse first the json file, strip all comments and pass that to the json_parse

the last idea seems the right way to do it.

**Comment by prudhomm** [comment]
Ok thanks to boost, we have spirit and in spirit there is Qi and with Qi can easily strip comments ;)
actually there is already a code for that ;)

**Comment by vincentchabannes** [comment]
@prudhomm it works perfectly, thank a lot!
