### ISSUE TITLE
Exporter ensightgold with option ensightgold.save-face

### ISSUE THREAD

**Issue by vincentchabannes** [feelpp/feelpp#665]
There is a segfault when I try to use exporter.ensightgold.save-face=1.

**Comment by aancel** [comment]
Do you have a sample app to reproduce this issue ? 
If I remember well, I didn't encountered this issue with quickstart apps.

**Comment by vincentchabannes** [comment]
Just try with a marked mesh.
I have noticed that if on your geo file, you use Physical Line(32) =..., (with a integer instead of string) the option save-face do nothing. I think it s another bug. ( this is the case in QuickStart). But generally we use Physical Line("toto") =...  And with this, there is the segfault.  Can you confirm?

**Comment by prudhomm** [comment]
`save-face=1` can be a nice feature, the price is saving extra data. 
you can then visualize data on the markedfaces (eg inlet, outlet...)
it is not heavily tested though

**Comment by vincentchabannes** [comment]
In fact, I want to use this for compute the streamlines from inlets/outlets with EnSight (it's really easier compare to paraview). I use this method in my phd defense in the video of the cerebrovenous network with particles moving on streamlines

**Comment by prudhomm** [comment]
indeed you can pass the inlet to the particle trace tool or any surface
