### ISSUE TITLE
Support MPI synchronization in Vector

### ISSUE THREAD

**Issue by vincentchabannes** [feelpp/feelpp#671]
keyword sync(...) allow to apply a synchronization of value of a vector.
Several kind of synchronization can be define in order to assign the dofs values shared by several proc : 
- operator = : value equal to one of them (generally the active process )
- operator + : value equal by summing all values for each proc which share the dof 
- operator min/max : value equal to the min/max value for each proc which share the dof

```
auto v = Vh->element();
// do some operations on v
sync( v, "=" );
sync( v, "+" );
sync( v, "min" );
sync( v, "max" );
```

If the vector v is modified only locally (e.g on a marker), the values synchronized
can be wrong value by deleting last insertion. For fix this, we can give
a list of dof index which are used to generate the new values of dof shared.

```
v.on(_range=markedfaces(mesh,"toto"),_expr=cst(3.1415));
std::set<size_type> dofUsed;
// fill dofUsed
sync(v,"=",dofUsed ); // also available for all operator
```

**Comment by vincentchabannes** [comment]
it fix also the P1 visu of a P0d field in // (activated with --exporter.element-spaces "P0-P1" )

**Comment by prudhomm** [comment]
:+1:

**Comment by prudhomm** [comment]
It should now be closed no?

**Comment by prudhomm** [comment]
Should it be closed @vincentchabannes? Or are there missing bits still?
