### ISSUE TITLE
Exporter prefix

### ISSUE THREAD

**Issue by aancel** [feelpp/feelpp#672]
Following the test written by @gdolle ([testsuite/feelts/test_bdf3.cpp](https://github.com/feelpp/feelpp/blob/develop/testsuite/feelts/test_bdf3.cpp)), we noticed some issues regarding the prefix used by the exporter:
An example would be (from @gdolle's code):
```
# First create an exporter with the test_bdf prefix
# This will create the initial timeset with the corresponding prefix
auto e = exporter( _mesh=mesh, _name="test_bdf" );
...
# Further calls to setPrefix won't modify the prefix of the timeset 
# after this initial call, because the setPrefix function does not update 
# the prefix of the latest timeset.
e->setPrefix( prefix )
```

Actually and currently, this is working with the Ensight Gold exporter because I made modifications to actually use the prefix set to the exporter and not the name of the timeset, but I think it would be a better idea to totally switch to using the name of the timeset. 

The function `setPrefix( name )` currently only store the value for the prefix. Wouldn't it be a better idea to directly set the value of the most recent timeset rather than storing the prefix ? Maybe we can also add a new `setPrefix( ts_id, name )` that would allow to modify the prefix for other timesets (in case we would be using several of them)

**Comment by prudhomm** [comment]
I would have to have a closer look. I wrote that a long time ago. I need to refresh my memories.

**Comment by aancel** [comment]
I can take care of this and the associated modifications in the exporters, if you validate the change. I think it would make the code of the exporters cleaner.

**Comment by prudhomm** [comment]
sure, do that in a branch + PR

**Comment by prudhomm** [comment]
@aancel Please discuss here or the branch/PR the changes before hand rather than after.
