### ISSUE TITLE
cmake broken for quickstart

### ISSUE THREAD

**Issue by prudhomm** [feelpp/feelpp#686]
Cmake process is broken in quickstart. It seems from [travis](https://travis-ci.org/feelpp/quickstart/jobs/101011931) that FEELPP_DIR is not taken properly into account to set the include directory of the Feel++ installation. 
probably a bug in the cmake feel++ setup 
@aancel could you fix that please ?

**Comment by aancel** [comment]
@prudhomm Indeed I saw this. I seem to have forgot to take into account the case where Feel++ could be installed with tarballs, and thus not in the directory it was initially installed.

**Comment by prudhomm** [comment]
yup

**Comment by prudhomm** [comment]
could be also install via homebrew or the debian package system.

**Comment by aancel** [comment]
I don't think that installing Feel++ via homebrew or packaging systems would cause issues, as standard path will be used for both building and installation. The problems would appear when using different paths from the one used in the build step.

**Comment by aancel** [comment]
@prudhomm The build is fixed on travis. There just seem to be a memory issue with clang 3.5.
I'll close the issue.
