### ISSUE TITLE
Support test(expr) function 

### ISSUE THREAD

**Issue by prudhomm** [feelpp/feelpp#690]
Support test(expr) function to retrieve the test function of an expression if it exists

``` c++
auto e = trans(N())*id(v);
auto t = test(e); // returns id(v);
```

it produces an error to use this function on an expression which does not hold a test function

**Comment by vhuber** [comment]
@prudhomm How does it work with the following expression ?
```c++
auto an_expr = id(v)*gradt(psi) + idt(u)*grad(psi);
auto t = test(an_expr);
M_form2 = vf::integrate(_range=elements(mesh),_expr=an_expr);
```

**Comment by prudhomm** [comment]
that won't work yet. in that case we would retrieve a mpl vector of the two types of test functions
