### ISSUE TITLE
Exporter Ensight: variable names with space characters

### ISSUE THREAD

**Issue by gdolle** [feelpp/feelpp#692]
Paraview can't open exported files for variable elements if they are saved using a name containing spaces
 e.g
```cpp
auto e = exporter(...)
e->add( "my element", my_element );

// generate files that looks like "bioreactor.my element.scl.0001"  gives paraview error while loading.
```
We should check string to either remove spaces (`myelement`) or replace space by underscores (`my_element`).

**Comment by aancel** [comment]
Indeed, spaces are not checked in those names.

Notes for solving the issue:
To solve this issue, I guess the best way is to directly modify the `add*` functions in `feeldisc/timeset.hpp`, and not only modifying the ensight gold exporter (This would take care of the same potential issue in other exporters). 
To do so, we can use:
```
#include <algorithm>
...
std::replace(s.begin(), s.end(), " ", "_");
...
```

**Comment by aancel** [comment]
Plus, we should also modify all the functions accessing to the fields by their name, like `nodalScalar`, `nodalVector`, ...

**Comment by prudhomm** [comment]
or we can say the spaces and special characters like `;.,` are just not allowed like in the ensight format

**Comment by vhuber** [comment]
@prudhomm You mean: the user should not use them or the user can not use them ?

**Comment by prudhomm** [comment]
not allowed means not authorized and if he/she does do that then it is his/her own peril.

**Comment by prudhomm** [comment]
a new `sanitize` function will be called to make sure that no special characters are in the string
branch and PR commit soon
