### ISSUE TITLE
Support reading Acusim Raw Mesh formats

### ISSUE THREAD

**Issue by prudhomm** [feelpp/feelpp#706]
```
arm file is an xml file describing the files
*.crd : node coordinate file     node_ID | X | Y | Z  
*.cnn : fluid element file   elt_ID | node1 | node2 | node3 | node4  (e.g. for tetra)
*.ebc:  surface elt file     elt_cnn_belong |elt_ID |  node1 | node2 | node3 (e.g. for tria)
```

/cc @feelpp/po

**Comment by prudhomm** [comment]
I now close this issue
@vincentchabannes we can re-open if needed

**Comment by romainhild** [comment]
I have a segfault when loading a `arm` mesh.
```
[loadMesh] Loading mesh in format arm(acusolve)h5: "/home/u2/hild/feelpp/research/po/mesh/diffuseur/diffuseur.1.arm"
. loading AcusimRawMesh, coordinates /home/u2/hild/feelpp/research/po/mesh/diffuseur/diffuseur.crd
  .. element_set fluid - /home/u2/hild/feelpp/research/po/mesh/diffuseur/diffuseur.fluid.tet4.cnn (four_node_tet)
[1]    59491 segmentation fault (core dumped)  ./feelpp_testARM --gmsh.filename
```
The mesh is the one sent by PO last friday.

I have just launch an application with `auto mesh = loadMesh( Mesh<Simplex<3> >);` with  `gmsh.filename` set to the `.arm` file in the same directory as the `.crd`, `.cnn` and `.ebc`.

**Comment by romainhild** [comment]
Actually, it seems it comes from [this line](https://github.com/feelpp/feelpp/blob/develop/feel/feelfilters/importeracusimrawmesh.hpp#L153)

**Comment by vincentchabannes** [comment]
@romainhild 
my test case was : 
 ```
  <element_set 
		name      ='fluid_soufflerie tet4' 
		group     ='fluid_soufflerie tet4' 
		file      ='cacd_afc_120M.fluid_soufflerie_0_tet4.tet4.cnn' 
		topology  ='four_node_tet'/>
  <surface_set 
		name      ='fluid_soufflerie tet4 inflow_fente_INF_continu tria3' 
		parent    ='fluid_soufflerie tet4' 
		group     ='fluid_soufflerie tet4 inflow_fente_INF_continu tria3' 
		file      ='cacd_afc_120M.fluid_soufflerie_0_tet4.tet4.fluid_soufflerie_0_tet4_0_inflow_fente_INF_continu_0_tria3.tri3.ebc' 
		topology  ='three_node_triangle'/>
 ```
in this case,  the name of surface is the third character string. But I don't know why there is  ```fluid_soufflerie tet4```   before

**Comment by romainhild** [comment]
@vincentchabannes In my case, I have 
```
  <element_set
        name      ='fluid'
        group     ='fluid'
        file      ='diffuseur.fluid.tet4.cnn'
        topology  ='four_node_tet'/>
  <surface_set
        name      ='inflow'
        parent    ='fluid'
        group     ='inflow'
        file      ='diffuseur.fluid.tet4.inflow.tri3.ebc'
        topology  ='three_node_triangle'/>
```

**Comment by romainhild** [comment]
If we don't know to what `name` corresponds, maybe we should use it as is, just by replacing the white spaces by underscores. What do you think ?

**Comment by vincentchabannes** [comment]
we need to look the doc of this format. I think tet4 or tria3 are necessary else we don't know which kind of element must be use (it seems that the filename contains also tet4 or tria3). For the name,  maybe we can just take the last one and different of tet4,tria3,... it works in both cases.

**Comment by romainhild** [comment]
The kind of element is determined by the topology attribute, no ?
It is weird that the format is not at all the same between our two sample.

**Comment by prudhomm** [comment]
@romainhild you are right, it seems that the tet4 is misleading in the filename and we should use the topology entry for the proper element type.

**Comment by romainhild** [comment]
@vincentchabannes I have another mesh from PO that looks like this:
```
 <element_set
  name      ='fluid tet4'
  group     ='fluid'
  file      ='MESH.DIR/diffuseur.fluid.tet4.cnn'/>
 <surface_set
  name      ='wall tria3 fluid tet4'
  parent    ='fluid tet4'
  group     ='wall'
  file      ='MESH.DIR/diffuseur.wall.tria3.fluid.tet4.ebc'/>
```
In this case, the name is the first part of the `name` attribute. And the last one and different from tet4, tria3 is always `fluid`.

An option could be to remove tet4, tria3, and the parent from the name, if found in it.
What do you think ?

**Comment by vincentchabannes** [comment]
@romainhild it's good for me to remove the parent name and tria3, tet4. The syntax seems to be name= (name1,entity1),..., (nameN,entityN) or name=name
