### ISSUE TITLE
Support for io streams in parallel

### ISSUE THREAD

**Issue by prudhomm** [feelpp/feelpp#715]
To avoid endless `if ( Environment::isMasterRank() )` we should support c++ iostreams in parallel and in particular outputting on master rank process of a `WorldComm`

We should define `cout`, `cerr`, `clog` by default and they should output the streams only if  `Environment::isMasterRank()` is true.
here is how it would work
```c++
Environment env(...);

cout << "Hello world from " << Environment::rank() << std::endl;
```

Another application is to output to files from master rank
```c++
MasterStream out(std::ofstream);
out.open("data.txt");
out << "some data ...";
out.close();
```
/cc @feelpp/feelpp

**Comment by vhuber** [comment]
@prudhomm @aancel 
From scratch :
```sh
cmake ~/feelpp -DFEELPP_ENABLE_RESEARCH=false -DCMAKE_BUILD_TYPE=debug -DCMAKE_C_COMPILER=`which clang-3.7` -DCMAKE_CXX_COMPILER=`which clang++-3.7` -DCMAKE_CXX_FLAGS="-pipe"
```
followed by
```sh
make feelpp_test_feelio
```
No problem.

**Here the problem**
If I add 
```c++
#include <feel/feel.hpp>
```
In the test, I have as error (identitcally for cout) :
```sh
/home/u2/huber/feelpp/testsuite/feelcore/test_feelio.cpp:67:5: error: reference to 'cerr' is ambiguous
    cerr << "cerr:: Hello World from process " << Environment::rank() << std::endl;
    ^
/data/software/install/VTK/5.10.1/gcc-4.9.0/openmpi-1.10/include/vtk-5.10/vtkIOStream.h:46:12: note: candidate found by name lookup is 'cerr'
using std::cerr;
```

**Comment by prudhomm** [comment]
either
`using Feel::cerr` 
or 
`Feel::cerr`
