### ISSUE TITLE
bdf - default behavior

### ISSUE THREAD

**Issue by vhuber** [feelpp/feelpp#726]
I ran an application with a bdf.
I had to stop it.
I would like to restart it.
I cannot: the default file format is not hdf5 but binary and the name of the created file does not embed the proc rank.

I guess we should change the bdf default behavior to:
- default file format: hdf5 if cmake detect it
- default naming convention : set the rank proc in file name if the file format is binary. That should not depends on the user.

@vincentchabannes Is there any reason to prevent modifications like that ?

/cc @prudhomm @jbwahl

**Comment by ranine** [comment]
I agree with Vincent, if we miss adding the option bdf.file-format=hdf5 and/or bdf.rank-proc-in-files-name=1, the restart becomes painful
