### ISSUE TITLE
Issue bluiding fluid exemple

### ISSUE THREAD

**Issue by cpivot** [feelpp/feelpp#728]
Hi, 
Here an issu when i try to build the fluid exemple, i'm on the develop branch of feelpp
```
In file included from /usr/local/include/feel/feelmodels/modelcore/modelalgebraic.hpp:33:0,
                 from /usr/local/include/feel/feelmodels/modelcore/modelnumerical.hpp:33,
                 from /usr/local/include/feel/feelmodels/fluid/fluidmecbase.hpp:44,
                 from /usr/local/include/feel/feelmodels/fluid/fluidmechanics.hpp:34,
                 from /home/cpivot01/feelpp-develop/feelpp/fluid/fluid/main_fm.cpp:3:
/usr/local/include/feel/feelmodels/modelcore/modelbase.hpp:38:65: fatal error: feel/feelmodels/modelcore/feelmodelscoreconstconfig.h: Aucun fichier ou dossier de ce type
 #include <feel/feelmodels/modelcore/feelmodelscoreconstconfig.h>

```
It seems that the file feel/feelmodels/modelcore/feelmodelscoreconstconfig.h il missing
Bye

**Comment by vhuber** [comment]
@cpivot 
We have to fix that installation process, you are right.

As a quickfix, you can (pick only one option)
- copy `$BUILDDIR/feel/feelmodels/modelcore/feelmodelscoreconstconfig.h` to `/usr/local/include/feel/feelmodels/modelcore/`
- do not install Feel++ as a system library, add your project in the `$SRCDIR/feelpp/research` directory, and compile your project in `$BUILDDIR/research/yourProject` (that needs to activate the option `-DFEELPP_ENABLE_RESEARCH_YOURPROJECTNAME=true` variable at cmake process)
- wait for us to fix that.

(I'll recommend the second option to properly fix it quickly)

/cc @vincentchabannes

**Comment by aancel** [comment]
I will solve this issue. 
@cpivot Which command do you use to do the installation ? `make install` ?

**Comment by cpivot** [comment]
Hi, 
I used in a first time `make install-feelpp-lib`, but i couldn't locate the missing file. I tried to use `make install` now i can locate the `feelmodelscoreconstconfig.h` in my bluid directory. 
How can I saiy to feelpp o consider my build directory?
Bye

**Comment by vhuber** [comment]
@cpivot I guess you have taken the `CMakeLists.txt` from [here](http://book.feelpp.org/content/GettingStarted/using.html#_step_1_configure_your_project_with_feel)
If so, you have to correctly set the environment variable `$FEELPP_DIR` with
```sh
export FEELPP_DIR=/where/is/my/lib
```
such that `$FEELPP_DIR/share/feel/cmake/modules/` exists.

**Comment by cpivot** [comment]
@vhuber Ok I did èxport FEELPP_DIR=my_build_directory` but it still not working. 
Then I did `locate feelmodelscoreconstconfig.h` to see where is this file. But when I go to this directory I have `feelmodelscoreconstconfig.h.in`with this extra extension.

**Comment by aancel** [comment]
@cpivot If you want access to this file, you cannot use target `make install-feelpp-lib` as, if I remember well, this target does not install model libraries. Use `make install`
Commit 22873c1a335d63d01caeb6b607c6a3759ddccfe5 should fix your issue with the missing file. Pay attention, I renamed the file with .hpp at the end instead of .h (for consistency).
Please close the issue, if it is working for you.

**Comment by cpivot** [comment]
I compiled feelpp "all in one" and it's ok now :) 
Thank's
