### ISSUE TITLE
Interpolate a dataset

### ISSUE THREAD

**Issue by vhuber** [feelpp/feelpp#733]
Given a dataset (x_i, y_i) we should provide the construction of the GiNaC expression that interpolate the dataset.
- [x] p1
- [x] Spline
- [x] Akima

Moreover, we have to provide the derivative of the interpolation 

Given the following dataset
```sh
T K
t1 k1
t2 k2
t3 k3
```
I would like to write
```c++
auto interpolate_kappa = interpolate(soption("kappa_dataset"),ioption("interpolate_method"));
/*
* interpolate_kappa.interpolate = "(T>t1)*(T<t2)*(a1*T + b1) + (T>t2)*(T<t3)*(a2*T + b2):T"
* interpolate_kappa.diff = "(T>t1)*(T<t2)*(a1) + (T>t2)*(T<t3)*(a2):T"
*/
auto expr_interpolate_kappa = expr(interpolate_kappa.interpolate);
```

The first solution is to use GSL, but that will add another dependence.
The second solution is to build the interpolation method.

**Comment by prudhomm** [comment]
why should it be a ginac expression ?

**Comment by vhuber** [comment]
The process to build an expression from a string is complete.
Actually, you're right, that is not mandatory, I though it will be easier.

**Comment by prudhomm** [comment]
if you have already $$(x_i,y_i)$$ available applying interpolation methods is not that complicated in C++ and it would be more efficient

**Comment by vhuber** [comment]
I would like to solve d_t T - k(T) div(T) = f.
I have the dataset (T - k(T)).
It will be easier to manipulate ginac expressions, or I miss something.

**Comment by prudhomm** [comment]
why would it be easier ?
```c++
Interpolator I( T, k );
double theT=...;
std::cout << "I(" << theT << ") = " << I( theT ) << std::endl;
```
it could even be enhanced to support fields:
```c++
auto Th = Pch<1>(mesh);
auto T = Th->element();
auto Ph = Pdh<0>(mesh);
auto K = Ph->element();
K.on(_range=elements(mesh), _expr=I(T) );
```

**Comment by vhuber** [comment]
To match my needs, it has to be enhanced to support fields.
I guess I have to write a class in the feelvf directory that presents the correct interface for the `Expr<>` class, isn't it ?

**Comment by vhuber** [comment]
@prudhomm How can I add the enhancement to support fields ?

**Comment by prudhomm** [comment]
sorry no time at the moment. will try after wednesday

**Comment by vhuber** [comment]
Ok, let me know. I have written the interpolation class, I'm waiting for instructions.

**Comment by prudhomm** [comment]
what does it look like ?

**Comment by vhuber** [comment]
[Here](http://pastebin.com/mbJtyiF4) the pastebin of the code. I do not want to push it as long as it is not a *Feel++* class.

**Comment by vhuber** [comment]
What do you think about it ?

**Comment by vhuber** [comment]
@prudhomm I do not understand why you write it:
```c++
auto Th = Pch<1>(mesh);
auto T = Th->element();
auto Ph = Pdh<0>(mesh);
auto K = Ph->element();
K.on(_range=elements(mesh), _expr=I(T) );
```
Why have you chosen `K` in `Pdh<0>` ?

**Comment by vhuber** [comment]
Here the chosen interface :
```c++
  auto M_ak = InterpolatorAkima(data);
  T.on(_range=elements(mesh), _expr=expr(soption("functions.f")));
  K.on(_range=elements(mesh), _expr=fit(idv(T),M_ak) );
  Kd.on(_range=elements(mesh), _expr=fitDiff(idv(T),M_ak) );
```

@prudhomm is the solution convenient enough to be merged ?
