### ISSUE TITLE
FindPETSc.cmake

### ISSUE THREAD

**Issue by vhuber** [feelpp/feelpp#734]
When running cmake with clang or gcc, petsc complains that various tests failed.
That comes from cmake tries to compile a little petsc code with the compiler that can not find `mpi.h`.

I have not find a way to pass theses tests with mpicc when one wants to use clang of gcc as a compiler.

Moreover, the code we want to compile generate an error at the execution that has to be fixed.

**Comment by vhuber** [comment]
@cdaversin what is the reason you've reverted https://github.com/feelpp/feelpp/commit/e3333f9c0b295f36dc5b83876b49da5723ce2c98 ?

**Comment by cdaversin** [comment]
@vhuber @aancel Unfortunately I don't remember which was the reason of this revert.
I don't remember the problem which was fixed doing this. You can re-apply the changes, and I will report eventual problems if needed.
