### ISSUE TITLE
support for med format for mesh

### ISSUE THREAD

**Issue by Trophime** [feelpp/feelpp#735]
Hi, 
i run into a problem with gmsh 2.11 and med 3.10.
Med is the format used by Salome to save mesh data.
The I usually use gmsh to the med file and save a .msh file which I can use in Feelpp

The trouble with med 3.1.0 is that the save .msh file no longer contains any element
which is really bad...

It will help if we could load directly med mesh file just like what was done for po.

**Comment by Trophime** [comment]
med 3.1.0 source tarball can be retreived from [latest Salome](http://www.salome-platform.org/downloads/current-version)

API is included in the source tarball.
see [MED Salome](http://www.salome-platform.org/user-section/about/med) to get a general picture of MED

**Comment by prudhomm** [comment]
and what is the format exactly ?
is there a one page/two pages document explaining the format ?

**Comment by gdolle** [comment]
Here's the API (however more than 2 pages):
http://docs.salome-platform.org/latest/gui/MED/MEDLoaderBasicAPIPage.html
(Note that MED is already a GMSH dependency)

**Comment by prudhomm** [comment]
this has been fixed with #824
