### ISSUE TITLE
Doxygen manual examples missing

### ISSUE THREAD

**Issue by gdolle** [feelpp/feelpp#738]
The documentation section for the manual examples seems missing in the API.
The *.doc files in "feelpp/doc/manual/" for most example are not displayed at http://doc.feelpp.org/
It seems there is a problem with doxygen configuration.

**Comment by vhuber** [comment]
doc.feelpp.org is intended for the library developers: the manual documentation has to be moved to the feelpp-book.

**Comment by prudhomm** [comment]
yes but @gdolle some documentation disappeared, namely the one from example files with doxygen in them.
we should recobver them or rewrite them

**Comment by gdolle** [comment]
As mentionned @prudhomm, there was an "example" section in doxygen that is not in the feelpp-book and was generated parsing code comments and reading specific *.doc files. For example I see there's still `doc/manual/heat/heatsink.doc`.

Currently there is no more documentation available for feel++ examples online (either in the API nor in the feelpp-book) and that is a serious problem.

If everyone agree to put these docs in the feel++ book, I'd be glad to rename the issue.
