### ISSUE TITLE
brew install duplicated source

### ISSUE THREAD

**Issue by mdelmans** [feelpp/feelpp#746]
When running
`brew install feel`

you get:

```
==> Installing feelpp from feelpp/science
Error: Formulae found in multiple taps: 
 * feelpp/science/gmsh
 * homebrew/science/gmsh
```

Pinning the tap doesn't help. The error propagates deeper into the dependencies. So if you fix formula to specifically use `feelpp/science/gmsh`, you get:

```
==> Installing feelpp from feelpp/science
Error: Formulae found in multiple taps: 
 * feelpp/science/opencascade
 * homebrew/science/opencascade
```

coming from `gmsh` formula

**Comment by prudhomm** [comment]
Hi

sorry for the late answer. you should not use feelpp/homebrew-science but directly homebrew/homebrew-science and then use
https://github.com/feelpp/homebrew-feelpp

here is the set of command lines
```
brew tap homebrew/homebrew-science
brew tap feelpp/homebrew-feelpp
brew install feelpp
```

**Comment by prudhomm** [comment]
let us know how it goes

**Comment by prudhomm** [comment]
@mdelmans is it working now for you ? I am closing the issue, feel free to re-open it
