### ISSUE TITLE
Support add scalar quantity in Exporter interface

### ISSUE THREAD

**Issue by prudhomm** [feelpp/feelpp#750]
Adding a scalar quantity (eg a constant or a constant over time) is supported in [ExporterEnsightGold](http://doc.feelpp.org/classFeel_1_1ExporterEnsightGold.html), we should add an interface in [Exporter](http://doc.feelpp.org/classFeel_1_1Exporter.html) that enables this when there is no time-stepping (it is already done in the time-stepping case)

```c++
auto e = exporter(_mesh=mesh); 
// a scalar field
e->add( "V", *pp );                                                                                                                                      
double myvalue=1.0;
e->add( "myValue", myvalue );                
e->save()
```
/cc @vhuber @MarieHouillon

**Comment by gdolle** [comment]
:+1:

**Comment by prudhomm** [comment]
@gdolle what was your problem with the exporter? Bug report already filled?

**Comment by vhuber** [comment]
I've rebuild from scratch Feel++, it goes well.

**Comment by prudhomm** [comment]
ok good. thx

**Comment by vhuber** [comment]
@prudhomm Actually, it depends on the compiler.
Clang 3.5 complains about the compilation :
```clang
/home/vhuber/feelpp/feel/feelfilters/exporter.hpp:409:34: note: candidate template ignored: disabled
      by 'enable_if' [with T = Feel::FunctionSpace<Feel::Mesh<Feel::Simplex<2, 1, 2>, double, 0>,
      Feel::bases<Feel::Lagrange<1, Scalar, Feel::Continuous, PointSetEquiSpaced, 0> >, double,
      Feel::Periodicity<Feel::NoPeriodicity>, Feel::mortars<Feel::NoMortar> >::Element<double,
      Feel::VectorUblas<double, ublas::vector<double> > >]
         typename std::enable_if<std::is_floating_point<T>::value>::type* = nullptr )
                                 ^
/home/vhuber/feelpp/feel/feelfilters/exporter.hpp:419:5: note: candidate template ignored:
      substitution failure [with F = Feel::FunctionSpace<Feel::Mesh<Feel::Simplex<2, 1, 2>, double,
      0>, Feel::bases<Feel::Lagrange<1, Scalar, Feel::Continuous, PointSetEquiSpaced, 0> >, double,
      Feel::Periodicity<Feel::NoPeriodicity>, Feel::mortars<Feel::NoMortar> >::Element<double,
      Feel::VectorUblas<double, ublas::vector<double> > >]: non-type template argument is not a
      constant expression
    add( std::string const& name, F const& u,
```

**Comment by prudhomm** [comment]
It is a bug in the compiler then
I think
The code is correct

**Comment by vhuber** [comment]
Do we remove Clang 3.5 from the list of the supported compiler ?

**Comment by prudhomm** [comment]
I don't know yet, may be we can find a workaround

**Comment by vhuber** [comment]
Btw, is there a possibility to export, for a given field, a string ? It could be convenient to let us write : 
```c++
e->step(current_time)->add("u",u,"comment");
```
to avoid very long variable name (In think about the exporter in CRB).

**Comment by aancel** [comment]
It would be possible to do so with the VTK exporter.
Fields are exported as vtkDataArrays and you can annotate those data arrays with information, like double or const char *.
An example is given here: http://www.paraview.org/Wiki/VTK/Examples/Cxx/PolyData/AttachAttributes

However, I don't know how those information would be accessed and displayed in ParaView. You might have to extract them yourself with a custom filter, if ParaView doesn't display them somewhere.

**Comment by aancel** [comment]
With Ensight Gold, you only seem to be able to bundle a description with the variable name in a single field (limited to 80 chars).
See http://www3.ensight.com/EnSight10_Docs/UserManual.pdf for more information.
