### ISSUE TITLE
Bug in path of ensightgold scalar quantity file

### ISSUE THREAD

**Issue by prudhomm** [feelpp/feelpp#751]
the file storing the scalar quantity in the ensight gold format is generated in the wrong directory, it is not in the same directory as the ensight other files

/cc @feelpp/feelpp @MarieHouillon

**Comment by vhuber** [comment]
@prudhomm 
CDash complains about the exporter, does this commit has something to do with that ?
For example : http://my.cdash.org/viewBuildError.php?buildid=948683

(considering the CDash latency, it is possible that problem is already fixed)

**Comment by prudhomm** [comment]
it is related to #750 and not #751.

**Comment by prudhomm** [comment]
and it is not even clear that it is a bug. I tested the testsuite without problem here
:point_up: [April 23, 2016 1:37 PM](https://gitter.im/feelpp/feelpp?at=571b5e7011d2855e3401277a)

**Comment by prudhomm** [comment]
let's wait and see the next cdash and eventually set a bug report on #750 if needed
