### ISSUE TITLE
Support concatenation of entity sets

### ISSUE THREAD

**Issue by prudhomm** [feelpp/feelpp#752]
In HDG we need to create the union of set of faces which may be of different location (internal faces and markedfaces say on boundary). 
this can be useful of course in other scenarii than HDG
```c++
auto set = concatenate(internalfaces(mesh),markedfaces(mesh,"top"), markedfaces(mesh, "R"));     
```
/cc @feelpp/hdg

**Comment by prudhomm** [comment]
then `set` can be used as the usual filters `integrate(_range=set, _expr=...)`

**Comment by vhuber** [comment]
@prudhomm I'm afraid there is a problem with `concatenate`, see `testsuite/feelmesh/test_concatenate`:
```sh
feelpp/testsuite/feelmesh/test_concatenate.cpp:52:23: error: use of undeclared identifier 'concatenate'
            auto e3 = concatenate( e1, e2 );
```

**Comment by vhuber** [comment]
@prudhomm Are you certain there is no duplicates between that issue and #455 ?
