### ISSUE TITLE
Support automatic code reformatting according to Feel++ coding rules

### ISSUE THREAD

**Issue by prudhomm** [feelpp/feelpp#763]

**Comment by vhuber** [comment]
For VIM, the plugin is [here](https://llvm.org/svn/llvm-project/cfe/trunk/tools/clang-format/clang-format.py)

**Comment by prudhomm** [comment]
what does it do ?

**Comment by vhuber** [comment]
<C-I> and the file is indented considering the `.clang-format` file.

**Comment by prudhomm** [comment]
ok nice. 
be careful because it seems that some (boost) macro may be messed up by clang-format.
so use with care
