### ISSUE TITLE
Segfault in parallel with addMatrix and block matrix

### ISSUE THREAD

**Issue by romainhild** [feelpp/feelpp#769]
When one adds an integral on internal faces on a matrix, trying to add this matrix to another results in a segfault.

**Comment by vhuber** [comment]
@romainhild Can you provide an example, or even better a test in the testsuite ?

**Comment by romainhild** [comment]
it is done: 37cde6e

**Comment by romainhild** [comment]
The problem comes from the fact that the graph changes when one integrates on internal faces. So the graphs differ from the two matrices.

A way to copy such a matrix, but this erase the content `A2`, could be:
``` c++
MatConvert(toPETSc(A)->mat(), MATSAME, MAT_INITIAL_MATRIX, &(toPETSc(A2)->mat()));
```

@prudhomm what should I do with this issue and the associated testcase ?

**Comment by prudhomm** [comment]
you should add the fix to test it with some checks

**Comment by romainhild** [comment]
but is this really a fix? I mean that it does not do exactly the same as `addMatrix`.
And shouldn't `addMatrix` be working in this case, or is this the expected behavior, and then no need for a fix ?
