### ISSUE TITLE
Computing element type at a point segfaults when a mesh partition is empty

### ISSUE THREAD

**Issue by Trophime** [feelpp/feelpp#775]
Hi, when trying to compute the value of an element type at a given point

```
auto Xh=Pchv<1>(mesh);
node_type pt(3);
auto  B = Xh->element();
auto val = B(pt);
```

I end up with a segfault when the mesh (actually a submesh) contains an empty partition.

**Comment by vhuber** [comment]
Can you provide a complete test on the testsuite for that please ?

**Comment by prudhomm** [comment]
@Trophime would you have a reproducer ?
