### ISSUE TITLE
move log files to result directory 

### ISSUE THREAD

**Issue by prudhomm** [feelpp/feelpp#787]
Currently log files are stored in scratch directory. 
It would be better to have everything in one place. 
Log files would in sub-directory  `logs` of  `fs::current_path()` where we store the results

**Comment by vincentchabannes** [comment]
For me it's better to have log files in scratch dir because a lot of files are generated when we launch a lot of applications, and now we need to erase these files in each applications directory. Also, in some of my applications, the current path can be not fixed and thus logfiles can be written everywhere.
Do you plan to define an option/env variables to keep the previous behavior?

**Comment by prudhomm** [comment]
I think the previous behavior is way too complicated. we have files in general in too many places.
the vast majority of users don't know where they are unfortunately. 
Moreover 
 - most users never erase the logfiles because they don't know where they are and/or they don't realize they take space. 
 - it requires extra steps on supercomputers for example to recover these files which are in a different directory.

the current path is not anywhere but the directory set initially:
 - if `nochdir=1`, then <current_dir>/logs
 - if  `nochdir=0` then `<directory | rootRepository><application_name>/<np_*>/logs`

regarding deleting logfiles, I propose to simply erase logfiles if they exist when a simulation is re-run.

now regarding your application what is the directory layout for your results  ?

**Comment by prudhomm** [comment]
the PR #788 allows to simplify (or to make it easier on users) some aspectsof the runtime environment
some advantages I see:
 - everything in one place, easier to find things
 - the logs correspond to the latest simulation
 - former logs are erased when a new simulation are done
 - link to #731 which displays some info about the app
 - #786 which colorises the output to localise more quickly some important text

**Comment by vhuber** [comment]
@prudhomm you've mentioned user does not erase logfiles and that can be problematic. Since the user does not know there is a logfile, we can make the log generation optional, isn't it ?

And to address the size of the logfile, can you have a look to #771 ?

**Comment by vincentchabannes** [comment]
For me, not write these files by default will be the best. And have this log files for each run is very useful (for debugging). As feel++ is a library, we need to keep in mind that feel can be integrate in others environments (or we can also write an other Feel::Environment constructor for these case). I think if we want a better understanding for users, we mustn't hide all of this in Environment, but user which read changeDirectory, changeLogDirectory(..) know where files are generated.  Imagine that petsc,gmsh,vtk do the same thing, it becomes hard to manage this. And all of my applications use feel as a library and feel is not necessary the master lib.  Examples :(1) with feelmodel applications, the export dir is computed at runtime and after the Environment constructor. (2) with paraview plugin, the current path must be the place where paraview has been run. (3) some constraints quite similar in angiotk.

**Comment by prudhomm** [comment]
I will probably use this
http://stackoverflow.com/questions/19291499/change-logging-directory-in-google-glog
to change the log directory correctly
