### ISSUE TITLE
Minimal version of Feel++

### ISSUE THREAD

**Issue by aancel** [feelpp/feelpp#790]
To help with building demonstrators for online reduced basis applications, we would like to keep the number of dependencies Feel++ uses as small as possible, notably to build small-sized docker images.
- Mandatory dependencies : boost, eigen
- Dependencies that can be disabled : petsc, slepc, gmsh, openmpi (to investigate)

**Comment by aancel** [comment]
@prudhomm Most of the dependencies can be disabled with associated options. By default, they keep the initial activation behavior they have right now.
Using the FEELPP_MINIMAL_BUILD option will disable most of the dependencies.

**Comment by prudhomm** [comment]
@aancel gmsh and paraview are in dockerfile.minimal. any reason for that ?
they should not be depends

**Comment by aancel** [comment]
@prudhomm Indeed Gmsh and ParaView are still in the minimal Dockerfile.
This image was tailored for the project @vincentchabannes is working on and those dependencies are needed to build everything.
If I exclude the ParaView plugin, both Gmsh (for loadmesh calls) and VTK (for ExporterVTK) are still needed.
@vincentchabannes @prudhomm Could we remove thoses dependencies and use ifdefs without impairing the proper functioning of the apps ?

**Comment by vincentchabannes** [comment]
For the paraview plugin, of course Paraview is necessary but not Gmsh, we will use hdf5 mesh format. Also for a simple crb online application (work in progress), only boost and Eigen are necessary (there is no mesh to load).  I think we need to have some kind of minimal docker images, depending on the context.

**Comment by aancel** [comment]
Ok for now, I'll leave those two dependencies, I'll remove them, once the work on the online app is finished. It will also allow to remove several apt-dependencies by the way !

**Comment by prudhomm** [comment]
@aancel @vincentchabannes there will indeed be 2 types of images.  Gmsh won't be in hem. Paraview in one of them

**Comment by aancel** [comment]
Regarding to this, I pushed a new idea in the base build image here: https://github.com/feelpp/docker/commit/c67a1873cc79dfb723211c282b5c797e5a40f6ad
I propose to use the ARG entry to allow disabling the build of a specific dependency. We can then use docker-compose to build several base images with different configurations without having to handle different Dockerfiles. If you have remarks regarding to this, please let me know.

**Comment by aancel** [comment]
There sem to be a bug with cmake_dependent_option used in this setup.
When the user attemps to override the option value. Cmake_dependent_option revert it to the value it is set for.
I'll switch to the following:
```
if(FEELPP_MINIMAL_BUILD)
option( ... ON)
else()
option( ... OFF)
endif()
```
to circumvent the issue

**Comment by prudhomm** [comment]
Ok

**Comment by prudhomm** [comment]
@aancel what are the news on that front ?

**Comment by aancel** [comment]
@prudhomm It seems to be working well for the feelpp library, according to travis (e.g. on the last build: https://travis-ci.org/feelpp/feelpp/jobs/153648150). Now that the previous issue is fixed we should have a normal behaviour and the ability to build this minimal version.
