### ISSUE TITLE
CRB - rhs and time

### ISSUE THREAD

**Issue by vhuber** [feelpp/feelpp#800]
The Rhs has the following form: `f(x; mu) g(t)`
To my best knowledge, the framework does not allow `g(t)` to be taken into account at this point.

The base class of crb models has to be extended to do this.

/cc @prudhomm @vincentchabannes

**Comment by vincentchabannes** [comment]
You can do that by implementing in your model    ```  betaq_type computeBetaQ( parameter_type const& mu ,  double time , bool only_terms_time_dependent=false )  ``` or ```computeBetaQm``` if you use eim.

**Comment by vhuber** [comment]
Thank you !

What about theses kind of Rhs: `(z-t)*f(x,y)` ?

**Comment by prudhomm** [comment]
@vhuber this is rather easy you have z*f(x,y) -t*f(x,y) which is exactly the form required !

**Comment by vhuber** [comment]
I've seen that (really), but I though the `M_betaAq` members apply on the whole system formed by the linear forms added via the `addRhs` function.
Apparently, the `computeBetaQ` function is to overwrite the mu-dependent ginac expression given by the addRhs function, isn't it ?

**Comment by prudhomm** [comment]
@vhuber your right hand side is a little weird. if you think in terms of units then you are subtracting terms that don't have the same units.

**Comment by vhuber** [comment]
@prudhomm my bad: it is not `x-t` but `x-v*t` with `v` the velocity.
I have assumed `v=1` for that issue.
