### ISSUE TITLE
CMake / CTest 

### ISSUE THREAD

**Issue by vhuber** [feelpp/feelpp#801]
In the macro `feelpp_add_application` we have the flag `APP_NO_TEST` to forbid ctest to generate a test.
In the doc (i.e.) directory, no `feelpp_add_application` are called with that flag

There is only the `testsuite` directory that contains code to be tested.

Why does the `feelpp_add_application` macro let ctest to generate test (`add_test` line 103 & 105) ?

I would like to remove the possibility to add tests with the `feelpp_add_application` macro.
That is to let CDash only report crash on the code we test with `feelpp_add_test`.

What do you think about it ?

/cc @prudhomm @vincentchabannes @aancel

**Comment by prudhomm** [comment]
This is in fact the expected behavior. some applications(not test) will be run through ctest .
