### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by BijanZarif** [feelpp/feelpp#816]
Dear Feel++ Developers,

I have intended to install the Feel++ based on the instruction of the web page "http://book.feelpp.org/content/GettingStarted/building.html". I successfully passed the configuration step without any error, but with lots of warnings. However, when I used the command "Make -j8", I faced an error which has been attached below. I would be so pleased if you could guide me how to solve this problem.

Kind Regards,
Bijan

[Error.txt](https://github.com/feelpp/feelpp/files/530554/Error.txt)

**Comment by prudhomm** [comment]
@BijanZarif The warnings are ok. it seems however that the problem comes from the installation of MPI on your machines
```
Linking CXX shared library libfeelpp_ginac.so
/usr/bin/ld: /usr/local/lib/libmpich.a(alloc_mem.o): relocation R_X86_64_32 against `MPIR_ThreadInfo' can not be used when making a shared object; recompile with -fPIC
/usr/local/lib/libmpich.a: error adding symbols: Bad value
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [contrib/ginac/ginac/libfeelpp_ginac.so.2.1.0] Error 1
make[1]: *** [contrib/ginac/ginac/CMakeFiles/feelpp_ginac.dir/all] Error 2
mak
```

what type system do you have ? could you install the shared libraries for mpich ?

**Comment by prudhomm** [comment]
@BijanZarif we have reworked a little bit the documentation. 
You could try also using [feel++ in docker ](https://book.feelpp.org/content/en/02-docker/)

**Comment by prudhomm** [comment]
By the way you should produce the type of system you use

**Comment by prudhomm** [comment]
We need more information. I close this issue for now
