### ISSUE TITLE
Support two element mesh in parallel (e.g 2 processors)

### ISSUE THREAD

**Issue by prudhomm** [feelpp/feelpp#822]
Currently the code is stuck (mpi lock probably) 
see `benchmark/hdg/hdg_laplacian`

**Comment by prudhomm** [comment]
@vincentchabannes I remember you telling me that this was fixed ( I am not sure though) and I cannot find the commit. any update on this ?

**Comment by prudhomm** [comment]
@vincentchabannes this is fixed now right ?

**Comment by vincentchabannes** [comment]
it was fixed with 56c9f801fd49587acd8e6cbe6c62f4b867d9dcf3.
