### ISSUE TITLE
Avoid code duplication of updateGhostCellInfoByUsingNonBlockingComm

### ISSUE THREAD

**Issue by prudhomm** [feelpp/feelpp#833]
@vincentchabannes @lantzt in feature/holo3 the function
    `MeshStructured::updateGhostCellInfoByUsingNonBlockingComm` was taken from
    importergmsh, is it still needed (I haven't checked the code)?
    if yes then we should merge the two versions fom meshstructured and
    importergmsh and avoir code duplication

**Comment by vincentchabannes** [comment]
@prudhomm If I remember, yes it's same code. And normally this function doesn't have dependency about importergmsh. So it could be merged.

But, the question is : is it really necessary for the structured mesh? this function give the element id of ghost cell in other partition which contains this element as active.

**Comment by prudhomm** [comment]
@LANTZT I haven't checked but is this function actually used now ?

**Comment by LANTZT** [comment]
@prudhomm Yes, it is. The function is present at the end of `MeshStructured` creation.

**Comment by prudhomm** [comment]
@LANTZT is it really needed ? see the comment by @vincentchabannes. You have this information thanks to the structure of the mesh no ?

**Comment by LANTZT** [comment]
@prudhomm I will try without it, and compare the results to the old ones

**Comment by prudhomm** [comment]
I set this issue to v0.104. We need to cleanup and review the code in `MeshStructured`
