### ISSUE TITLE
Port Feel++ on Finis Terrae @ CESGA

### ISSUE THREAD

**Issue by prudhomm** [feelpp/feelpp#852]
We need to have Feel++ running on Finis Terrae rapidly

 - [X] natively
 - [X] singularity

I would say that @gdolle is doing the job with @vincentchabannes @Trophime helping if necesary

documentation is here : http://book.feelpp.org/clusters/ft2/

**Comment by prudhomm** [comment]
@victorsndvg where do we stand on Feel++ at CESGA ? have you tried solving a large problem ?

**Comment by prudhomm** [comment]
@gdolle is preparing description of usage of Feel++ on supercomputer feelpp/book.feelpp.org#4
it would be nice to check the page. @gdolle where do we stand on this ?

**Comment by gdolle** [comment]
@prudhomm I'm almost finished. The current page details with compilation scripts. We'll have to update that part once modules are up to date of course.

**Comment by victorsndvg** [comment]
@prudhomm ,
@gdolle scripts works properly. Now I'm trying to do some tunning to PETSc, if possible, in order to get better performance. I don't tried to solve big problems yet.

**Comment by prudhomm** [comment]
@vincentchabannes is there some toolbox code that could be run to make relevant benchmarking in 3D at CESGA ? If I remember correctly you set set some tools to measure performance within the toolboxes . Could you write a few lines on this ? May be we could put that somewhere in a book ?

**Comment by victorsndvg** [comment]
Hi @all
I think Feel++ is successfully compiled/installed in FT2. :sweat_smile: 
I did minor modification in "cesga port". You can see this changes in #891

Let me know if all works properly and if it works I think you can close this issue.

**Comment by prudhomm** [comment]
@gdolle @trophime @romainhild @lsala you could test with your application when you have the time. @gdolle @victorsndvg is the book doc on ft2 up-to-date?

**Comment by victorsndvg** [comment]
Sorry @prudhomm , I'm a bit lost with the last question. Which book?

**Comment by prudhomm** [comment]
I mean here http://book.feelpp.org/clusters/ft2/

**Comment by victorsndvg** [comment]
@prudhomm ,

In a first sight seems that the existing content is correct. There is an issue adding a raw file from the repository:

> Unresolved directive in ft2.adoc - include::https://raw.githubusercontent.com/feelpp/feelpp/develop//ports/cesga/environment[]

Probably some info about executing the udocker container can be also added. Do you agree?

With the 2 "Work in progress" warnings, I suggest to remove remove both. About the compilation process, I think that a link to the scripts is enough info. In my opinion, to explain the compilation process could be a nightmare. 

On the other hand, I think that the info related with singularity is also enough. Are you thinking in other sections related with singularity?
