### ISSUE TITLE
Package Salome  with Feel++ Docker

### ISSUE THREAD

**Issue by prudhomm** [feelpp/feelpp#854]
We need to have an image of salome that we can use with Feel++.

**Comment by gdolle** [comment]
If the image is generated by your CI yes, otherwise use rather the "singularity_images/custom" directory of the collection.

**Comment by prudhomm** [comment]
@Trophime what is the status of the docker salome package?
should we try to have salome with feelpp ?

/cc @romainhild

**Comment by prudhomm** [comment]
it seems that we had an issue about this :)

I will try reproduce the issuein docker

**Comment by romainhild** [comment]
This is done now.
