### ISSUE TITLE
CMake process fails from scratch at GINAC step 

### ISSUE THREAD

**Issue by metivett** [feelpp/feelpp#860]
Instruction `list(REMOVE_DUPLICATES _ginac_rpath)` in [contrib/ginac/CMakeLists.txt](https://github.com/feelpp/feelpp/blob/develop/contrib/ginac/CMakeLists.txt#L132)  fails since `_ginac_rpath` is unset (see d7a4c44ebff1ffc8b87803b3e529008d391184b3 which commented out  this [line](https://github.com/feelpp/feelpp/blob/develop/contrib/ginac/CMakeLists.txt#L105)).

/cc @prudhomm

**Comment by prudhomm** [comment]
can you show an error message ?
that's weird that nobody else got this problem. We recompile Feel++ from scratch every time there is a new commit. what is the platform you work on ? 
currently I cannot reproduce this without more information

**Comment by metivett** [comment]
The error appears in the configuration step. It reads 
`[...]`
`-- found CLN [/usr/local/include/cln/version.h], version 1.3.4`
`CMake Error at contrib/ginac/CMakeLists.txt:132 (list):
  list sub-command REMOVE_DUPLICATES requires list to be present.`
`-- Found FLEX: /usr/bin/flex (found version "2.5.35")`
`[...]`
This is on osx, and it only shows up when I try to build in a new (empty) directory. If I uncomment the  aforementioned line (`set(_ginac_rpath_reloc "$ORIGIN/../lib")`), it configures fine.
In case this may be related to the cmake version, mine is 3.7.1.

**Comment by prudhomm** [comment]
Ok let me try on osx then

**Comment by Trophime** [comment]
I ran into a similar problem. Just make sure the list in not empty before applying REMOVE_DUPLICATES... in contrib/ginac/CMakeLists.txt
