### ISSUE TITLE
Serialization of Feel::Vector

### ISSUE THREAD

**Issue by romainhild** [feelpp/feelpp#861]
The serialization of Vector, VectorPetsc and VectorPetscMPI.

**Comment by romainhild** [comment]
After b580d58, the serialization of the vectors should work in sequential but not in parallel.
@jbwahl

**Comment by romainhild** [comment]
@prudhomm @jbwahl It now works in parallel for the vectors.

In `vector.hpp` I could not put the serialization into the class, like in `vectorpetsc.hpp`. I do not understand why for the moment. So I put it outside it, it works.

I also needed to add `BOOST_CLASS_EXPORT_GUID` for the derived classes `VectorPetsc<double>` and `VectorPetscMPI<double>`. But if one wants to use it with another template, he should add it.

**Comment by jbwahl** [comment]
@romainhild great ! Thx ! I will do the job for matrix next week.
