### ISSUE TITLE
Support smart storage/replay of offline eim/deim data

### ISSUE THREAD

**Issue by prudhomm** [feelpp/feelpp#866]
@jbwahl @romainhild @cdaversin I have been thinking about a discussion with @jbwahl regarding storing matrices in DEIM. The issue is about having to rebuild the entire offline EIM data. storing matrices or vectors would help and avoid having to replay the entire algorithm.
However storing matrices is impractical(due to size), moreover in the case of vector and matrices we are dependent also on the partitioning.

There would be a way to achieve fast replay of EIM/DEIM by just storing the small relevant information to rebuild the vectors and matrices. the information would be the \mu_i
​​  to compute the basis (vectors or matrices or finite element fields) and the t_​i
​​  the points(and the geomap context). This should be sufficient to rebuild everything unless I am missing something but if I am missing something then we save it.

This is a good compromise because we store only very little information and we can just have an EIM/DEIM mode that takes these data and reconstruction the vectors/matrices/finite element fields
The information would be stored in a json data file as metadata for eim/deim

/cc @vincentchabannes

**Comment by prudhomm** [comment]
missing something but I don't think so). Part of eim/deim is being re-run but the most costly parts are not redone.

**Comment by prudhomm** [comment]
This would also be useful for enrighment of (d)eim basis

**Comment by prudhomm** [comment]
@jbwahl have you given some thoughts to this ?
@vincentchabannes @jbwahl we need to review what is needed here so that we can use EIM/DEIM efficiently and now have to redo everything all the time.

**Comment by prudhomm** [comment]
@jbwahl  how about this one? I remember some discussions but I am not sure about the current support in Feel++

**Comment by jbwahl** [comment]
All is ok with recent development in `feature/deim`

**Comment by prudhomm** [comment]
then update the PR description, list the issues and make sure to close the issues either in commits or after the PR is merged
