### ISSUE TITLE
HDG : support static condensation with dynamic product space

### ISSUE THREAD

**Issue by romainhild** [feelpp/feelpp#867]
@prudhomm For now, we determine if there integral boundary condition by the number of spaces in the product space. But this works only if the product space is static.
In the case where we use a dynamic space for the ibc, it is counted even if its size is 0.
See [blockforms.hpp line 192](https://github.com/feelpp/feelpp/blob/feature/hdg-sc/feel/feelvf/blockforms.hpp#L192)

**Comment by prudhomm** [comment]
Done
