### ISSUE TITLE
Refactor SER algorithm 

### ISSUE THREAD

**Issue by prudhomm** [feelpp/feelpp#876]
We need to 
 - [x] Extract SER from OpusApp Class
 - [x] have a class of its own
 - [ ] have it work seamlessly for EIM and DEIM
 - [ ] check that it works with existing tests

**Comment by prudhomm** [comment]
@jbwahl a branch `feature/ser` should be created

**Comment by jbwahl** [comment]
@prudhomm i extracted SER from opusapp and i tested it on grepl benchmark.
If it is ok for you, i proposed to merge this in develop and i will continue the work with deim in the `feature/deim` branch

**Comment by prudhomm** [comment]
why not in the branch ?

**Comment by prudhomm** [comment]
if you implemented it in `develop` just  `git checkout -b feature/ser` to create the branch before committing

**Comment by jbwahl** [comment]
@prudhomm i already pushed the branch `feature/ser` with the modifications.
But for the integration of DEIM in SER i propose to do it in the `feature/deim` branch.

**Comment by prudhomm** [comment]
link with commit 43f9aa9
