### ISSUE TITLE
install-feelpp-lib can't finish because of mesh_partitioner

### ISSUE THREAD

**Issue by Doyeux** [feelpp/feelpp#882]
if HDF has no mpi support, `feelpp_mesh_partitioner` can't be built but make install-feelpp-lib still tries to copy this file and the install fails.

for a complete install, one has to "hack" the CMakeLists.txt or do a `touch feelpp_mesh_partitioner`

**Comment by prudhomm** [comment]
@vincentchabannes has this been fixed ?

**Comment by prudhomm** [comment]
@vincentchabannes it would be good to have a guard/fix for milestone v0.103 which is due over the weekend

**Comment by vincentchabannes** [comment]
it has been fixed
