### ISSUE TITLE
Add debian build support 

### ISSUE THREAD

**Issue by prudhomm** [feelpp/feelpp#892]
Add debian scripts to Feel++ so that we can build debian/ubuntu packages more easily and systematically

**Comment by prudhomm** [comment]
@Trophime could you add the debian directory to feel++ ? so that we can start deploying feel++ debian/ubuntu packages ? do you think we could have that before the end of the week so that we can deploy this for mso4sc workshop

**Comment by Trophime** [comment]
@prudhomm I run into several issues:
* building feelpp + testsuite + models requires a lot of disk space. 
Could you give some figures? To work around this I plan to split the main src package into several src packages one for each physic. Is there a way to generate only the libs and headers common to all models (ie modelalg, modelcore,...)
* is there a way to compile and run a minimal testsuite to keep disk space requirement low
* the so lib installed should all be "versionned". This is not the case metis nor for the "model" so lib.
Moreover it seems that feelpp-glog is not numbered as the others

**Comment by Trophime** [comment]
One more point:
* I've used only the feelpp target which seems not to build mesh apps that should be shipped !!

**Comment by Trophime** [comment]
It is functional now. The scripts are included in https://github.com/feelpp/hifimagnet/tree/develop/package
with a detailed procedure to build a local debian repository.

To go further I would need some help to split the hifimagnet repository into seperate projects:
* magnettools
* salome hifimagnet plugins
* docker images: salome, hifimagnet, ensight, novnc, sregistry-cli...
* singularity images: .....
* debian/ubuntu packaging and local repository management
and make some cleanup.

That would be also great to update the pipelines to build packages, docker/singularity images and store them... Some preliminary pipelines are already defined in Buildkite

**Comment by prudhomm** [comment]
@Trophime regarding packaging the feelpp debian/ubuntu packages were in TPS, may be they should go in feelpp/feelpp-debian or something like that

**Comment by prudhomm** [comment]
done, see feelpp.plg
