### ISSUE TITLE
Missing hpddm and others from source archive tarball

### ISSUE THREAD

**Issue by Trophime** [feelpp/feelpp#893]
When creating and dowloading the source archive tarballs from github neither hpddm nor nlopt nor ipot are included in the sources.

This causes some problem when building Feel++ from this archive.

**Comment by prudhomm** [comment]
The tarballs on Github are generated automatically by Github and do not contain the submodules. To solve this we need to upload our own tarballs generated by `make package_source` which will contain hpddm and nlopt
