### ISSUE TITLE
Add an option for max dimension of the fluid model

### ISSUE THREAD

**Issue by cpivot** [feelpp/feelpp#899]
Hi, 
It would be great if we had an option to choose the max dimension of the fluid model
It should sounds something like `cmake /path/to/feelpp -DFEELPP_MAX_FLUIDMODELS_DIM=2`

And for exemple in /path/to/feelpp/CMakeLists.txt add 
`OPTION(FEELPP_MAX_FLUIDMODELS_DIM "Max dimension for the models" 3)`

And in /path/to/feelpp/toolboxes/feel/feelmodels/fluid/CMakeLists.txt change each 
`foreach( _DIM 2 3)` to something like
`foreach(_DIM RANGE 2 ${FEELPP_MAX_FLUIDMODELS_DIM} 1)` 

such that the compilation time and the final size get lower.
Thank's 
Charles

**Comment by cpivot** [comment]
By the way, we can do this for the other models (like solid and thermodyn) 
And may be it would be easier to have one option for the max dim, ie replace in my previous message `OPTION(FEELPP_MAX_FLUIDMODELS_DIM "Max dimension for the models" 3)`
to `OPTION(FEELPP_MAX_MODELS_DIM "Max dimension for the models" 3)`

**Comment by prudhomm** [comment]
@cpivot out of curiosity what is the setting of the computer you use (n cpus and memory ) ?
also what is the OS that you are using ? 
are you developing in the CFD toolbox or "just" using it ?

**Comment by cpivot** [comment]
@prudhomm My computer is a simple one (4cpus and 8Go of ram)
Before yesterday, I was on ubuntu, but I finally got docker.
I use the CFD as a library in my C++ code, so I have to compile feelpp (or may be there is another solution). I have to do so because I do some flow control.
I noticed that the size of the entire library is impressive (my last docker image was something like 130go). There is a lot a of stuff I don't need.

**Comment by prudhomm** [comment]
@cpivot I would be suprised that we deliver 130Go of software ;) however it might be that you get new version of docker images and never clean/remove the older ones.
you should do that once in a while otherwise your harddrive will be filled up. 
There are tools around to help you do that
