### ISSUE TITLE
add a version number to installed libs

### ISSUE THREAD

**Issue by Trophime** [feelpp/feelpp#901]
Hi,
would it be possible to have all the libs installed to be of the form libfeelpp_*.so.x.y.z?

This is the case for some libs but not for all
see for install libfeelpp_metis, and all libs related to models and toolboxes

**Comment by prudhomm** [comment]
This is difficult to do properly in general. It requires being very careful about changes in the api. 
Why do you need that? To track api changes?

**Comment by Trophime** [comment]
to stick to debian standard and avoid lots of lintian errors or warnings mostly

**Comment by prudhomm** [comment]
this is done
