### ISSUE TITLE
Perform performance assessment of HDG/Static Condensation framework

### ISSUE THREAD

**Issue by prudhomm** [feelpp/feelpp#910]
We should profile the implementation of the HDG/Static Condensation framework to understand how it behaves and make proper choices of solution strategies.
In particular we should compare
 - multigrid strategies
 - schwarz methods
 - direct methods

for different polynomials orders (say 1-4) and differents types of equations (say darcy and elasticity). The latter will allow to better understand also the performance hit due to flux or stress computations

**Comment by romainhild** [comment]
@prudhomm for Mixed Poisson, I started to add some configurations for the benchmarks see 7279985acd3dc27187fc87046707fcd66cff77ec. There is a config file for domain decomposition (gasm) and one for multigrid (gamg).
And in 66f5522557a4e77954ccac5b8e3d5dde1da9aa9d, I save the time for the different parts of the resolution.

**Comment by prudhomm** [comment]
This is done.
