### ISSUE TITLE
Support block problems in CRB 

### ISSUE THREAD

**Issue by prudhomm** [feelpp/feelpp#912]
multiphysic problems requires product of spaces as well as a block type algebraic handling.
This should be also supported in CRB

**Comment by prudhomm** [comment]
this is related to #845

**Comment by prudhomm** [comment]
This is handled by #845 no ? it is not only handling saddle point problems @jbwahl @vincentchabannes  ?

**Comment by jbwahl** [comment]
Indeed it can be used for any problem with 2 physical fields, the construction of the supremizer, specific to saddle point problem, is an option.
