### ISSUE TITLE
CRB hifimagnet models

### ISSUE THREAD

**Issue by prudhomm** [feelpp/feelpp#915]
@Trophime we need to discuss the CRB thermo-electric hifimagnet application, @romainhild has redesigned one in Feel++ that works already in linear. 
The hifimagnet one can serve as a reference but it may be complicated to maintain it in the long run. 

Also there is the question of having some "open" hifimagnet testcase that could be usable in Feel++ so that we can show case the hifimagnet  models

**Comment by romainhild** [comment]
They work now.
