### ISSUE TITLE
Add magnetostatic toolbox 

### ISSUE THREAD

**Issue by prudhomm** [feelpp/feelpp#919]
Add support for magnetostatic toolbox in Feel++, compute the potential vector and magnetic flux given some current density

**Comment by prudhomm** [comment]
This is linked to the toolbox thermo-electrostatic toolbox

**Comment by prudhomm** [comment]
@gdolle use the work by @romainhild in hifimagnet

**Comment by prudhomm** [comment]
this is a duplicate with #1155

**Comment by romainhild** [comment]
We close this issue and keep the other one.
