### ISSUE TITLE
Add support for DEIM

### ISSUE THREAD

**Issue by prudhomm** [feelpp/feelpp#925]
deim provides an algebraic version of eim

**Comment by jbwahl** [comment]
TODO list for DEIM : 

- [ ] Stock solutions for NL problems during greedy (eventually save these solutions on disk)

- [ ] Save and load greedy selection for reload (with option)

- [ ] SER interface

**Comment by prudhomm** [comment]
@jbwahl the second point refers to #866

**Comment by jbwahl** [comment]
@prudhomm right but i thought it was good to have an overview of the whole todo list here.

**Comment by prudhomm** [comment]
sure but add the reference for discussion. This may not be ovious for everybody
