### ISSUE TITLE
implement unique ids for CRB DB

### ISSUE THREAD

**Issue by prudhomm** [feelpp/feelpp#929]
instead of having lors of directories (which does not scale) to differentiate between different setup for a CRBModel, use uuid

**Comment by romainhild** [comment]
@prudhomm j'ai essayé de merge develop dans la branch bs-rb2, et depuis j'ai l'erreur suivante à la compilation:
```
/home/feelpp/feelpp/feel/feelcrb/eim.hpp:1806:91: error: no member named 'id' in 'Feel::Thermoelectric'
        super( space, model->parameterSpace(), sampling, model->modelName(), name, model->id() ),
```
qu'est ce que doit retourner `id()` ?
