### ISSUE TITLE
Boost::DLL no available on Debian/Jessie with Boost 1.55

### ISSUE THREAD

**Issue by Trophime** [feelpp/feelpp#934]
Trying to rebuild feelpp from scratch on Debian/jessie with boost 1.55, I run into this pb:
```
/home/LNCMI-G/trophime/github/feelpp/feel/feelcrb/crbplugin_interface.cpp:24:10: fatal error: 'boost/dll.hpp' file not found
#include <boost/dll.hpp>
```
Is there a minimal requirement for boost for latest dev feelpp?

**Comment by prudhomm** [comment]
you need to have at least boost 1.61

**Comment by prudhomm** [comment]
@Trophime now boost 1.61 is required for boost.dll
see 9c433677703e37c0466e1623df98ed9a92cc31cb
