### ISSUE TITLE
support load/modify last CRB DB online and offline

### ISSUE THREAD

**Issue by prudhomm** [feelpp/feelpp#946]
With the new DB system for CRB based on the unique ids, it is a bit cumbersome/tedious to load a DB in the online stage
For the online part, I have already added
 - `loadDBFromID` which enables loading from the DB id or part of the last digits of the DB id 
 
I now proposed to add
 - `loadDBLast` which will load the last created or modified DB. By default it will load the last modified DB. the interface is as follows

```c++
 virtual void loadDBLast ( crb::last l = crb::last::modified, std::string const& root = Environment::rootRepository() );       
```
where `crb::last` is an enum class specifying the last mode:
```c++
namespace crb{
enum class last    {
 created=0,
 modified = 1
}
}
```
The online plugin can then easily load the DB.
The next step is to propose something similar for the offline stage in order eg to restart a DB build

thoughts ?

**Comment by prudhomm** [comment]
@vincentchabannes Looking at https://github.com/feelpp/feelpp/blob/develop/feel/feelcrb/crbelementsdb.hpp#L388 or the equivalent in the hdf5 format I wonder why *restarting* ever worked if we don't use directly a `.msh` or `.h5` file. 

Indeed it seems that the load function do not load the mesh but use the one from the model. Hence if the mesh is rebuilt from a `.geo` file we may be in trouble here. 
Either we get a crash if the mesh as a different number of elements/nodes or we could get wrong results if the mesh has the same number of elements or we get good results if the mesh is really the same as in the DB.
I am clearly getting these scenarii while working with `heat3d` and trying to restart/continue/enhance the RB DB.



a fix is to use the .msh file (simplest but not fool proof)
another one is to actually load the mesh saved  in the DB to reinitialize the model

any thoughts ? am I missing something ?

PS: the loading strategies described above work nicely online and offline now. Except offline is the mesh is re-generated from a `.geo`

**Comment by vincentchabannes** [comment]
it will better if we can reuse the mesh in the db. Maybe, the class ModelCrbBase can manage the mesh.

**Comment by prudhomm** [comment]
my thoughts exactly. 
The mesh (and hence the Fe model) should be reinitialized from the DB loading function. 
If I use the `.msh` instead of the `.geo` everything is good but still this is not satisfactory because the mesh might be different from the mesh used to generate the DB. That way it will be fool proof. this triggers a nasty bug which may be difficult to detect.

**Comment by prudhomm** [comment]
@vincentchabannes I think that should simplify the use of the new DB system

initial build
```
./feelpp_crb_heat3dapp --config-file heat3d/heat3d.cfg --crb.rebuild-database=1 --crb.dimension-max=4
```
enhance 1
```
./feelpp_crb_heat3dapp --config-file heat3d/heat3d.cfg --crb.rebuild-database=0 --crb.dimension-max=10
```

enhance 2
```
./feelpp_crb_heat3dapp --config-file heat3d/heat3d.cfg --crb.rebuild-database=0 --crb.dimension-max=12
```

Note that by default it uses the loading strategy `--crb.db.load=1` (last modified).
Four modes:
 - `--crb.db.load=0`  : load from filename (use `--crb.db.filename`)
 - `--crb.db.load=1`  : last db modified 
 - `--crb.db.load=2`  : last db created (often same as last one but not necessarily it could be older)
 - `--crb.db.load=3`  : load from db id (use `--crb.db.id`)

**Comment by prudhomm** [comment]
Note that for `--crb.db.id` the last few (say 2 or 3) digits of the uuid is sufficient
e.g
instead of 
```
crb.db.id=9456a8f3-8800-4b64-80af-1943e6904c45
```
one can write
```
crb.db.id=c45
```
just make sure that there are no other DB uuid for the model finishing with `c45`

**Comment by prudhomm** [comment]
The last bit missing in this issue is to allow updating a DB offline by providing the `db.id`

**Comment by vincentchabannes** [comment]
It doesn't work with EIM. The uid is reload in CRB class but EIM is built before to use CRB. I think, it should be move in ModelCrbBase.

**Comment by prudhomm** [comment]
Ok. I would need to get back to this. How hard is it going to be?
