### ISSUE TITLE
Missing output implementation in Biosavart

### ISSUE THREAD

**Issue by prudhomm** [feelpp/feelpp#948]
It was failing to build, I added an empty implementation but we need to have something like magnetic flux computed through one or multiple surfaces

**Comment by prudhomm** [comment]
@romainhild  where do we stand here? From our last discussion, I had the impression that this has been fixed? is that the case? could you elaborate and possibly link to a commit if you already did it?

**Comment by romainhild** [comment]
This file should not be used anymore, see in mor/thermoelectric now.
