### ISSUE TITLE
Fix  expansion calls

### ISSUE THREAD

**Issue by prudhomm** [feelpp/feelpp#951]
the `expansion` functions seems to have been changed and now `Feel::expansion()` needs to be called. We need to modify quite a bit of functions calls to fix compilation

**Comment by prudhomm** [comment]
@vincentchabannes @jbwahl could you check the `expansion` calls ?
why had the interface changed ?

**Comment by jbwahl** [comment]
@prudhomm interface changed for crb saddle point. I will check this today

**Comment by prudhomm** [comment]
ok thanks

**Comment by prudhomm** [comment]
Ok thx @jbwahl I merge in `feature/rb-load`

**Comment by romainhild** [comment]
Isn't it [this line](https://github.com/feelpp/feelpp/blob/develop/feel/feelcrb/crb.hpp?utf8=%E2%9C%93#L9244) that poses problem ?
```
return Feel::expansion( WN, u, N );
```

**Comment by prudhomm** [comment]
@jbwahl  should it be closed ?
