### ISSUE TITLE
add support the mongo c++ driver

### ISSUE THREAD

**Issue by prudhomm** [feelpp/feelpp#953]
We shall use mongodb as a database system to query reduced basis DB. The mongo C++ driver can provide the interface with the mongodb server and enable 
 - queries from within C++ codes
 - insertion of json files (might be delicate to handle)

here is the local fork of [mongo-cxx-driver](https://github.com/feelpp/mongo-cxx-driver)

**Comment by prudhomm** [comment]
Regarding docker support it will require installing
 - libbson-dev
 - libmongoc-dev
 - mongodb
 - mongo-tools

the first two are for development, the last two are the mongodb server and the tools that we will use to setup the DB for our json files

**Comment by prudhomm** [comment]
with monggodb it will be easier to use the models, for example here is a query in the mongo shell
```js
> var a=db.crbdb.find({$and:[{"crbmodel.name" : "heat1d"},{"crb.output-index":"0"}]}).toArray()
> a[0].crb
{
    "dimension" : "6",
    "name" : "heat1d",
    "database-filename" : "heat1d.crb.crbdb",
    "has-solve-dual-problem" : "true",
    "output-index" : "0",
    "error-type" : "1"
}
```
with `crb_onlinerun` it may look like this in the future
```
feelpp_crb_onlinerun --query "{$and:[{"crbmodel.name" : "heat1d"},{"crb.output-index":"0"}]}"
```
it will run the output 0 DB, or
```
feelpp_crb_onlinerun --query "{"crbmodel.name" : "heat1d"}"
```
will run both output 0 and 1 associated online codes

**Comment by gdolle** [comment]
Just a comment we should keep mongodb as a weak dependency. 

We should create a Feel++ tool `./feelpp_database [--input-dir] <JSON list>` to generate the database from merged .json from `~/feeldb` simulations.
Then enable query from that database for a python/post process usage.

To import a JSON file into a mongodb database "feeldb" into a `simulation` collection
from the shell
```
mongoimport --db feeldb --collection simulation heat1d.json
mongoexport --db feeldb --collection simulation heat1d.json
```
A specific mongdb identy entry `_id` is added to the json.

Note: Check [this API function](http://api.mongodb.com/cplusplus/current/namespacemongo.html#aa0d5ccd386edb7031d272670199997ea) to import JSON using the cxx driver.
I think we can use it directly with ptree.

**Comment by prudhomm** [comment]
@gdolle the dependency should be weak in the sense of *optional*. I see the C++ mongo driver as the way to integrate mongo queries to a possible mongodb. From what I have read this is rather easy (a few lines) to do and it would enable tremendous  possibilities in my opinion (well not clear if these possibilities are all useful ;) )

regarding importing, that's what I used to show the queries above (there are real queries, not fake ones ;) )

**Comment by gdolle** [comment]
@prudhomm Ok! I was just a bit worried you wanted to use mongodb as a permanent query tools for CRB :D

**Comment by prudhomm** [comment]
well the alternative is to build one ourself and it might be just a lot of work without the expertise. 
we need to be able to query on the database easily
