### ISSUE TITLE
Ipopt support broken

### ISSUE THREAD

**Issue by prudhomm** [feelpp/feelpp#956]
Ipopt support in Feel++ is currently broken (at least in branch feature/rb-load). It seems that there are missing libraries that should be associated and installed with `feelpp_ipopt`.

**Comment by prudhomm** [comment]
`ipopt` is currently disabled in `contrib.dependencies.cmake`

**Comment by prudhomm** [comment]
- [ ] is it ok now ? 
- [ ] is the testsuite running ok ? 
- [ ] should it be closed ?

**Comment by prudhomm** [comment]
How about the testsuite ? test_ipopt is operational ?

**Comment by gdolle** [comment]
Yes 👍
