### ISSUE TITLE
Add support for llvm >= 3.9 and clang using gcc6 at unistra

### ISSUE THREAD

**Issue by prudhomm** [feelpp/feelpp#958]
Is it possible to have
 - llvm and clang 3.9 compiled with GCC6
 - llvm and clang 4.0 (4.0.1 is out) compiled with GCC6
at mesostra

thanks in advance

**Comment by DBrusson** [comment]
Done.
**module load compilers/clang39** or **module load compilers/clang40**

**Comment by vincentchabannes** [comment]
@DBrusson it seems that clang39 and clang40 were compiled with gcc4.8.2 ( /usr/lib/gcc/x86_64-redhat-linux/4.8.2). We need to have clang compiled with gcc63

**Comment by DBrusson** [comment]
They were compiled with gcc-6.2.0 (they can't be compiled with gcc63 due to a problem with std::atomic stuff)

**Comment by vincentchabannes** [comment]
if fact no, you can see that typing ```clang++ -v```.
I have this on hpc-login :
``` 
[chabannes@hpc-login1 ~]$ module load compilers/clang40
[chabannes@hpc-login1 ~]$ clang++ -v
clang version 4.0.1 (tags/RELEASE_401/final)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/local/llvm/llvm-4.0.1/bin
Found candidate GCC installation: /usr/lib/gcc/x86_64-redhat-linux/4.8.2
Found candidate GCC installation: /usr/lib/gcc/x86_64-redhat-linux/4.8.5
Selected GCC installation: /usr/lib/gcc/x86_64-redhat-linux/4.8.5
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Selected multilib: .;@m64
```

**Comment by DBrusson** [comment]
Really strange, here is the CMakeCache :
[CMakeCache.txt](https://github.com/feelpp/feelpp/files/1155782/CMakeCache.txt)

and if you try using it without gcc62 (or a more recent version of gcc) it won't work at all

**Comment by vincentchabannes** [comment]
I have also some troubles with gcc63 (the lib cmath seems not work). I use gcc62, but I can not run a real mpi job with  mpi/openmpi-2.0.2.gcc63. I need to switch on mpi/openmpi-2.0.gcc62   but I have a lot of warning when run configuration build of feel++  because others dependencies like petsc are compiled with mpi/openmpi-2.0.2.gcc63. However, it seems work.

**Comment by vincentchabannes** [comment]
@DBrusson ok I will try.

**Comment by vincentchabannes** [comment]
@DBrusson I confirm, clang is linked to gcc4.8 libraries, not gcc62. The full support of c++14 is missing. You can test with this code ( ```clang++ toto.cpp -o toto -std=c++14```) : 
```cpp
#include <iostream>
#include <complex>
 
int main()
{
    using namespace std::complex_literals;
    std::complex<double> c = 1.0 + 1i;
    std::cout << "abs" << c << " = " << abs(c) << '\n';
}
```
It doesn't work with clang but it compile fine with gcc62

**Comment by vincentchabannes** [comment]
@DBrusson @celineCQ  I finally succeeded to compile feel++ with clang but by adding ```--gcc-toolchain=/usr/local/gcc/gcc-6.2.0``` in ```CMAKE_CXX_FLAGS``` and ```CMAKE_C_FLAGS```. I saw that you created an alias of clang with the toolchain path (and only the frontal) but I think it's not a good solution. When we detect the compiler with cmake it doesn’t take into account the gcc-toolchain option contained in the alias.
In reading your CMakeCache.txt, I think you forgot to set ```GCC_INSTALL_PREFIX=/usr/local/gcc/gcc-6.2.0```  in order to use by default the gcc62 toolchain.

**Comment by DBrusson** [comment]
You're entirely right. I've made that quick dirty fix because I was running out of time yesterday. I'm recompiling a correct version of clang right now, with a proper fix

**Comment by DBrusson** [comment]
Now both 3.9 and 4.0 version of clang should be allright :
"""
 [brusson@hpc-login1 ~]$ clang -v
clang version 6.0.0 (trunk 308733) (llvm/trunk 308730)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/local/llvm/llvm-4.0.1/bin
Found candidate GCC installation: /usr/local/gcc/gcc-6.2.0/lib/gcc/x86_64-pc-linux-gnu/6.2.0
Selected GCC installation: /usr/local/gcc/gcc-6.2.0/lib/gcc/x86_64-pc-linux-gnu/6.2.0
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Selected multilib: .;@m64
"""

**Comment by vincentchabannes** [comment]
@DBrusson yes, it's good with clang. thanks !
