### ISSUE TITLE
Issue with fftw using mpirun on a mesostra compute node

### ISSUE THREAD

**Issue by prudhomm** [feelpp/feelpp#960]
We have another issue with `mpirun` ( in an interactive job). 
```
mpirun -np 4 ./quickstart/feelpp_qs_laplacian_2d  --ksp-monitor=1 --functions.f=1
error while loading shared libraries: libfftw3.so.3: cannot open shared object file: No such file or directory
```
There is no problem in sequential without mpirun.
The config is :
```
module list
Currently Loaded Modulefiles:
  1) batch/slurm               2) cmake/cmake-3.4.1         3) compilers/gnu62           4) libs/boost-1.63.gnu63     5) mpi/openmpi-2.0.2.gcc63   6) petsc/petsc-3.7.6.g63     7) mesh/gmsh-3.0.1.g63       8) compilers/intel17
```

**Comment by DBrusson** [comment]
The problem is that it was compiled with an FFTW which is installed on the connexion node but not on the compute nodes.
I've just compiled a FFTW version with the gnu compiler, if you use it the problem should be fixed
**module load libs/fftw3.3.6.g63**

**Comment by prudhomm** [comment]
I think this can be fixed now
