### ISSUE TITLE
Support singularity @ mesostra

### ISSUE THREAD

**Issue by prudhomm** [feelpp/feelpp#961]
We have docker and singularity images for Feel++. Singularity images are adapted to cluster and supercomputers. Could it be possible to install and support singularity @ mesostra ?

here is our setup on atlas our local computer 
http://book.feelpp.org/clusters/atlas/

here is the website for singularity http://singularity.lbl.gov/

**Comment by prudhomm** [comment]
Hi guys, when do you want to start the discussion?

**Comment by celineCQ** [comment]
Hi,
The discussion started (offline), but will be taken online (here) as soon as the installation starts.

**Comment by gdolle** [comment]
Bump to current testing.

**Comment by prudhomm** [comment]
@DBrusson @vincentchabannes singularity is now supported on alsacalcul right ?
where is the associated document to run properly with singularity

**Comment by prudhomm** [comment]
our documentation about the supercomputer is here http://docs.feelpp.org/feelppdocs/stable/infra/alsacalcul/

@vincentchabannes it needs probably to be updated now ? it is vastly out of date

**Comment by DBrusson** [comment]
Some documentation can be found here : https://hpc.pages.unistra.fr/singularity/singularity.html
But if you already have a singularity image, the main idea is : load module **singularity/singularity** and then run your image with **mpirun singularity run my_image**

Oh, by the way, the name of the cluster is not Alsacalcul. In fact, it doesn't really have a name, but we use to call it "Centre de Calcul de l'Université de Strasbourg (CCUS)"(yeah, straight to the point)

**Comment by prudhomm** [comment]
@DBrusson thanks a lot. are there any particular issues with the presence or not of some libs in the singularity to ensure proper performance ?
