### ISSUE TITLE
Singularity build fails

### ISSUE THREAD

**Issue by prudhomm** [feelpp/feelpp#964]
See buildkite failure in screenshot attached or [here](https://buildkite.com/feelpp/feelpp/builds/1861#396e29c9-4b0e-4a82-b75b-f4ee73e60019)

<img width="1058" alt="screenshot 2017-07-15 20 26 04" src="https://user-images.githubusercontent.com/151693/28241806-e3ac5bf8-699b-11e7-8dc4-ca22611348a2.png">

**Comment by gdolle** [comment]
This is solved.
