### ISSUE TITLE
ship headers for mesh adaptation

### ISSUE THREAD

**Issue by chifaadahik** [feelpp/feelpp#969]
`fatal error: 'Field.h' file not found
#include <Field.h>`
when including :
`#include<feel/feelmesh/meshadaptation.hpp>`

**Comment by prudhomm** [comment]
@chifaadahik tu peux faire une ref à un autre repository et dire : fixed thanks to feelpp/feelpp#969
ce qui est le cas ;)

**Comment by chifaadahik** [comment]
ok merci :)

**Comment by gdolle** [comment]
https://github.com/feelpp/feelpp/blob/a82362fc676e3992f3cbf9692b8e5cfbbebf0048/cmake/modules/FindGmsh.cmake#L92-L101
This check is required for non contrib gmsh install (that do not have adaptmesh headers).

**Comment by prudhomm** [comment]
@Trophime after discussion with @vincentchabannes this can be closed
