### ISSUE TITLE
How to set entries of algebraic representation in linear forms

### ISSUE THREAD

**Issue by miinguyen** [feelpp/feelpp#971]
In non- linear problem when using Newton's method and we have Dirichlet boundary conditions, we need to set the Dirichlet entries of the Jacobian and residual to zero except of cours the diagonal which is set to one. If the solution has Dirichlet boundary condition then the increment has zero Dirichlet condition.

**Comment by miinguyen** [comment]
Use the technical of copy an element of function space `Vh` in order to use the operation `on` in each increment of the residual:

----
auto w = Vh->element();
w=*R; // copy residual in v
// set the unknowns on the boundary to 0
w.on(_range=markedfaces(mesh,"Dirichlet"),_expr = q);
// copy back to R
*R=w;
----

**Comment by prudhomm** [comment]
@miinguyen does that work ? what are the results in the strong and weak cases ?

**Comment by miinguyen** [comment]
@prudhomm  It's work. The two cases gives almost the sames results. For exemple:
In strong case, It converges in the 6-th iteration ` 6  SNES Function norm 5.625101e-12` and in weak case, it's ` 6  SNES Function norm 5.625918e-12`.

**Comment by miinguyen** [comment]
It's work with non-homogene Dirichlet's condition too @prudhomm
