### ISSUE TITLE
Support hdf5 format to save PETSc vectors

### ISSUE THREAD

**Issue by jbwahl** [feelpp/feelpp#972]
It would be usefull for large // parallel problem to support hdf5 format for petsc vectors.
For now only ascii and binary format exist for petsc vectors.
hdf5 if also available for ublas vectors.

An important use case where the benefit would be very important is when we store the intermediate results for the offline step of the reduced basis methodology and in particular the computation of the offline a posteriori estimator/error bounds quantities

**Comment by prudhomm** [comment]
why is is necessary in the deim algorithm ? haven't we already discussed that ? likewise we don't want to store the matrices

**Comment by prudhomm** [comment]
There was a discussion in #866

**Comment by jbwahl** [comment]
Actually it is not for DEIM but for the evaluation of the residual in CRB algorithm.
We discussed with @vincentchabannes to write the vectors on disk instead of reevaluating all the vectors in each loop. (as it is implemented in https://github.com/feelpp/feelpp/blob/develop/feel/feelcrb/crbsaddlepoint.hpp#L966 )
For now I use binary save with boost serialization for petsc vectors but hdf5 format would be more appropriate for // run.

**Comment by prudhomm** [comment]
@jbwahl then you should update the description of the issue and be more precise. It was not quite clear ;)

**Comment by prudhomm** [comment]
@jbwahl @vincentchabannes  should it be closed? is it still on-going dev or is it done?

**Comment by jbwahl** [comment]
The actual solution is to transform the PETSc vector into ublas vector and then save it with hdf5.
At some point, we should add a specific function for PETSc vectors but it is not done for now. 
agree @vincentchabannes  ?

**Comment by prudhomm** [comment]
@vincentchabannes?

**Comment by prudhomm** [comment]
There is this function [PetscViewerHDF5Open](http://www.mcs.anl.gov/petsc/petsc-current/docs/manualpages/Viewer/PetscViewerHDF5Open.html#PetscViewerHDF5Open)
and the code is [here](http://www.mcs.anl.gov/petsc/petsc-current/src/sys/classes/viewer/impls/hdf5/hdf5v.c.html#PetscViewerHDF5Open).

By the way, they use HDF5 to stack up fields in time.
