### ISSUE TITLE
Submesh creation : conservation of elements ID

### ISSUE THREAD

**Issue by jbwahl** [feelpp/feelpp#973]
For now we only conserve the points ids when we create a submesh.
The conservation of the elements ids is needed for the online part of DEIM #925.
This issue should be closed with in the branch `feature/functionspace-on-range`

**Comment by prudhomm** [comment]
@jbwahl why is that a problem ? you have the correspondance map between the elements of the meshes and the local numbering in the elements is preserved. you can build the mapping from this.
am I missing something ?

**Comment by jbwahl** [comment]
@prudhomm you are probably right ! i missed the correspondance map... i will look at that

**Comment by prudhomm** [comment]
@jbwahl look at the class MeshBase to get the mapping between the meshes

**Comment by jbwahl** [comment]
@prudhomm got it ! Thanks !

**Comment by prudhomm** [comment]
This was already implemented
