### ISSUE TITLE
Effective online phase for DEIM

### ISSUE THREAD

**Issue by jbwahl** [feelpp/feelpp#974]
- [x] Build a submesh from list of elements

- [x] Save submesh and reread it on sequential

- [x] Correspondance between dof and subspace dof

- [x] Add offline and online models in DEIM

**Comment by jbwahl** [comment]
submesh done via #968

**Comment by prudhomm** [comment]
Is it done?

**Comment by jbwahl** [comment]
Some work has to be done for composite spaces. But it works with simple function spaces

**Comment by prudhomm** [comment]
should it be closed ?

**Comment by jbwahl** [comment]
Will be close with the merge of `feature/deim`
