### ISSUE TITLE
Exporter in a `for` loop

### ISSUE THREAD

**Issue by PhilippeRicka** [feelpp/feelpp#976]
I wrote the following lines in the end of a for loop.
```
    auto e = exporter( _mesh=mesh );
    e->addRegions();
    e->step(t)->add( "u", u );
    e->step(t)->add( "p", p );
    e->save();
```
I basically created an exporter at each time step overwriting the previous ones. I should have written this way instead.
```
auto e = exporter( _mesh=mesh );
for( double t = dt; t < T; t += dt )
{
    // do stuff with u and p
    e->step(t)->add( "u", u );
    e->step(t)->add( "p", p );
    e->save();
}
```
It would be useful to document the Exporter class usage.

**Comment by prudhomm** [comment]
Issue moved to [feelpp/book.feelpp.org #38](https://github.com/feelpp/book.feelpp.org/issues/38) via [**ZenHub**](https://www.zenhub.com/)
