### ISSUE TITLE
Crash of thermoelectric CRB online application

### ISSUE THREAD

**Issue by prudhomm** [feelpp/feelpp#991]
@romainhild it seems that the online thermoelectric CRB crashes using the DB in feel/crbdb

```
/feelpp_crb_onlinerun --query "crbmodel.name:thermoelectric"
[ Starting Feel++ ] application crbonlinerun version 0.104.0-alpha.20 date 2017-Jul-27
 . crbonlinerun files are stored in /home/prudhomm/feel/crbonlinerun/np_1
 .. exports :/home/prudhomm/feel/crbonlinerun/np_1/exports
 .. logfiles :/home/prudhomm/feel/crbonlinerun/np_1/logs
document { "$and" : [ { "crbmodel.name" : "thermoelectric" } ] }
Loaded the plugin thermoelectric
 . using db /home/prudhomm/feel/crbdb/thermoelectric/1ad46e85-f0f0-46bc-aa07-1002a1863458/thermoelectric.crb.json
dimension of parameter space : 5
min element in parameter space : 290 0.05 0.05 0.35 57500 
max element in parameter space : 310 0.1 0.1 0.4 58500 
--------------------------------------
mu[0] : 304.621 0.0721006 0.0950838 0.355089 58472.9 
*** Aborted at 1501143868 (unix time) try "date -d @1501143868" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGSEGV (@0x50) received by PID 10786 (TID 0x7f1f257e98c0) from PID 80; stack trace: ***
    @     0x7f1f16f14670 (unknown)
    @     0x7f1edf65c76e _ZN4Feel9expansionINS_13FunctionSpaceINS_4MeshINS_7SimplexILt3ELt1ELt3EEEdLi0EEENS_5basesIJNS_8LagrangeILt1ENS_6ScalarENS_10ContinuousENS_18PointSetEquiSpacedELt0EEESB_EEEdN5boost9parameter5void_ESF_E7ElementIdNS_11VectorUblasIdNSD_7numeric5ublas6vectorIdNSK_15unbounded_arrayIdSaIdEEEEEEEEEN5Eigen6MatrixIdLin1ELi1ELi0ELin1ELi1EEEEET_RKSt6vectorISV_SaISV_EERKT0_i
    @     0x7f1edf487f6e Feel::CRB<>::expansion()
    @     0x7f1edf476366 Feel::CRB<>::fixedPointPrimal()
    @     0x7f1edf57a28f Feel::CRB<>::fixedPoint()
    @     0x7f1edf46f739 Feel::CRB<>::lb()
    @     0x7f1edf66125a Feel::CRB<>::run()
    @     0x7f1edf2f9351 Feel::CRBPlugin<>::run()
    @           0x4232fe runCrbOnline()
    @           0x422218 runCrbOnlineQuery()
    @           0x427897 main
    @     0x7f1f138443f1 __libc_start_main
    @           0x41fe9a _start
    @                0x0 (unknown)
Segmentation fault
```

**Comment by prudhomm** [comment]
here is the json file

```json
{
    "uuid": "1ad46e85-f0f0-46bc-aa07-1002a1863458",
    "crbmodel": {
        "name": "thermoelectric",
        "parameter_space": {
            "dimension": "5",
            "names": [
                "Tw",
                "current",
                "h",
                "k",
                "sigma"
            ],
            "parameters": {
                "Tw": {
                    "min": "290",
                    "max": "310"
                },
                "current": {
                    "min": "0.050000000000000003",
                    "max": "0.10000000000000001"
                },
                "h": {
                    "min": "0.050000000000000003",
                    "max": "0.10000000000000001"
                },
                "k": {
                    "min": "0.34999999999999998",
                    "max": "0.40000000000000002"
                },
                "sigma": {
                    "min": "57500",
                    "max": "58500"
                }
            }
        },
        "additional-model-files": "",
        "eim": {
            "eim_gradgrad": {
                "database-filename": "eim\/eim_gradgrad.eim.crbdb"
            }
        },
        "specifity-of-model": "",
        "affine-decomposition": {
            "mMaxA": [
                "1",
                "1",
                "1",
                "1",
                "1",
                "1"
            ],
            "mMaxM": "",
            "mMaxF": [
                [
                    "1",
                    "1",
                    "1",
                    "1",
                    "1"
                ]
            ],
            "mMaxLinearDecompositionA": ""
        }
    },
    "reduced-basis-space": {
        "mesh-filename": "thermoelectric_mesh_p1.json",
        "database-filename": "thermoelectric.elements_p0.crbdb",
        "dimension": "10",
        "mesh-context": "7",
        "finite-element-space": {
            "dimension": "18034",
            "basis-name": "lagrange_lagrange"
        }
    },
    "crb": {
        "dimension": "10",
        "name": "thermoelectric",
        "database-filename": "thermoelectric.crb.crbdb",
        "has-solve-dual-problem": "false",
        "output-index": "0",
        "error-type": "2"
    }
}
```

**Comment by prudhomm** [comment]
@vincentchabannes @jbwahl could it be that is crash is related to #951

**Comment by romainhild** [comment]
Isn't it [this line](https://github.com/feelpp/feelpp/blob/develop/feel/feelcrb/crb.hpp?utf8=%E2%9C%93#L9244) that poses problem ?
```
return Feel::expansion( WN, u, N );
```

**Comment by prudhomm** [comment]
The frame stack seems to say so. There has been a change of interface

**Comment by prudhomm** [comment]
expansion()  is also a member of crb. Perhaps it is best to use this interface

**Comment by romainhild** [comment]
It seems that the base is empty, `WN.size()=0`
could it be because of the lack of the function `setupSpecificityModel` ?

**Comment by prudhomm** [comment]
But why expansion() is called online? 
Otherwise use  CRB::expansion()

**Comment by romainhild** [comment]
CRB::expansion calls Feel::expansion()
In the nolinear case, the call comes from [here](https://github.com/feelpp/feelpp/blob/develop/feel/feelcrb/crb.hpp?utf8=%E2%9C%93#L4705-L4728)
But there exists a function `computeBetaQm` in [crbmodel.hpp](https://github.com/feelpp/feelpp/blob/develop/feel/feelcrb/crbmodel.hpp#L889) that takes the reduced vector, we should not need to use the expansion.

**Comment by romainhild** [comment]
Why do we need to do go back to the FE dimension [here](https://github.com/feelpp/feelpp/blob/develop/feel/feelcrb/crb.hpp?utf8=%E2%9C%93#L4724-L4728):
```c++
if ( M_useRbSpaceContextEim && M_hasRbSpaceContextEim )
    boost::tie( betaMqm, betaAqm, betaFqm ) = M_model->computeBetaQm( uN[0], mu/*, N*/ );
else
    boost::tie( betaMqm, betaAqm, betaFqm ) =
        M_model->computeBetaQm( this->expansion( uN[0], N ), mu );
```

Even if we don't use the expansion at this point, we will need to compute the coefficients with EIM, so I need to add the function `setupSpecifictyModel`.
The thing is, in the application, I use the name of the parameters to get them. Those names comes from the Parameters section of a json file which path is given as an option. I can't do that when using the plugin. I assume some informations (dimension, min, max) about the parameter space is stored in the database. Can we add the names of the parameters ?

**Comment by romainhild** [comment]
In regard of the expansion error, the problem seems to be that we do not have a reduced basis space context: see [here](https://github.com/feelpp/feelpp/blob/develop/feel/feelcrb/eim.hpp#L2091-L2094). 
Can you explain what is this context and what it is used for ?

Should we call [`updateRbSpaceContextEim`](https://github.com/feelpp/feelpp/blob/5e9266e56cf83328c5fac69a3fa09a3b4ec155c5/feel/feelcrb/modelcrbbase.hpp#L574-L580) at some point ?

**Comment by prudhomm** [comment]
@romainhild yes you should probably call, I haven't looked at the code but you need to build the RB eim context. the RB eim context allows to avoid using the FE interpolation to compute online the eim right hand side of the expression using the RB approx. 
in the right hand side , if you depend on a RB approx, eg `uN` then you need to compute `uN(t_i,\mu)` where `t_i` is one of the magic points. You don't want to use the FE representation to computing but rather compute the reduced basis at the `t_i`. we have 
```
uN(t_i) = \sum_j=1^N uN_j \phi_j(t_i)
```
we need to compute `\phi_j(t_i)` for each `(i,j)` pair and that's the RB eim context !
does that make sense @romainhild ?
/cc @feelpp/crb

**Comment by prudhomm** [comment]
where do we stand on this one? @romainhild  @vincentchabannes?

**Comment by prudhomm** [comment]
@romainhild @vincentchabannes no news on this one, does it mean it is fixed ?

**Comment by prudhomm** [comment]
Then I close the issue. Other problems  should be reported in their issues.
Thanks
